import type { ModuleDraft } from "./types";
import { conversation, listeningLesson, b2ListeningDirection as context } from "./listening-authoring.ts";

export const b2NarrativeModules: ModuleDraft[] = [{
  id: "b2-narratives", title: "Narrativas e mídia cotidiana", level: "B2", prerequisiteId: "b2-pressure",
  description: "Acompanhar relatos, entrevistar, comparar versões e publicar uma síntese responsável de acontecimentos cotidianos.",
  lessons: [
    listeningLesson({ id: "b2-narratives-01", title: "O que mudou no meio do caminho", listening: conversation({ id: "b2-personal-story", title: "O que mudou no meio do caminho", level: "B2", context,
      scene: "Two friends reflecting on a first volunteering experience after meeting at a café. An honest personal story with a small turning point.",
      turns: [
        ["sparky", "When I first volunteered at the food collection point, I thought the difficult part would be carrying heavy boxes. I'd offered to help for one Saturday, and I imagined we would simply sort everything and send it out. I hadn't realised how much checking was involved.", "Quando comecei a ajudar na coleta de alimentos, achei que o difícil seria carregar caixas. Eu me oferecera para um sábado e imaginava apenas separar e despachar tudo. Não sabia quanto trabalho de conferência havia."],
        ["pinky", "What changed your mind? Was there a delivery that you couldn't use, or did the organisers ask you to do something different from what you'd expected?", "O que mudou sua opinião? Houve uma entrega que não podiam usar ou os organizadores pediram algo diferente do que você esperava?"],
        ["sparky", "Both, actually. We received several unlabelled bags. I was about to put them with the other donations when a coordinator stopped me. We needed to identify the contents and check the dates before passing anything on. Speed wasn't the only thing that mattered.", "As duas coisas. Recebemos sacolas sem rótulo. Eu estava prestes a juntá-las às doações quando uma coordenadora me interrompeu. Era preciso identificar o conteúdo e verificar datas antes de repassar. Rapidez não era o único critério."],
        ["pinky", "That must have been uncomfortable at first. It's easy to feel criticised when you're trying to be helpful. Did she explain the reason, or did you have to ask?", "Deve ter sido desconfortável no início. É fácil sentir-se criticado quando se está tentando ajudar. Ela explicou o motivo ou você teve que perguntar?"],
        ["sparky", "She explained it calmly and showed me the checking list. By the end of the morning, I'd started training another volunteer with it. I still helped move boxes, but I understood why the less visible jobs were essential too.", "Ela explicou com calma e mostrou a lista de conferência. No fim da manhã, eu já ajudava outro voluntário a usá-la. Continuei carregando caixas, mas entendi a importância do trabalho menos visível."],
        ["pinky", "So the experience didn't just teach you a new task. It changed what you counted as useful help. That sounds like the strongest part of your story, especially if you're writing about why you decided to keep volunteering.", "A experiência não ensinou apenas uma tarefa. Mudou o que você considera ajuda útil. Essa parece a parte mais forte do relato, especialmente se escrever sobre por que continuou como voluntário."]
      ], gist: ["What is the main change in Sparky's understanding?", "He learns that careful checking is as valuable as visible physical work", "He decides that volunteering never requires physical effort", "He concludes that all donated food is unusable", "O ponto de virada amplia a noção de ajuda útil; não elimina o trabalho físico."],
      detail: ["What was Sparky about to do when the coordinator stopped him?", "Mix unlabelled bags with the other donations", "Leave before his shift had started", "Throw away all the labelled boxes", "Ele ia juntar sacolas sem identificação antes de conferir conteúdo e datas."],
      inference: ["Why does Pinky focus on the less visible jobs?", "They reveal the lesson behind the sequence of events", "They provide proof that Sparky disliked the coordinator", "They show the checking list was unnecessary", "Pinky distingue significado pessoal de mera sequência: é a mudança de compreensão que organiza o relato."],
      mediation: "Conte a experiência a um voluntário iniciante em português, em 70–100 palavras. Preserve o ponto de virada e a orientação prática, sem inventar um conflito com a coordenadora."
    }), rule: "Um relato eficaz apresenta expectativa, acontecimento decisivo e reflexão. Past perfect situa o que aconteceu antes de outro ponto passado: I'd offered. Was about to mostra uma ação prestes a acontecer que pode ter sido interrompida. Escolha os tempos para orientar a cronologia, mas explique também por que o episódio mudou sua perspectiva.",
      example: "I was about to sort the bags when she stopped me.", translation: "Eu estava prestes a separar as sacolas quando ela me interrompeu.",
      vocabulary: "collection point — ponto de coleta\nunlabelled — sem identificação\npass something on — repassar algo",
      pitfall: "Was about to não confirma que a ação aconteceu. Transformar a intenção interrompida em ação concluída altera o relato.",
      gap: "Before that Saturday, I ___ how much checking was involved.", fills: ["hadn't realised", "haven't realised", "don't realise"], gapExplanation: "O ponto de referência é um sábado passado; hadn't realised situa a falta de percepção antes dele.",
      production: "Escreva 180–220 palavras sobre uma experiência que mudou uma expectativa. Marque o contexto, uma ação interrompida ou imprevisto, o ponto de virada e uma reflexão sustentada por um detalhe concreto.",
      speakingTask: "Conte a experiência em 90 segundos sem ler. Responda: What would you do differently next time? Relacione sua resposta ao acontecimento narrado."
    }),
    listeningLesson({ id: "b2-narratives-02", title: "Uma entrevista que vai além do sim", listening: conversation({ id: "b2-local-interview", title: "Uma entrevista que vai além do sim", level: "B2", context,
      scene: "Pinky interviews Sparky for a local newsletter about a repair café he helped organise. Curious follow-up questions, no promotional exaggeration.",
      turns: [
        ["pinky", "For our neighbourhood newsletter, I'd like to ask about the repair café. People have seen the posters, but they may not know what happens inside. Could you walk me through what a first-time visitor would actually do?", "Para o jornal do bairro, quero perguntar sobre o café de consertos. As pessoas viram cartazes, mas talvez não saibam o que acontece. Pode explicar como seria a visita de alguém que vai pela primeira vez?"],
        ["sparky", "They tell a volunteer what they've brought and what seems to be wrong. We check whether someone has the right experience to help. If we do, the visitor stays and works alongside that person. It's a shared learning session, not a drop-off repair service.", "A pessoa conta o que trouxe e qual parece ser o problema. Verificamos se alguém tem experiência para ajudar. Se houver, ela fica e trabalha junto. É aprendizado compartilhado, não um serviço para deixar o objeto e buscar depois."],
        ["pinky", "You said the visitor stays involved. Could you give an example of something a person might learn, even if the item can't be fixed that afternoon? I'd like readers to understand that distinction.", "Você disse que o visitante participa. Pode dar um exemplo do que se aprende mesmo quando o objeto não é consertado naquela tarde? Quero que os leitores entendam essa diferença."],
        ["sparky", "Last month, someone brought a lamp with a damaged switch. We didn't have the replacement, but she learned which part to ask a professional for and how to describe the fault. I wouldn't say we repaired her lamp. We helped her understand her next step.", "Mês passado, alguém trouxe uma luminária com interruptor danificado. Não tínhamos a peça, mas ela aprendeu o que pedir a um profissional e como descrever o defeito. Não diria que consertamos: ajudamos a entender o próximo passo."],
        ["pinky", "That's useful. Is there anything you wish the posters made clearer? I don't want the article to encourage people to bring an item that the volunteers aren't equipped to handle safely.", "Isso ajuda. O que gostaria que os cartazes explicassem melhor? Não quero que a matéria leve pessoas a trazer itens que os voluntários não possam manusear com segurança."],
        ["sparky", "Please include the list of accepted items and our booking link. Visitors should describe the problem beforehand. And let me check the practical details before you publish, especially the opening hours. My memory of last month's schedule isn't reliable enough for that.", "Inclua a lista de itens aceitos e o link de reserva. As pessoas devem descrever o problema antes. Deixe-me conferir os dados práticos, especialmente horários: minha lembrança do mês passado não é confiável para publicar isso."]
      ], gist: ["What is Pinky trying to clarify for readers?", "What the café offers and what visitors should expect", "Why every broken item will be repaired free of charge", "Why visitors must leave their items unattended", "As perguntas esclarecem funcionamento, aprendizado e limites do serviço."],
      detail: ["What did the visitor with the lamp gain?", "Information about the needed part and the next step", "A fully repaired lamp that same afternoon", "A promise that no professional help was needed", "Sparky diferencia orientação útil de conserto concluído."],
      inference: ["What does Sparky's request to check opening hours suggest?", "He values accurate practical information over an unverified recollection", "He wants to withdraw everything he said", "He thinks the newsletter should omit practical information", "A memória do mês anterior pode estar desatualizada; a conferência protege a utilidade da matéria."],
      mediation: "Escreva em português uma nota de 80–110 palavras para quem pensa em visitar o café. Explique participação, limite do serviço e informação que precisa ser conferida antes da publicação."
    }), rule: "Uma pergunta aberta convida a explicar um processo; uma pergunta de acompanhamento retoma algo específico que o entrevistado disse. Could you give an example… produz evidência concreta. Na pergunta indireta, mantenha a ordem afirmativa: Could you explain what a visitor does? Evite acrescentar inversão de pergunta direta dentro dela.",
      example: "Could you explain what a first-time visitor does?", translation: "Você poderia explicar o que faz um visitante de primeira viagem?",
      vocabulary: "walk someone through — explicar passo a passo\ndrop-off service — serviço em que se deixa o objeto\nfault — defeito",
      pitfall: "Could you explain what does a visitor do? mistura ordens. Depois de explain, use what a visitor does.",
      gap: "Could you explain what a visitor ___ on arrival?", fills: ["does", "do", "does do what"], gapExplanation: "A oração indireta usa sujeito antes do verbo: what a visitor does. Visitor é singular.",
      production: "Prepare uma entrevista de 180–220 palavras com quatro perguntas abertas e duas perguntas de acompanhamento para um projeto local. Acrescente uma introdução que explique objetivo e público, sem inventar respostas do entrevistado.",
      speakingTask: "Faça a primeira pergunta e imagine uma resposta curta. Formule oralmente duas perguntas de acompanhamento que dependam dessa resposta, sem trocar de assunto abruptamente."
    }),
    listeningLesson({ id: "b2-narratives-03", title: "Notícia local, certeza proporcional", listening: conversation({ id: "b2-local-news", title: "Notícia local, certeza proporcional", level: "B2", context,
      scene: "Two volunteer editors discussing a short local transport news report before publication. Careful, matter-of-fact conversational tone.",
      turns: [
        ["sparky", "I've drafted a headline for the neighbourhood page: New bus timetable cuts waiting times. The transport office says the average wait fell from eighteen minutes to twelve during the first week. It sounds like a clear improvement.", "Escrevi a manchete: Novo horário de ônibus reduz espera. O departamento informa queda de dezoito para doze minutos na primeira semana. Parece uma melhora clara."],
        ["pinky", "It may be, but what does the average include? Was it measured at every stop, or just the central station? And were those weekday figures? A headline can sound broader than the evidence behind it.", "Pode ser, mas o que entra nessa média? Mediram em todos os pontos ou só na estação central? São dados de dias úteis? A manchete pode parecer mais ampla que a evidência."],
        ["sparky", "You're right to ask. The figures come from three central stops on weekdays. The office hasn't published weekend data yet. One resident told me her evening bus was still late, although that doesn't tell us how the whole service performed.", "Os dados vêm de três pontos centrais em dias úteis. Ainda não há dados de fim de semana. Uma moradora disse que o ônibus dela atrasou à noite, embora isso não descreva o serviço inteiro."],
        ["pinky", "Then let's report both without pretending they're equivalent kinds of evidence. The official figures describe a limited sample, and the resident describes a personal experience. We can ask the office when it will release information for other routes and times.", "Vamos relatar ambos sem fingir que são evidências equivalentes. Os números oficiais tratam de uma amostra limitada; a moradora, de uma experiência pessoal. Podemos perguntar quando sairão dados de outras rotas e horários."],
        ["sparky", "How about: Shorter weekday waits reported at three central stops? It isn't as dramatic, but it tells readers what was actually measured. I'll put the first-week limitation near the top rather than burying it at the end.", "Que tal: Espera menor em dias úteis é relatada em três pontos centrais? É menos dramático, mas informa o que foi medido. Coloco a limitação da primeira semana no início, não escondida no fim."],
        ["pinky", "That works. Also make clear that the office supplied the figures. If we receive the wider data later, we can update the report. We don't need to turn a promising early result into a claim about every passenger's experience.", "Funciona. Deixe claro também quem forneceu os números. Podemos atualizar depois com dados mais amplos. Um resultado inicial promissor não precisa virar afirmação sobre a experiência de todos os passageiros."]
      ], gist: ["Why do the editors revise the headline?", "To match the claim to the scope of the available evidence", "To deny that waiting times changed anywhere", "To replace all data with one resident's experience", "A revisão delimita local, período e fonte sem negar o resultado observado."],
      detail: ["What do the published figures cover?", "Three central stops on weekdays during the first week", "Every route throughout the first month", "Weekend services in all neighbourhoods", "As três restrições aparecem explicitamente: três pontos, dias úteis e primeira semana."],
      inference: ["Why should the limitation appear near the top?", "Readers need it to interpret the main claim accurately", "Readers should ignore the transport office entirely", "It will make the report appear more dramatic", "A ressalva modifica a interpretação da conclusão principal, portanto não é um detalhe dispensável."],
      mediation: "Redija em português um boletim de 80–110 palavras para moradores, distinguindo números oficiais, relato individual e dados ainda ausentes."
    }), rule: "Ao relatar uma notícia, atribua a fonte e delimite o alcance. Is reported / was measured destaca o resultado ou processo sem omitir de onde vem a informação. Uma média de alguns locais não descreve necessariamente cada pessoa ou todo o sistema. Preserve no resumo as condições que mudam a interpretação da manchete.",
      example: "Shorter waits were reported at three central stops.", translation: "Foram relatadas esperas menores em três pontos centrais.",
      vocabulary: "headline — manchete\nsample — amostra\nbury a limitation — esconder uma limitação em parte pouco visível",
      pitfall: "Uma experiência individual não refuta automaticamente a média; a média também não invalida a experiência. São escalas diferentes de observação.",
      gap: "The figures ___ by the transport office last week.", fills: ["were supplied", "was supplied", "supplied were"], gapExplanation: "Figures é plural; a passiva no passado usa were supplied.",
      production: "Escreva uma notícia autoral de 180–220 palavras usando apenas os fatos do diálogo. Inclua manchete delimitada, fonte, dado principal, relato individual contextualizado e uma pergunta que ainda precisa de resposta.",
      speakingTask: "Resuma a notícia em um minuto. Responda: So are all buses faster now? Corrija a generalização usando linguagem clara, sem recitar o texto."
    }),
    listeningLesson({ id: "b2-narratives-04", title: "O fio de um podcast", listening: conversation({ id: "b2-everyday-podcast", title: "O fio de um podcast", level: "B2", context,
      scene: "A short, thoughtful two-host podcast about notifications and routines. Warm natural voices, no theme music or effects.",
      turns: [
        ["pinky", "Today we're talking about a small experiment with phone notifications. I turned off the non-essential ones for a week because I kept checking my phone while studying. I expected to feel cut off from everyone, but that wasn't really what happened.", "Hoje falamos de um pequeno experimento com notificações. Desativei as não essenciais por uma semana porque olhava o celular durante o estudo. Esperava sentir-me desconectada das pessoas, mas não foi bem isso que aconteceu."],
        ["sparky", "What did you keep switched on? Some listeners may need messages for work or family arrangements, so turning everything off isn't necessarily a realistic option. I'm curious about how you decided which alerts counted as essential.", "O que você manteve ligado? Alguns ouvintes precisam de mensagens para trabalho ou família, então desligar tudo não é necessariamente realista. Como decidiu quais alertas eram essenciais?"],
        ["pinky", "I kept calls from family and direct messages from my project group. I silenced shopping apps and general social updates. For the first two days, I still reached for the phone out of habit. The quieter screen didn't immediately change the behaviour.", "Mantive ligações da família e mensagens diretas do grupo do projeto. Silenciei lojas e atualizações gerais de redes sociais. Nos dois primeiros dias, ainda pegava o celular por hábito. A tela mais quieta não mudou o comportamento imediatamente."],
        ["sparky", "That's an important distinction. Removing a prompt and changing a habit aren't quite the same thing. Did anything help you stop checking, or was it simply a matter of waiting until the urge became weaker?", "É uma distinção importante. Remover um estímulo e mudar um hábito não são exatamente a mesma coisa. Algo ajudou ou bastou esperar que a vontade diminuísse?"],
        ["pinky", "Leaving the phone on a shelf helped more than I'd expected. I also told my group when I'd check messages, so they knew how to reach me urgently. By the weekend I was checking less, though I can't separate the effect of those changes.", "Deixar o celular numa prateleira ajudou mais do que eu esperava. Avisei quando leria mensagens, para o grupo saber como contatar-me em urgências. No fim da semana eu olhava menos, mas não consigo separar o efeito das mudanças."],
        ["sparky", "So this is a useful personal experiment, not proof of one universal solution. Listeners could try a small change that suits their responsibilities, notice what happens, and adjust it. The aim is a workable routine, not winning a competition to use a phone least.", "É um experimento pessoal útil, não prova de uma solução universal. Os ouvintes podem testar uma pequena mudança compatível com suas responsabilidades e ajustá-la. O objetivo é uma rotina viável, não uma competição para usar menos o celular."]
      ], gist: ["What is the podcast's main message?", "Test realistic changes and observe their effects without universal claims", "Turn off all contact regardless of responsibilities", "One notification setting will solve every study problem", "O episódio termina com experimentação ajustada ao contexto, não uma regra universal."],
      detail: ["Which notifications did Pinky keep?", "Family calls and direct messages from her project group", "Shopping alerts and all social updates", "Only messages arriving at the weekend", "Esses contatos foram preservados por terem função prática específica."],
      inference: ["Why does Pinky say she cannot separate the effects?", "She changed several parts of her routine together", "She never observed her phone use", "Her project group refused to contact her", "Notificações, localização do aparelho e horários de consulta mudaram juntos; não há isolamento de uma única causa."],
      mediation: "Faça uma recomendação em português de 70–100 palavras a um estudante que precisa estar disponível para a família. Adapte a ideia central sem recomendar desconexão total."
    }), rule: "Podcasts costumam alternar exemplo pessoal, pergunta e generalização cautelosa. Procure marcadores como that's an important distinction e so para acompanhar o argumento. By the weekend situa o resultado acumulado; out of habit explica uma motivação automática. Ao resumir, mantenha a diferença entre observação pessoal e conclusão universal.",
      example: "I still reached for the phone out of habit.", translation: "Eu ainda pegava o celular por hábito.",
      vocabulary: "notification — notificação\nurge — impulso forte\nworkable routine — rotina viável",
      pitfall: "Um relato de melhora após várias mudanças não prova qual delas causou o resultado. Evite transformar helped em solved everyone's problem.",
      gap: "I kept checking my phone ___ habit.", fills: ["out of", "instead", "in spite"], gapExplanation: "Out of habit é a expressão para uma ação feita por hábito. As outras opções exigem estruturas e sentidos diferentes.",
      production: "Escreva um roteiro de podcast de 180–220 palavras com dois locutores: apresente um experimento pessoal, faça uma pergunta que revele uma limitação e termine com uma recomendação ajustável.",
      speakingTask: "Grave mentalmente uma abertura de um minuto para seu episódio. Depois responda: Would this advice work for someone on call? Ajuste a recomendação às responsabilidades dessa pessoa."
    }),
    listeningLesson({ id: "b2-narratives-05", title: "Duas versões, um acontecimento", listening: conversation({ id: "b2-compare-versions", title: "Duas versões, um acontecimento", level: "B2", context,
      scene: "Two friends compare reports of a delayed neighbourhood meeting. Calm analytical conversation, no accusation or dramatic performance.",
      turns: [
        ["sparky", "I've read two accounts of last night's meeting, and they make it sound like two different events. The organiser says it started late because the projector failed. A resident says people were left outside and nobody explained the delay.", "Li duas versões da reunião de ontem, e parecem eventos diferentes. A organizadora diz que começou tarde por falha do projetor. Um morador diz que deixaram pessoas do lado de fora sem explicar o atraso."],
        ["pinky", "Those statements might both be true. A technical problem could explain the late start without explaining why communication at the entrance was poor. Do the accounts disagree about a specific fact, or do they focus on different parts of the experience?", "As duas afirmações podem ser verdadeiras. O problema técnico explica o início tardio, mas não a comunicação ruim na entrada. Elas discordam de algum fato específico ou destacam partes diferentes da experiência?"],
        ["sparky", "They agree that the doors opened at seven twenty, twenty minutes after the advertised time. The organiser says an announcement was made inside the building. The resident says the people waiting outdoors couldn't hear any announcement.", "Ambas dizem que as portas abriram às sete e vinte, vinte minutos depois do anunciado. A organizadora diz que houve um aviso dentro do prédio. O morador diz que as pessoas lá fora não o ouviram."],
        ["pinky", "Then the location of the announcement matters. Saying there was no explanation anywhere would go beyond the resident's evidence. Saying everyone was informed would go beyond the organiser's. We should make that difference visible in the summary.", "Então importa onde houve o aviso. Dizer que não existiu explicação alguma vai além da evidência do morador. Dizer que todos foram informados vai além da da organizadora. O resumo deve mostrar essa diferença."],
        ["sparky", "I'll ask whether a volunteer was assigned to the entrance and whether anyone updated the event page. I don't need to decide that one person is lying before identifying what information is missing. The delay and the communication problem can be reported separately.", "Vou perguntar se havia voluntário na entrada e atualização na página do evento. Não preciso decidir que alguém mente para identificar a informação ausente. Atraso e problema de comunicação podem ser relatados separadamente."],
        ["pinky", "Exactly. Start with what both accounts agree on, attribute the different observations, and list the unanswered questions. That gives readers a fair picture without creating a false choice between defending the organiser and believing the resident.", "Exatamente. Comece pelo consenso, atribua as observações diferentes e liste perguntas sem resposta. Isso oferece um quadro justo sem criar uma escolha falsa entre defender a organização e acreditar no morador."]
      ], gist: ["How should the accounts be compared?", "Separate shared facts, different perspectives and missing information", "Assume that different perspectives prove someone is lying", "Choose the more dramatic account and ignore the other", "As versões podem coexistir; o trabalho é delimitar o que cada pessoa observou."],
      detail: ["What time do both accounts give for the doors opening?", "Seven twenty", "Seven o'clock", "Twenty minutes before seven", "Ambas concordam em 7:20, vinte minutos após o horário anunciado."],
      inference: ["Why is the announcement's location crucial?", "An indoor announcement may not have reached people outdoors", "The projector could only be repaired outdoors", "The advertised time depended on where people stood", "Ter sido emitido não garante ter alcançado todos os destinatários."],
      mediation: "Escreva 90–120 palavras em português para alguém ausente da reunião. Inclua consenso, perspectivas atribuídas e duas perguntas abertas sem acusar ninguém de mentir."
    }), rule: "Versões diferentes podem ser complementares. Use both accounts agree that para o consenso e according to para atribuição. Might both be true preserva uma possibilidade; não afirma que tudo foi comprovado. Compare acesso à informação, horário e localização antes de concluir que existe contradição factual.",
      example: "Both accounts agree that the doors opened late.", translation: "As duas versões concordam que as portas abriram tarde.",
      vocabulary: "account — relato de um acontecimento\nattribute — atribuir a uma fonte\nunanswered question — pergunta ainda sem resposta",
      pitfall: "No announcement was heard outside é diferente de no announcement was made. Trocar a percepção pela inexistência do fato produz uma conclusão sem apoio.",
      gap: "___ the resident, the announcement could not be heard outside.", fills: ["According to", "According with", "Because to"], gapExplanation: "According to é a combinação usada para atribuir uma informação a uma fonte.",
      production: "Escreva 180–220 palavras comparando as duas versões. Abra com os fatos compartilhados, atribua cada observação, identifique uma aparente contradição resolvível e formule duas perguntas de apuração.",
      speakingTask: "Explique as versões em 90 segundos. Responda: Which person should we believe? Mostre por que a pergunta cria uma oposição desnecessária neste caso."
    }),
    listeningLesson({ id: "b2-narratives-06", title: "Projeto: editar sem distorcer", listening: conversation({ id: "b2-editorial-project", title: "Projeto: editar sem distorcer", level: "B2", context,
      scene: "Two local newsletter editors choosing an angle for an article about a library pilot. Professional but accessible conversation.",
      turns: [
        ["pinky", "We have room for one article about the library's evening opening trial. We've collected attendance figures, spoken to a librarian and interviewed two students. The challenge is choosing an angle without pretending that those two students represent every library user.", "Temos espaço para uma matéria sobre o teste de abertura noturna da biblioteca. Há dados de público, entrevista com bibliotecária e dois estudantes. Precisamos escolher um enfoque sem tratá-los como representantes de todos os usuários."],
        ["sparky", "The attendance rose during the final two weeks, but those were also the weeks before college exams. The librarian said some people came for quiet study and others came to use the computers. The student quotes only describe the study space.", "O público cresceu nas duas semanas finais, que antecederam provas da faculdade. A bibliotecária citou estudo silencioso e uso de computadores. As falas dos estudantes tratam apenas do espaço para estudar."],
        ["pinky", "Then our headline should ask what the trial has shown rather than announce that longer hours have solved an access problem. We can explain the encouraging figures and the exam timing together, followed by the experiences people actually described.", "Nossa manchete deve explorar o que o teste mostrou, não anunciar que horários maiores resolveram o acesso. Podemos explicar os números promissores junto com o período de provas e depois trazer as experiências descritas."],
        ["sparky", "I'd like to include what happens next. The library hasn't received funding for permanent evening hours. According to the librarian, the council will consider a proposal next month. We should avoid wording that makes the trial sound like a permanent service.", "Quero incluir os próximos passos. Ainda não há financiamento para abertura noturna permanente. Segundo a bibliotecária, o conselho analisa a proposta no mês que vem. Não devemos fazer o teste parecer um serviço permanente."],
        ["pinky", "Agreed. I'll draft the opening and organise the quotes. Could you check the dates, the figures and the wording of the proposal? We should also ask a computer user for their perspective before the article closes, if there's time.", "Combinado. Escrevo a abertura e organizo as falas. Você confere datas, números e a proposta? Se houver tempo, também devemos ouvir alguém que usa os computadores antes de fechar a matéria."],
        ["sparky", "Yes. If we can't obtain that interview, we'll state the gap instead of inventing a representative view. Before publishing, let's each read the article once as someone who knows nothing about the trial and mark anything that could create a false expectation.", "Sim. Se não conseguirmos a entrevista, indicaremos a lacuna em vez de inventar uma visão representativa. Antes de publicar, vamos ler como alguém que desconhece o teste e marcar o que pode gerar uma expectativa falsa."]
      ], gist: ["What is the editors' main goal?", "Publish an informative account that preserves limits and next steps", "Prove that all users want permanent evening hours", "Replace missing interviews with imagined quotations", "O projeto editorial combina utilidade, apuração e transparência sobre limites."],
      detail: ["When will the council consider the proposal?", "Next month", "During the final two weeks of the trial", "Only after permanent funding has been awarded", "A decisão está prevista para o mês seguinte; o financiamento ainda não está garantido."],
      inference: ["Why read the draft as someone unfamiliar with the trial?", "To spot wording that may mislead a new reader", "To remove every concrete detail from the report", "To decide that checking dates is unnecessary", "A leitura com outra perspectiva testa o efeito do texto, incluindo expectativas indevidas."],
      mediation: "Faça em português uma nota editorial de 90–120 palavras para o conselho do jornal, explicando o enfoque, a lacuna de fontes e os detalhes que precisam de conferência."
    }), rule: "Um projeto editorial articula informação confirmada, perspectiva atribuída e lacuna declarada. Reported speech permite transmitir uma fala sem transformá-la em garantia do narrador. Hasn't received indica ausência de financiamento até agora; will consider indica análise futura, não aprovação. Revise o efeito de sua redação sobre alguém que não conhece o contexto.",
      example: "The council will consider the proposal next month.", translation: "O conselho analisará a proposta no mês que vem.",
      vocabulary: "angle — enfoque editorial\nfunding — financiamento\nfalse expectation — expectativa indevida",
      pitfall: "Will consider a proposal não significa will approve it. Uma análise agendada não prova resultado favorável.",
      gap: "The library ___ funding for permanent evening hours yet.", fills: ["hasn't received", "didn't received", "hasn't receive"], gapExplanation: "Com yet e uma situação válida até agora, hasn't received usa present perfect: have/has + particípio.",
      production: "Projeto final: escreva uma matéria de 220–260 palavras sobre o teste da biblioteca, com manchete, abertura, dados contextualizados, perspectivas atribuídas, limitação e próximos passos. Use apenas informações do diálogo; não invente citações.",
      productionChecklist: ["A manchete corresponde aos dados?", "Distingui teste temporário de serviço permanente?", "Atribuí opiniões às fontes?", "Indiquei a perspectiva que falta?"],
      speakingTask: "Apresente sua pauta em dois minutos. Responda ao editor que pede uma manchete mais categórica. Explique a limitação sem perder clareza ou interesse."
    })
  ]
}];
