import type { ModuleDraft } from "./types";
import type { ListeningConversation } from "../listening-types";
import service from "./listening/b2-service-repair.json" with { type: "json" };
import { conversation, listeningLesson, b2ListeningDirection as context } from "./listening-authoring.ts";

export const b2PressureModules: ModuleDraft[] = [{
  id: "b2-pressure", title: "Vida prática sob pressão", level: "B2", prerequisiteId: "b2-autonomia",
  description: "Resolver problemas reais, esclarecer condições e negociar próximos passos em conversas completas.",
  lessons: [
    listeningLesson({ id: "b2-pressure-01", title: "Um conserto que não resolveu", listening: service as ListeningConversation,
      rule: "Uma reclamação produtiva combina histórico verificável, impacto concreto e pedido viável. I'd rather + verbo base expressa preferência sem impor uma única solução. By four marca um prazo; until four marca continuidade. Ouça a diferença entre concluir uma inspeção e prometer um conserto: uma condição pode limitar o compromisso.",
      example: "I'd rather have the actual problem fixed.", translation: "Eu preferiria que o problema de fato fosse resolvido.",
      vocabulary: "hold up — continuar funcionando bem\nhousing — capa protetora de um cabo\nloan bike — bicicleta disponibilizada para empréstimo",
      pitfall: "I can finish the check by four não promete terminar o conserto até as quatro. Traduzir check como repair elimina a condição decisiva da conversa.",
      gap: "Please call me ___ four with the inspection findings.", fills: ["by", "until", "during"], gapExplanation: "By four indica até as quatro como prazo para a ligação. Until indicaria uma ação que continua até esse horário.",
      production: "Escreva 180–220 palavras ao estabelecimento: descreva o histórico do problema, explique seu impacto, proponha uma solução e estabeleça quando deseja aprovar custos adicionais.",
      productionChecklist: ["Descrevi fatos sem exagerar?", "Fiz um pedido executável?", "Separei prazo confirmado de condição?"],
      speakingTask: "Explique outro problema de serviço em 90 segundos. Responda depois à objeção: We may need to order a replacement part. Faça uma pergunta de esclarecimento e negocie uma alternativa."
    }),
    listeningLesson({ id: "b2-pressure-02", title: "Quando a viagem muda", listening: conversation({ id: "b2-travel-change", level: "B2", title: "Quando a viagem muda", scene: "Two friends at a station information desk after a cancelled train. They weigh two realistic alternatives without panic.", context,
      turns: [
        ["sparky", "Our train to the coast has been cancelled. The board says there's a replacement bus, but it doesn't say where it leaves from. The guesthouse stops checking people in at eight, so we need more than a rough arrival time.", "Nosso trem para o litoral foi cancelado. O painel informa que há um ônibus substituto, mas não de onde ele sai. A pousada encerra o check-in às oito, então precisamos de mais que uma previsão vaga."],
        ["pinky", "I spoke to the station assistant. The bus leaves outside the south entrance at five fifteen. It should reach the coast around seven thirty, depending on traffic. Our tickets are valid, and we don't need to reserve seats again.", "Falei com o atendente. O ônibus sai da entrada sul às cinco e quinze. Deve chegar ao litoral por volta das sete e meia, dependendo do trânsito. Nossos bilhetes valem e não precisamos reservar de novo."],
        ["sparky", "That sounds possible, though it doesn't leave much room for delays. Is there a later train on another route? I'd prefer not to spend the whole journey worrying about being locked out of the guesthouse.", "Parece possível, mas deixa pouca margem para atrasos. Há outro trem por outra rota? Preferia não passar a viagem preocupado com a pousada fechada."],
        ["pinky", "There is, but it involves two changes and arrives after nine. Taking a taxi from here would cost more than our room. Why don't we call the guesthouse before deciding? They may have a way to arrange a late arrival.", "Há, mas exige duas trocas e chega depois das nove. Um táxi daqui custaria mais que o quarto. Vamos ligar à pousada antes de decidir? Talvez possam organizar uma chegada tardia."],
        ["sparky", "Good idea. I'll explain the cancellation and ask whether they can leave a key somewhere secure. If they confirm that, the bus seems sensible. We should still find the south entrance now rather than at the last minute.", "Boa ideia. Vou explicar o cancelamento e perguntar se podem deixar uma chave em lugar seguro. Se confirmarem, o ônibus faz sentido. Vamos localizar a entrada sul agora, sem deixar para a última hora."],
        ["pinky", "I'll check the walking route while you call. Let's keep the booking number ready and ask them to send any late check-in instructions in writing. Then we'll both know exactly what has been agreed.", "Vou conferir o caminho enquanto você liga. Vamos deixar o número da reserva pronto e pedir instruções por escrito para o check-in tardio. Assim saberemos exatamente o que foi combinado."]
      ],
      gist: ["What are the friends trying to achieve?", "Choose a workable route and protect their check-in", "Claim that every route is equally convenient", "Cancel the guesthouse immediately", "Eles comparam transporte e a condição de entrada na pousada antes de decidir."],
      detail: ["What is confirmed about the replacement bus?", "Their existing tickets are valid", "It will arrive before seven whatever the traffic", "They must reserve new seats", "Pinky confirma a validade dos bilhetes; a chegada depende do trânsito."],
      inference: ["Why do they want written check-in instructions?", "To reduce uncertainty about the agreement", "To prove that a taxi is inexpensive", "To avoid speaking to the guesthouse", "O registro permite que ambos consultem as condições combinadas; não substitui o contato inicial."],
      mediation: "Envie ao amigo que viajará com vocês uma mensagem em português de 70–100 palavras: local e horário do ônibus, validade do bilhete e condição ainda não confirmada sobre o check-in."
    }), rule: "Negociar uma mudança de viagem exige distinguir fatos confirmados, estimativas e condições. Should reach expressa expectativa, não garantia; depending on limita a previsão. If they confirm that conecta a escolha a uma informação pendente. Antes de propor outra rota, esclareça qual restrição realmente ameaça o objetivo da viagem.",
      example: "If they confirm that, the bus seems sensible.", translation: "Se eles confirmarem isso, o ônibus parece uma opção sensata.",
      vocabulary: "replacement bus — ônibus substituto\nroom for delays — margem para atrasos\ncheck-in instructions — instruções de entrada",
      pitfall: "Should arrive não significa will definitely arrive. Retirar depending on traffic muda o grau de certeza da informação.",
      gap: "We should arrive at seven thirty, ___ traffic.", fills: ["depending on", "despite of", "according with"], gapExplanation: "Depending on introduz a condição variável que afeta a estimativa. Despite of e according with não são as combinações naturais pretendidas.",
      production: "Escreva 180–220 palavras para uma hospedagem explicando uma interrupção de viagem. Peça uma alternativa de entrada, confirme o que você já sabe e faça duas perguntas objetivas sobre o que ainda falta combinar.",
      speakingTask: "Compare duas rotas em 90 segundos. Depois responda: We cannot leave a key outside. Proponha outra solução sem tratar estimativas como garantias."
    }),
    listeningLesson({ id: "b2-pressure-03", title: "Dividir a casa sem acumular tensão", listening: conversation({ id: "b2-shared-home", level: "B2", title: "Dividir a casa sem acumular tensão", scene: "Two flatmates talking at their kitchen table on a quiet afternoon. They negotiate cleaning expectations without blame.", context,
      turns: [
        ["sparky", "Can we talk about the kitchen for a minute? Twice this week I've come home to dishes covering the counter. I know we're both busy, but I couldn't make dinner without clearing someone else's things first.", "Podemos conversar um minuto sobre a cozinha? Duas vezes nesta semana cheguei e encontrei a bancada coberta de louça. Sei que estamos ocupados, mas não consegui fazer o jantar sem tirar as coisas de outra pessoa."],
        ["pinky", "You're right about Tuesday. I left in a hurry and meant to wash up when I got back. On Thursday, though, the dishes were from the meal we cooked together. I thought we were still taking turns after shared meals.", "Sobre terça, você tem razão. Saí com pressa e pretendia lavar quando voltasse. Mas na quinta a louça era da refeição que fizemos juntos. Achei que ainda estivéssemos alternando a limpeza dessas refeições."],
        ["sparky", "We were, but we never agreed whose turn it was that night. I can see why you understood it differently. Maybe the problem is that we've been relying on guesses instead of making the arrangement clear.", "Estávamos, mas não combinamos de quem era a vez naquela noite. Entendo por que você interpretou diferente. Talvez o problema seja depender de suposições em vez de deixar o acordo claro."],
        ["pinky", "What if we each deal with our own dishes before bedtime, and decide who washes up before we start a shared meal? I'd also like us to keep one side of the counter clear, even when something is soaking.", "E se cada um cuidasse da própria louça antes de dormir e decidíssemos quem lava antes das refeições compartilhadas? Também gostaria de manter um lado da bancada livre, mesmo quando algo estiver de molho."],
        ["sparky", "That would help. There'll be evenings when one of us gets home very late, so let's allow an exception if we send a message. I don't want a strict system that falls apart the first time our schedules change.", "Isso ajudaria. Haverá noites em que alguém chegará muito tarde, então vamos permitir uma exceção se avisarmos por mensagem. Não quero um sistema rígido que falhe na primeira mudança de horário."],
        ["pinky", "Agreed. Let's try it for two weeks and check how it's working. I'll write the arrangement on our shared list, including the exceptions, so neither of us has to remember an unwritten rule.", "Combinado. Vamos testar por duas semanas e avaliar. Vou registrar o acordo na lista compartilhada, incluindo as exceções, para ninguém depender de uma regra não escrita."]
      ],
      gist: ["What do the flatmates ultimately address?", "An unclear agreement and practical cleaning expectations", "A decision to stop sharing the flat", "A ban on cooking together", "Eles identificam a ambiguidade do acordo e definem um teste com responsabilidades claras."],
      detail: ["When will they decide who washes up after a shared meal?", "Before they start the meal", "Only if a disagreement happens", "At the end of the two-week trial", "A decisão anterior evita a mesma suposição conflitante do jantar de quinta."],
      inference: ["Why does Sparky suggest exceptions?", "He wants an arrangement that survives real schedule changes", "He wants to avoid every cleaning responsibility", "He thinks messages should replace all housework", "Ele aceita a responsabilidade, mas prevê situações em que a flexibilidade torna o acordo sustentável."],
      mediation: "Redija 80–100 palavras em português para um terceiro morador que não ouviu a conversa. Registre a regra, a exceção e a data de revisão, sem atribuir culpa unilateral."
    }), rule: "Ao resolver uma tensão doméstica, descreva comportamentos específicos antes de interpretar intenções. I thought we were… torna visível uma suposição passada. What if we + passado simples pode propor uma alternativa no presente; não indica necessariamente um evento passado. Reformule o problema como algo negociável e estabeleça uma revisão do acordo.",
      example: "What if we kept one side of the counter clear?", translation: "E se mantivéssemos um lado da bancada livre?",
      vocabulary: "wash up — lavar a louça\nsoak — deixar de molho\ntake turns — alternar as vezes",
      pitfall: "You always leave a mess generaliza e pode provocar defesa. Two evenings this week é verificável. Não confunda uma divergência de entendimento com falta de consideração comprovada.",
      gap: "We ___ turns after shared meals, but never chose that evening's turn.", fills: ["were taking", "was taking", "were take"], gapExplanation: "We exige were; o progressivo usa taking. A forma mostra o arranjo em andamento naquele período.",
      production: "Escreva 180–220 palavras propondo um acordo para um espaço compartilhado: apresente dois problemas observáveis, ofereça regras flexíveis, preveja uma exceção e combine uma revisão.",
      speakingTask: "Apresente o acordo em 90 segundos. Responda: That rule would be difficult on my late shifts. Reformule uma condição mantendo o objetivo comum."
    }),
    listeningLesson({ id: "b2-pressure-04", title: "Reagendar com responsabilidade", listening: conversation({ id: "b2-rescheduling", level: "B2", title: "Reagendar com responsabilidade", scene: "Two colleagues on a quiet call arranging a community workshop after an unexpected scheduling clash.", context,
      turns: [
        ["sparky", "I'm sorry to bring this up so late, but the room we booked for Thursday is needed for emergency maintenance. The centre has offered us Friday morning instead. Before I accept, I wanted to check whether you could still lead the workshop.", "Desculpe avisar tão perto, mas a sala de quinta será usada para manutenção emergencial. O centro ofereceu sexta de manhã. Antes de aceitar, quis conferir se você ainda poderia conduzir a oficina."],
        ["pinky", "Friday morning won't work for me. I've already arranged another session, and moving it would affect a different group. Could we use the smaller room on Thursday? We only have twelve people confirmed so far.", "Sexta de manhã não funciona para mim. Já marquei outra atividade e mudá-la afetaria outro grupo. Podemos usar a sala menor na quinta? Até agora temos só doze pessoas confirmadas."],
        ["sparky", "I checked that. It holds twelve, but the entrance has steps and no alternative access. One participant specifically asked for step-free access when they registered, so I don't think it's an acceptable replacement.", "Conferi isso. Cabem doze, mas a entrada tem degraus e não há acesso alternativo. Uma participante pediu expressamente acesso sem degraus na inscrição, então não considero uma substituição aceitável."],
        ["pinky", "Then let's keep that requirement. What about moving the workshop online this Thursday and offering an optional practical session next week? We would need to warn people that the first session won't include the equipment demonstration.", "Então vamos manter essa exigência. E se fizermos a oficina online nesta quinta e oferecermos uma prática opcional na próxima semana? Precisaremos avisar que a primeira sessão não terá a demonstração dos equipamentos."],
        ["sparky", "That could work, provided everyone can join online. I'll contact the participants today, explain both options and offer a refund if neither suits them. I won't describe the online session as identical to what they booked.", "Pode funcionar, desde que todos consigam participar online. Vou contatá-los hoje, explicar as duas opções e oferecer reembolso caso nenhuma sirva. Não vou dizer que a sessão online é idêntica à contratada."],
        ["pinky", "Thanks. Send me the responses by tomorrow lunchtime, and we'll confirm the final arrangement together. If anyone needs help joining the call, I can set aside fifteen minutes beforehand to walk them through it.", "Obrigada. Envie as respostas até o almoço de amanhã e confirmaremos juntos. Se alguém precisar de ajuda para entrar, posso reservar quinze minutos antes para explicar o processo."]
      ],
      gist: ["What guides their rescheduling decision?", "Preserving access while communicating the changed offer", "Keeping the original room at any cost", "Replacing the workshop without consulting participants", "Eles mantêm a acessibilidade e reconhecem que a versão online muda a oferta."],
      detail: ["Why is the smaller room rejected?", "Its entrance does not provide the required step-free access", "It cannot hold twelve people", "It is booked for Friday morning", "O problema é o acesso com degraus, não a capacidade de doze participantes."],
      inference: ["What does Sparky's refusal to call the sessions identical reveal?", "He wants participants to make an informed choice", "He believes no one values practical work", "He intends to hide the equipment change", "Ele explicita a diferença relevante e oferece escolha, em vez de disfarçar a alteração."],
      mediation: "Escreva um aviso em português de 80–110 palavras aos participantes. Separe mudança confirmada, proposta ainda em consulta e opções de reembolso/apoio."
    }), rule: "Reagendar envolve reparar o impacto, não só trocar uma data. Antes de oferecer uma alternativa, preserve as necessidades essenciais. Provided (that) introduz condição necessária, semelhante a desde que. Uma proposta condicional continua pendente: não a resuma como decisão final. Explique diferenças de formato para permitir uma escolha informada.",
      example: "That could work, provided everyone can join online.", translation: "Isso pode funcionar, desde que todos consigam participar online.",
      vocabulary: "scheduling clash — conflito de horários\nstep-free access — acesso sem degraus\nwalk someone through — explicar um processo passo a passo",
      pitfall: "We will meet online soa como decisão tomada. We could meet online, provided… preserva a condição de participação que ainda será verificada.",
      gap: "We could move online, ___ everyone can access the session.", fills: ["provided that", "even though", "so that"], gapExplanation: "Provided that estabelece a condição. Even though concede um contraste; so that indica finalidade, relações diferentes da negociação.",
      production: "Escreva 180–220 palavras reagendando uma atividade. Explique o motivo sem detalhes desnecessários, ofereça duas alternativas, preserve uma necessidade de acesso e solicite confirmação até um prazo claro.",
      speakingTask: "Explique a mudança em 90 segundos. Responda: I booked because of the practical demonstration. Reconheça o impacto e ofereça uma escolha honesta."
    }),
    listeningLesson({ id: "b2-pressure-05", title: "Um evento que caiba no bairro", listening: conversation({ id: "b2-community-event", level: "B2", title: "Um evento que caiba no bairro", scene: "Two neighbours planning a small community event at a table, comparing enthusiasm with capacity and accessibility.", context,
      turns: [
        ["sparky", "We've had thirty people offer to help with Saturday's neighbourhood event. That's great, but almost everyone signed up to run a stall. We still need people at the entrance and someone to keep the walking routes clear.", "Trinta pessoas se ofereceram para o evento de sábado. Ótimo, mas quase todas querem cuidar de uma barraca. Ainda precisamos de gente na entrada e para manter os caminhos livres."],
        ["pinky", "Perhaps the sign-up form made the stalls sound more exciting. We described those in detail, but the other roles just said general help. People may not know what they'd actually be agreeing to do or how long a shift would last.", "Talvez o formulário tenha feito as barracas parecerem mais interessantes. Descrevemos essas tarefas em detalhe, mas as outras diziam apenas ajuda geral. Talvez as pessoas não saibam o trabalho nem a duração do turno."],
        ["sparky", "You're probably right. I'll write a short description for each role and limit shifts to an hour. We should also check the layout again. The coffee queue could block the ramp if we leave the tables where they are.", "Provavelmente. Vou descrever cada função e limitar os turnos a uma hora. Também devemos rever o espaço. A fila do café pode bloquear a rampa se as mesas ficarem onde estão."],
        ["pinky", "Let's move the coffee stall beside the garden wall and leave a wide route between it and the entrance. We can mark the route before the event, but a person should keep an eye on it as the crowd changes.", "Vamos colocar o café ao lado do muro do jardim e deixar um caminho amplo até a entrada. Podemos marcar o caminho antes, mas alguém deve acompanhá-lo conforme o público se move."],
        ["sparky", "Would you coordinate those entrance shifts? I'll handle the stall changes and send the revised map. If we still don't have enough volunteers by Friday, I'd rather reduce the number of stalls than leave the entrance unmanaged.", "Você pode coordenar os turnos da entrada? Eu mudo as barracas e envio o mapa revisado. Se faltarem voluntários na sexta, prefiro reduzir as barracas a deixar a entrada sem responsável."],
        ["pinky", "Yes. I'll ask for specific one-hour slots rather than a whole-day commitment. We can explain that helping people enter comfortably is just as important to the event as serving coffee or selling cakes.", "Sim. Vou pedir horários específicos de uma hora, não o dia inteiro. Podemos explicar que ajudar as pessoas a entrar com conforto é tão importante quanto servir café ou vender bolos."]
      ],
      gist: ["What is the main planning problem?", "Volunteer numbers are high but essential roles lack coverage", "There are no volunteers for any activity", "The neighbours want to cancel all stalls", "O número total parece bom, mas não cobre as tarefas necessárias."],
      detail: ["What will happen if staffing is still insufficient by Friday?", "They will reduce the number of stalls", "They will leave the entrance unmanaged", "They will require everyone to work all day", "Sparky prefere reduzir o escopo a deixar a entrada sem coordenação."],
      inference: ["Why does Pinky suggest rewriting the role descriptions?", "Clear duties and short shifts may make people more willing to help", "She thinks all volunteers lack useful skills", "She wants to conceal the less popular tasks", "Ela considera que a descrição vaga dificulta uma decisão informada sobre o compromisso."],
      mediation: "Resuma em português, em 80–100 palavras, o pedido aos voluntários. Explique tarefas, duração e motivo da mudança sem culpar quem escolheu uma barraca."
    }), rule: "Coordenação eficaz transforma pedidos vagos em tarefas, responsáveis e prazos. Rather than compara uma opção escolhida com outra evitada. Uma condição como if we still don't have enough… permite planejar redução de escopo. Ao ouvir números, confira se eles medem capacidade total ou cobertura das funções realmente necessárias.",
      example: "I'll ask for specific slots rather than a whole-day commitment.", translation: "Vou pedir horários específicos em vez de um compromisso de dia inteiro.",
      vocabulary: "stall — barraca de evento\nshift — turno de trabalho\nkeep an eye on — acompanhar com atenção",
      pitfall: "Thirty volunteers não garante trinta funções cobertas. O listening pede atenção à distribuição, não apenas ao número mais memorável.",
      gap: "I'd rather reduce the event ___ leave the entrance unmanaged.", fills: ["than", "that", "to"], gapExplanation: "A comparação com would rather usa than: preferir uma ação a outra.",
      production: "Escreva 180–220 palavras recrutando voluntários para uma atividade comunitária. Especifique três tarefas, duração de turnos, apoio disponível, um requisito de acesso e um plano se faltarem pessoas.",
      speakingTask: "Faça um convite oral de 90 segundos. Responda à pessoa que diz: I can help, but only for an hour. Proponha uma tarefa compatível e confirme o entendimento."
    }),
    listeningLesson({ id: "b2-pressure-06", title: "Projeto: um plano que resolve", listening: conversation({ id: "b2-resolution-project", level: "B2", title: "Projeto: um plano que resolve", scene: "Two organisers reviewing a repair workshop pilot and agreeing a feasible next plan. Reflective but practical voices.", context,
      turns: [
        ["sparky", "Before we announce another repair workshop, we should look at what happened last time. People liked learning together, but six visitors left before anyone could help them. The feedback forms mention long waits more often than missing equipment.", "Antes de anunciar outra oficina de conserto, vamos revisar a última. As pessoas gostaram de aprender juntas, mas seis saíram sem atendimento. Os formulários mencionam espera longa mais que falta de equipamento."],
        ["pinky", "I noticed that too. Buying more tools sounds like an easy answer, but it wouldn't create more experienced helpers. At one point, three visitors had the same kind of problem and were waiting in separate queues without knowing it.", "Também percebi. Comprar ferramentas parece uma resposta fácil, mas não cria mais ajudantes experientes. Três visitantes tinham o mesmo tipo de problema e esperavam em filas diferentes sem saber."],
        ["sparky", "Then perhaps we could group similar requests when people arrive. A short demonstration might help several people at once, while individual appointments would be reserved for problems that really need them. We'd have to explain that system clearly.", "Talvez possamos agrupar pedidos parecidos na chegada. Uma demonstração curta ajudaria várias pessoas e reservaríamos atendimento individual para quem realmente precisa. Teremos que explicar o sistema claramente."],
        ["pinky", "I like the idea, as long as we don't promise to repair everything. We should ask visitors to describe the problem when they book, give an estimated waiting time and make it clear that some items may need a professional service.", "Gosto da ideia, desde que não prometamos consertar tudo. Vamos pedir a descrição do problema na reserva, estimar a espera e esclarecer que certos itens podem exigir serviço profissional."],
        ["sparky", "Let's test it with twenty bookings rather than forty. I'll design the arrival form and coordinate the demonstrations. Could you organise the helpers and record how many people are still waiting after the first half hour?", "Vamos testar com vinte reservas, não quarenta. Faço o formulário e coordeno as demonstrações. Você organiza os ajudantes e registra quantas pessoas ainda esperam após meia hora?"],
        ["pinky", "Yes, and let's ask visitors whether the advice was useful, even if their item wasn't repaired. Counting repairs alone would miss part of the workshop's purpose. We'll review both the waiting times and the feedback before increasing the number of bookings.", "Sim, e vamos perguntar se a orientação foi útil, mesmo sem conserto. Contar apenas consertos perderia parte do objetivo. Avaliaremos espera e feedback antes de aumentar as reservas."]
      ],
      gist: ["What is the purpose of the proposed changes?", "Test a smaller, better-organised workshop before expanding", "Guarantee a repair for every visitor", "Replace all experienced helpers with new equipment", "Eles propõem um piloto menor com agrupamento, expectativas claras e avaliação."],
      detail: ["What will Pinky record after the first half hour?", "How many people are still waiting", "How many tools were bought that morning", "How many future bookings are fully paid", "Essa medida observa diretamente o problema de espera que motivou a mudança."],
      inference: ["Why would counting repairs alone be misleading?", "Visitors may gain useful knowledge without a completed repair", "No visitor actually wants an item repaired", "Waiting times cannot be measured", "O objetivo inclui aprender e receber orientação, não apenas sair com o item consertado."],
      mediation: "Produza uma síntese em português de 90–120 palavras para os voluntários: problema observado, teste proposto, divisão de tarefas e duas medidas para avaliar o resultado."
    }), rule: "Um projeto de resolução conecta evidência, hipótese, ação e critério de avaliação. As long as estabelece uma condição para aceitar uma proposta. Even if introduz uma situação possível que não elimina a validade da ideia. Escolha indicadores ligados ao objetivo: quantidade de consertos e utilidade do aprendizado medem coisas diferentes.",
      example: "The advice may be useful even if the item isn't repaired.", translation: "A orientação pode ser útil mesmo que o item não seja consertado.",
      vocabulary: "booking — reserva\nwaiting time — tempo de espera\nexperienced helper — ajudante experiente",
      pitfall: "Even if não afirma que o item ficou sem conserto; admite essa possibilidade. Even though apresentaria um fato ou contraste considerado verdadeiro no contexto.",
      gap: "Visitors can learn something useful ___ their item cannot be repaired.", fills: ["even if", "as soon as", "in order that"], gapExplanation: "Even if preserva a possibilidade de aprendizado apesar da condição hipotética. As soon as é temporal; in order that indica finalidade.",
      production: "Projeto final: escreva 220–260 palavras propondo a próxima oficina. Use duas evidências da conversa, compare duas soluções, justifique a escolhida, distribua responsabilidades e defina como avaliar o piloto.",
      productionChecklist: ["Cada proposta responde a uma evidência?", "Expliquei o que não posso garantir?", "Escolhi duas medidas coerentes com os objetivos?", "Incluí responsável e prazo?"],
      speakingTask: "Defenda o projeto em dois minutos. Responda depois: Why limit bookings when demand is growing? Reconheça o custo da decisão e explique quando ela poderia ser revista."
    })
  ]
}];
