import type { ModuleDraft } from "./types";
import { conversation, listeningLesson } from "./listening-authoring.ts";
const context = "An extended adult conversation for C1 English learning, 130–145 words per minute. Use natural pauses at argument boundaries, subtle contrastive stress and a measured pace. Sparky is Achird, warm lower-middle pitch; Pinky is Zephyr, clear higher-middle pitch. Speak the entire script exactly. No music, audience noise, caricature or simultaneous speech.";

export const c1LongListeningModules: ModuleDraft[] = [{
  id: "c1-long-listening", title: "Escuta longa e argumentação", level: "C1", prerequisiteId: "c1-mediation",
  description: "Acompanhar exposições extensas, avaliar evidências, tomar notas seletivas e responder a argumentos sem perder suas condições.",
  lessons: [
    listeningLesson({ id: "c1-long-listening-01", title: "Acompanhar uma palestra sem anotar tudo", listening: conversation({
      id: "c1-mini-lecture", title: "Acompanhar uma palestra sem anotar tudo", level: "C1", context,
      scene: "A short community learning talk delivered by Pinky, followed by Sparky's questions. The long opening should sound like a clear live explanation, not an advertisement.",
      turns: [
        ["pinky", "When we talk about access to community courses, we often start by counting places. That's understandable: if every class is full, people are being turned away. But an available place is only the beginning of access. Imagine a course with spare seats that starts at six, while the last bus from an outlying neighbourhood arrives at six twenty. Technically, the course is open to everyone. Practically, some residents must choose between missing the opening explanation and not attending at all. My first point, then, is that capacity and usability are different questions. My second concerns the information we collect. An enrolment form tells us who joined, not who considered joining and gave up. If we design improvements using only current participants' comments, we risk making a convenient service even more convenient for the people it already reaches. That doesn't mean their feedback is unimportant. It means we should ask whose experience is missing before treating the sample as the whole community.", "Ao discutir acesso a cursos comunitários, contamos vagas. É compreensível: turmas lotadas excluem pessoas. Mas uma vaga é só o início. Imagine um curso com lugares livres às seis, enquanto o último ônibus de um bairro distante chega às seis e vinte. Tecnicamente aberto, na prática obriga alguns a perder a explicação inicial ou desistir. Primeiro ponto: capacidade e possibilidade real de uso são questões diferentes. Segundo: matrícula mostra quem entrou, não quem pensou em entrar e desistiu. Usar apenas opiniões de participantes pode melhorar o serviço sobretudo para quem já consegue acessá-lo. Isso não torna suas opiniões irrelevantes; exige perguntar quais experiências faltam antes de tomar a amostra pela comunidade inteira."],
        ["sparky", "So would your recommendation be to move every course later? That seems straightforward, although it might create a different problem for people who need to collect children or get home before another bus route stops running.", "Sua recomendação seria atrasar todos os cursos? Parece simples, mas pode criar outro problema para quem busca crianças ou precisa chegar antes de outra linha de ônibus encerrar."],
        ["pinky", "Exactly, which is why I wouldn't prescribe one universal timetable. The example identifies a barrier; it doesn't establish the best solution. We could test a second session, change one start time or provide a recorded introduction, then examine who benefits and who still cannot participate.", "Exatamente por isso não prescreveria um horário universal. O exemplo identifica uma barreira, não a melhor solução. Podemos testar outra turma, mudar um início ou gravar a introdução e verificar quem se beneficia e quem continua excluído."],
        ["sparky", "I took notes under three headings: the distinction between a seat and usable access, the missing voices in enrolment data, and possible changes to test. I left out the exact bus times because they illustrated the first point rather than serving as evidence for a citywide timetable change.", "Anotei três eixos: vaga versus acesso utilizável, vozes ausentes nos dados de matrícula e mudanças a testar. Omiti os horários exatos porque ilustravam o primeiro ponto, não provavam a necessidade de mudar o transporte da cidade inteira."],
        ["pinky", "That's a fair summary. Keep the qualification that current participants' feedback still matters. Otherwise, someone reading only your notes might think I was arguing that we should disregard the people already attending, which is almost the opposite of broadening whose experience we take seriously.", "É um resumo justo. Preserve que a opinião de participantes atuais continua importante. Sem isso, alguém pode achar que defendo ignorá-los, quase o oposto de ampliar as experiências que levamos a sério."],
        ["sparky", "I'll add that. Then my follow-up question is about method: how could the organisers hear from people who never enrolled? A brief conversation at the library or a paper survey on the relevant bus route might reach someone an email to existing students would miss.", "Vou acrescentar. Minha pergunta seguinte é metodológica: como ouvir quem nunca se matriculou? Conversas na biblioteca ou pesquisa em papel na linha de ônibus podem alcançar quem um e-mail aos alunos atuais não alcançaria."]
      ], gist: ["What is the talk's central argument?", "Course access involves practical usability and evidence from people beyond current participants", "The number of empty seats proves that every resident can participate", "Participant feedback should be replaced entirely with bus timetables", "A exposição distingue vaga de acesso real e amplia as fontes de evidência sem descartar alunos atuais."],
      detail: ["What does an enrolment form fail to show on its own?", "People who considered enrolling but gave up", "The names of those who enrolled", "Whether any places were offered at all", "O limite específico é a ausência de pessoas que desistiram antes da matrícula."],
      inference: ["Why can Sparky omit the exact bus times from his structural notes?", "They illustrate a conceptual distinction rather than establish a universal timetable recommendation", "Pinky later states that the example was factually impossible", "Numbers are never relevant when taking notes on a talk", "Seleção depende da função da informação: o exemplo sustenta uma distinção, não uma regra geral de horário."],
      mediation: "Explique em português a um organizador de cursos, em 120–150 palavras, os dois argumentos da palestra e uma forma de ouvir não participantes. Preserve a importância das opiniões atuais e diferencie exemplo ilustrativo de recomendação comprovada."
    }), rule: "Na escuta longa, anote relações: tese, distinção, exemplo, ressalva e consequência. My first point e my second organizam a exposição; that doesn't mean limita uma interpretação excessiva. Um exemplo torna um argumento compreensível, mas não prova por si só sua frequência. Ao responder, teste a conclusão sem transformar o exemplo numa recomendação que o locutor não fez.",
      example: "An available place does not necessarily amount to usable access.", translation: "Uma vaga disponível não equivale necessariamente a acesso efetivo.",
      vocabulary: "turn someone away — recusar entrada por falta de lugar\noutlying neighbourhood — bairro afastado\nprescribe — recomendar de modo normativo",
      pitfall: "That doesn't mean their feedback is unimportant impede a conclusão de que alunos atuais devem ser ignorados. Omitir a ressalva muda a tese.",
      gap: "The example identifies a barrier; it does not ___ establish the best solution.", fills: ["in itself", "by the contrary", "on behalf"], gapExplanation: "In itself significa por si só e delimita o que o exemplo pode demonstrar.",
      production: "Escreva notas estruturadas e uma resposta analítica, somando 240–280 palavras. Distinga os dois argumentos, a função do exemplo, a ressalva e uma pergunta de investigação. Proponha um teste pequeno com uma medida de acesso real.",
      speakingTask: "Apresente a palestra em dois minutos usando apenas cinco palavras-chave. Responda a Why not simply add more seats?, distinguindo capacidade e barreiras práticas sem negar que vagas também importam."
    }),
    listeningLesson({ id: "c1-long-listening-02", title: "Um painel com critérios em disputa", listening: conversation({
      id: "c1-panel-discussion", title: "Um painel com critérios em disputa", level: "C1", context,
      scene: "A two-person discussion panel for a community radio programme about extending library hours. Sparky initially prioritises attendance; Pinky questions the decision criteria. No announcer or third voice.",
      turns: [
        ["sparky", "If the library can afford only one extra evening, I would choose the day with the strongest expected attendance. We have limited staffing, and opening a large building for very few visitors seems difficult to justify. A simple count would at least make the decision transparent and allow us to review it later.", "Se a biblioteca só pode abrir uma noite extra, escolheria o dia de maior presença esperada. A equipe é limitada, e abrir um prédio grande para poucos parece difícil de justificar. Uma contagem tornaria a decisão transparente e revisável."],
        ["pinky", "Attendance is relevant, but I'd question whether it should decide everything. Suppose Friday attracts more visitors who can already come during the day, while Wednesday serves fewer people who otherwise have no opportunity to use the library. The larger number and the greater improvement in access might point in different directions.", "Presença importa, mas deveria decidir tudo? Imagine sexta atraindo mais pessoas que já podem vir de dia, enquanto quarta recebe menos que não têm outra oportunidade. Maior número e maior melhora no acesso podem apontar em direções diferentes."],
        ["sparky", "That's a fair challenge, although identifying who genuinely has no alternative could become intrusive. I wouldn't want staff interrogating people about their working hours or caring responsibilities at the door. We need an approach that respects privacy and is practical enough to run with the staff we have.", "É um questionamento justo, mas identificar quem realmente não tem alternativa pode ser invasivo. Não quero funcionários interrogando sobre trabalho ou cuidados familiares na porta. A abordagem precisa respeitar privacidade e ser viável com a equipe disponível."],
        ["pinky", "Agreed. An optional anonymous question about whether the evening made a visit possible would be less intrusive. It wouldn't give us perfect evidence, and we'd have to report the response rate. But imperfect information about access could still improve a decision that currently treats every additional visit as the same kind of benefit.", "Concordo. Uma pergunta opcional e anônima sobre a noite ter possibilitado a visita seria menos invasiva. Não seria evidência perfeita, e teríamos que informar a taxa de resposta. Ainda assim, pode melhorar uma decisão que trata toda visita extra como o mesmo benefício."],
        ["sparky", "I can support that alongside the attendance count, rather than instead of it. There's also a staffing issue: the Wednesday extension would require overtime, whereas Friday could fit a different shift pattern. If we ignore that, the apparent access benefit may come at a cost we haven't acknowledged.", "Apoio isso junto da contagem, não em substituição. Há a equipe: quarta exigiria hora extra; sexta caberia em outra escala. Ignorar isso esconderia um custo do benefício aparente de acesso."],
        ["pinky", "Then the panel needs to make its priorities explicit before seeing the final figures. We could compare total use, newly enabled visits and staffing costs, and explain how we weigh them. There may still be disagreement, but it would be disagreement about values and trade-offs rather than a contest over one convenient number.", "Então o painel precisa explicitar prioridades antes dos números finais. Podemos comparar uso total, visitas possibilitadas e custo de pessoal, explicando os pesos. Pode haver divergência, mas sobre valores e custos, não sobre um número conveniente."],
        ["sparky", "I've moved from thinking the biggest attendance should settle it to thinking it should anchor the discussion. I'd still be cautious about making a permanent commitment after one unusually busy week. Let's agree a trial period and include dates when ordinary routines, not a special event, are likely to shape demand.", "Passei de achar que a maior presença deveria decidir a achar que ela deve fundamentar a discussão. Ainda evitaria um compromisso permanente após uma semana atípica. Vamos testar num período em que rotinas comuns, não um evento especial, determinem a procura."],
        ["pinky", "That's a useful shift. We haven't settled which evening wins, and we shouldn't pretend otherwise. What we've established is a more defensible way to compare the options, with privacy, cost and access visible. The eventual recommendation should explain the rejected option fairly as well as the chosen one.", "É uma mudança útil. Não decidimos qual noite vence e não devemos fingir isso. Estabelecemos uma comparação mais defensável, com privacidade, custo e acesso visíveis. A recomendação deve explicar com justiça também a opção rejeitada."]
      ], gist: ["What agreement emerges from the panel?", "Use several explicit criteria and a representative trial before choosing an evening", "Choose Wednesday immediately because attendance is irrelevant", "Use the single busiest week as proof of permanent demand", "O acordo é sobre método e critérios; o dia continua sem escolha."],
      detail: ["How do the staffing arrangements differ?", "Wednesday would require overtime, while Friday could use a different shift pattern", "Friday requires a new building, while Wednesday uses volunteers only", "Both evenings have already been fully staffed at no extra cost", "Sparky acrescenta uma diferença de custo e escala ao debate sobre acesso."],
      inference: ["How does Sparky's position change?", "Attendance becomes an important starting point rather than the sole deciding factor", "He abandons all concern about staffing and demand", "He concludes that anonymous feedback is necessarily worthless", "Anchor the discussion contrasta com settle it: a contagem continua relevante, mas perde exclusividade."],
      mediation: "Escreva em português, em 120–150 palavras, uma síntese para o conselho da biblioteca. Registre a mudança de posição, três critérios, proteção de privacidade e decisão ainda aberta. Não anuncie uma noite vencedora."
    }), rule: "Em um painel, acompanhe mudanças de posição: I can support that alongside…, rather than instead of… marca incorporação sem abandono. Whereas compara condições; I'd still be cautious preserva uma reserva após concessão. Uma síntese de debate deve mostrar onde ocorreu convergência e qual desacordo continua, não apenas listar falas por participante.",
      example: "Attendance should inform the decision rather than determine it alone.", translation: "A presença deve informar a decisão, em vez de determiná-la sozinha.",
      vocabulary: "anchor the discussion — dar base à discussão\nresponse rate — taxa de resposta\nshift pattern — organização dos turnos",
      pitfall: "Aceitar mais critérios não significa considerar irrelevante o critério inicial. Não resuma a evolução de Sparky como uma inversão total.",
      gap: "I support the survey ___ the attendance count, not as a replacement.", fills: ["alongside", "regardless", "except that"], gapExplanation: "Alongside indica uso conjunto, preservando as duas fontes de informação.",
      production: "Escreva uma recomendação provisória de 240–280 palavras para o conselho. Compare critérios, explicite uma tensão entre eles, proponha coleta proporcional de dados e diga o que seria necessário para uma decisão permanente.",
      speakingTask: "Defenda por dois minutos uma combinação de critérios. Responda a Isn't the biggest number obviously best?, oferecendo um exemplo de benefício diferente sem ridicularizar a preocupação com uso total."
    }),
    listeningLesson({ id: "c1-long-listening-03", title: "Entrevistar sem aceitar a premissa pronta", listening: conversation({
      id: "c1-probing-interview", title: "Entrevistar sem aceitar a premissa pronta", level: "C1", context,
      scene: "Pinky interviews Sparky about a local repair programme. The interviewer politely probes a success claim and the interviewee narrows it responsibly. Natural interview pacing.",
      turns: [
        ["pinky", "Your programme's update says it has transformed the neighbourhood's relationship with waste. That's quite a substantial claim. Before we discuss future funding, could you explain what changed, how you measured it and whether the evidence covers the whole neighbourhood or the people who attended your sessions?", "O relatório diz que o programa transformou a relação do bairro com o desperdício. É uma afirmação forte. Antes do financiamento, pode explicar o que mudou, como mediram e se a evidência cobre o bairro inteiro ou os participantes?"],
        ["sparky", "The wording is broader than the evidence, and I should acknowledge that. We recorded ninety repair attempts across six sessions; sixty items left in working order. We also asked attendees whether they felt more confident assessing a broken item. Those figures tell us about activity and reported confidence, not neighbourhood-wide behaviour.", "A frase é mais ampla que a evidência, e reconheço isso. Registramos noventa tentativas de conserto em seis sessões; sessenta itens saíram funcionando. Perguntamos sobre confiança para avaliar um objeto quebrado. Isso informa atividade e confiança relatada, não o comportamento do bairro inteiro."],
        ["pinky", "Thank you for separating those. When you say sixty items left working, do you know how many were still being used a month later? I'm asking because a successful repair on the day and a lasting reduction in replacement purchases are related outcomes, but they aren't interchangeable.", "Obrigada por separar. Dos sessenta itens funcionando, sabem quantos continuavam em uso um mês depois? Um conserto no dia e uma redução duradoura de compras de substituição são resultados relacionados, mas não equivalentes."],
        ["sparky", "We don't have a reliable figure yet. A few people sent unsolicited updates, which were encouraging, but they're not a representative follow-up. We're planning an optional one-month check with everyone who agrees to be contacted. Even then, we'd need to describe non-response and avoid assuming silence means success.", "Ainda não temos um número confiável. Alguns mandaram notícias espontâneas, animadoras, mas não representativas. Planejamos contato opcional após um mês com quem autorizar. Mesmo assim, precisamos registrar não respostas e não tratar silêncio como sucesso."],
        ["pinky", "Some listeners may hear that uncertainty and conclude the project hasn't achieved anything. Would that be a fair reading? I want to challenge the promotional language without replacing it with an equally sweeping dismissal of the work the volunteers have actually done.", "Alguns ouvintes podem entender a incerteza como sinal de que o projeto nada alcançou. Seria justo? Quero questionar o tom promocional sem substituí-lo por uma rejeição igualmente ampla do trabalho feito."],
        ["sparky", "No. We can document the sessions, the repairs completed that day and what participants reported learning. We just can't yet estimate the long-term effect on purchasing or waste. A more accurate claim would be that the programme has created repair opportunities and early evidence of learning, with durability still to be assessed.", "Não. Podemos documentar sessões, consertos no dia e aprendizado relatado. Só não estimamos ainda o efeito duradouro sobre compras ou resíduos. É mais correto dizer que criamos oportunidades de conserto e evidências iniciais de aprendizado, com durabilidade a avaliar."],
        ["pinky", "Then a funding decision could distinguish what is already demonstrated from what further support would help you investigate. What would you change in the public update now, rather than waiting for the follow-up results? Readers deserve a correction while the stronger claim is still circulating.", "O financiamento pode distinguir o já demonstrado do que o apoio permitirá investigar. O que mudaria no relatório agora, sem esperar o acompanhamento? Os leitores merecem uma correção enquanto a afirmação ampla circula."],
        ["sparky", "I'd replace the headline, publish the numbers with their scope and add the follow-up question explicitly. I'd keep the original update linked with a dated correction so the change is visible. Correcting an overclaim should improve the record, not make it look as though the overclaim was never made.", "Trocaria a manchete, publicaria números com seu alcance e explicitaria o acompanhamento. Manteria o relatório original ligado a uma correção datada, tornando a mudança visível. Corrigir deve melhorar o registro, não fingir que a afirmação excessiva nunca existiu."]
      ], gist: ["What does the interview achieve?", "It narrows a success claim while preserving demonstrated achievements and remaining questions", "It proves that no item was repaired successfully", "It establishes a measured reduction in purchases across the whole neighbourhood", "O resultado é uma afirmação proporcional à evidência, sem propaganda nem rejeição total."],
      detail: ["What has been documented so far?", "Ninety repair attempts, with sixty items working when they left the sessions", "Sixty items still in daily use after a year", "Ninety households that stopped buying replacements permanently", "Os números referem-se às tentativas e ao funcionamento no dia; não ao uso posterior."],
      inference: ["Why does Sparky propose a dated correction linked to the original?", "To make the change accountable instead of concealing the earlier overclaim", "To keep the stronger claim as the only visible version", "To imply the interviewer had invented the programme's wording", "A transparência do registro inclui reconhecer a alteração e sua origem."],
      mediation: "Redija em português uma atualização de 120–150 palavras para apoiadores. Preserve números e alcance, explique o que não foi medido e apresente a correção sem transformar incerteza em fracasso comprovado."
    }), rule: "Entrevistas críticas podem questionar a premissa de uma pergunta ou manchete sem hostilidade. What does the evidence cover? delimita população e resultado. Not yet separa ausência atual de evidência de impossibilidade permanente. Ao resumir, preserve unidades e momentos: attempts, items working that day e items still in use são medidas diferentes.",
      example: "A repair completed that day is not interchangeable with lasting use.", translation: "Um conserto concluído no dia não equivale a uso duradouro.",
      vocabulary: "overclaim — afirmação além da evidência\nunsolicited update — notícia enviada espontaneamente\nnon-response — ausência de resposta à pesquisa",
      pitfall: "Sessenta consertos no dia não permitem afirmar sessenta compras evitadas. Essa mudança de indicador precisa de evidência adicional.",
      gap: "We cannot ___ estimate the long-term effect on purchasing.", fills: ["yet", "already still", "no longer yet"], gapExplanation: "Yet, em oração negativa, indica que a estimativa ainda não é possível; não declara impossibilidade definitiva.",
      production: "Escreva 240–280 palavras revisando a atualização pública do programa. Inclua uma manchete, resultados demonstrados, limitação, método de acompanhamento e correção transparente. Use apenas os números do diálogo e evite apresentar intenção de pesquisa como resultado.",
      speakingTask: "Conduza uma entrevista de dois minutos com três perguntas de acompanhamento sobre uma afirmação de sucesso. Responda depois a Are you saying the project failed?, distinguindo crítica ao alcance da alegação e avaliação do trabalho realizado."
    }),
    listeningLesson({ id: "c1-long-listening-04", title: "Um briefing de dados com denominadores", listening: conversation({
      id: "c1-data-briefing", title: "Um briefing de dados com denominadores", level: "C1", context,
      scene: "Two programme coordinators examine fictional participation figures before briefing their team. Speak all numbers clearly and give comparisons enough space to be understood.",
      turns: [
        ["sparky", "The new evening course looks like a major improvement. Last term, forty-eight learners completed it; this term, sixty did. That's twelve more completions, or a twenty-five per cent increase in the number finishing. I was going to lead tomorrow's briefing with that result.", "O novo curso noturno parece melhorar bastante. No período passado, quarenta e oito concluíram; neste, sessenta. São doze conclusões a mais, aumento de vinte e cinco por cento no número. Pensei em abrir o briefing com isso."],
        ["pinky", "The count has increased, but what happened to enrolment? A completion count and a completion rate answer different questions. If the course admitted substantially more people, we could have more finishers while a smaller proportion of those who started reached the end. We should check both before choosing the headline.", "A contagem cresceu, mas e a matrícula? Número e taxa de conclusão respondem a perguntas diferentes. Com muito mais inscritos, pode haver mais concluintes e uma proporção menor chegando ao fim. Vamos conferir ambos antes da manchete."],
        ["sparky", "There were sixty starters last term and eighty this term. So the rates are eighty per cent and seventy-five per cent respectively. That means the completion rate fell by five percentage points, even though the number of completions rose. Calling it a twenty-five per cent improvement without naming the measure would be misleading.", "Foram sessenta iniciantes antes e oitenta agora. As taxas são oitenta e setenta e cinco por cento. A taxa caiu cinco pontos percentuais, embora o número de conclusões subisse. Chamar de melhora de vinte e cinco por cento sem indicar a medida enganaria."],
        ["pinky", "Exactly. We also need to know whether the groups were comparable. The evening course attracted more first-time learners and people returning after a long break. That doesn't explain the change by itself, but it warns us against attributing everything to the timetable as though nothing else had changed.", "Exato. Também precisamos saber se os grupos são comparáveis. O noturno atraiu mais iniciantes e pessoas voltando após longa pausa. Isso não explica sozinho a mudança, mas impede atribuir tudo ao horário como se nada mais tivesse mudado."],
        ["sparky", "The feedback survey is another complication. Only thirty of the eighty starters responded, and twenty-seven of those respondents rated the course positively. We can say ninety per cent of respondents were positive, but we can't quietly turn that into ninety per cent of all starters were satisfied.", "A pesquisa complica mais. Só trinta dos oitenta responderam, e vinte e sete avaliaram positivamente. Podemos dizer noventa por cento dos respondentes, mas não transformar isso em noventa por cento de todos os inscritos satisfeitos."],
        ["pinky", "And we shouldn't assume the non-respondents were dissatisfied either. The honest statement is that their views aren't represented in that result. In the briefing, give the numerator and denominator where they affect interpretation, then explain the practical question: what support might help the additional learners stay engaged?", "Também não devemos presumir insatisfação entre quem não respondeu. Suas opiniões simplesmente não estão representadas. No briefing, informe numerador e denominador quando mudam a interpretação e a pergunta prática: que apoio ajudaria os novos alunos a continuar?"],
        ["sparky", "I'll present the counts and rates together, label the survey base and separate observation from explanation. Then we can compare attendance patterns and ask learners about barriers. I don't want the meeting to become a choice between celebrating every number and declaring the expansion a failure.", "Apresentarei contagens e taxas juntas, identificarei a base da pesquisa e separarei observação de explicação. Depois podemos comparar presença e perguntar sobre barreiras, sem escolher entre celebrar todo número e declarar fracasso da expansão."],
        ["pinky", "Good. More people finishing is a real achievement, and the lower rate is a real question to investigate. Holding both facts together gives the team a better starting point. A responsible briefing can recognise progress while still making a problem visible enough for someone to act on it.", "Ótimo. Mais concluintes é uma conquista real, e a taxa menor é uma questão real a investigar. Preservar ambos dá uma base melhor à equipe. Um briefing responsável reconhece progresso e mantém o problema visível para gerar ação."]
      ], gist: ["What is the briefing's most defensible conclusion?", "More learners completed, but the lower completion rate and limited survey need investigation", "Every measure proves that the new timetable caused better outcomes", "The increased number of completions is mathematically impossible", "Contagem e taxa podem mover-se em direções diferentes; os dados não isolam causa."],
      detail: ["How did the completion rate change?", "From 80% to 75%, a fall of five percentage points", "From 48% to 60%, a rise of twelve percentage points", "From 75% to 90%, a rise of fifteen percentage points", "48/60 = 80%; 60/80 = 75%. A diferença é de cinco pontos percentuais."],
      inference: ["Why is it wrong to assign dissatisfaction to every non-respondent?", "Their views were not measured by the returned surveys", "The course required every starter to submit a positive answer", "The survey had more responses than enrolled learners", "Não resposta não revela automaticamente opinião negativa nem positiva."],
      mediation: "Explique os resultados em português a um coordenador sem formação estatística, em 120–150 palavras. Preserve contagens, taxas e base de 30 respondentes; diferencie pontos percentuais e crescimento do número de concluintes. Não atribua causalidade ao horário."
    }), rule: "Na escuta de dados, registre medida, base, período e comparação. Percentage points expressa a diferença entre taxas: 80% para 75% = menos 5 pontos; o número de concluintes cresce 25% de 48 para 60. Of respondents limita a população. Evite trocar count por rate ao parafrasear e não transforme correlação temporal em causa demonstrada.",
      example: "The count rose, whereas the completion rate fell by five percentage points.", translation: "A contagem subiu, enquanto a taxa de conclusão caiu cinco pontos percentuais.",
      vocabulary: "denominator — denominador/base do cálculo\nrespectively — respectivamente, na ordem indicada\nsurvey base — conjunto de respostas usado no cálculo",
      pitfall: "Noventa por cento de 30 respondentes não significa noventa por cento dos 80 inscritos. Preserve a base ao resumir oralmente.",
      gap: "The rate fell from 80% to 75%, a decrease of five ___ .", fills: ["percentage points", "additional completers", "survey respondents"], gapExplanation: "A diferença absoluta entre duas porcentagens é expressa em pontos percentuais.",
      production: "Redija um briefing de 240–280 palavras com dois parágrafos de resultados, uma limitação de comparabilidade e duas perguntas investigáveis. Inclua os denominadores necessários e uma frase reconhecendo progresso sem esconder a queda da taxa.",
      speakingTask: "Explique os dados em dois minutos sem ler uma tabela. Responda a So ninety per cent of all learners were happy?, corrigindo a base da pesquisa e dizendo o que permanece desconhecido."
    }),
    listeningLesson({ id: "c1-long-listening-05", title: "Participar de uma consulta pública", listening: conversation({
      id: "c1-public-consultation", title: "Participar de uma consulta pública", level: "C1", context,
      scene: "Sparky and Pinky prepare a joint response to a fictional consultation about pedestrianising a shopping street on Saturday mornings. Respectful disagreement, concrete access concerns and conditional support.",
      turns: [
        ["pinky", "The consultation asks whether we support making Market Street pedestrian-only on Saturday mornings. My first reaction is yes: the pavements are narrow, and it would be easier to walk between the stalls without stepping around parked cars. But the response form seems to encourage a simple yes or no.", "A consulta pergunta se apoiamos uma rua de pedestres no sábado de manhã. Minha reação é sim: as calçadas são estreitas, e seria mais fácil circular sem desviar de carros. Mas o formulário incentiva um simples sim ou não."],
        ["sparky", "I support the aim, but I'd want to understand access arrangements before giving unqualified support. My neighbour uses door-to-door transport and cannot comfortably walk from the proposed drop-off point two streets away. Calling the street accessible because cars are removed would overlook that particular barrier.", "Apoio o objetivo, mas quero entender o acesso antes de apoiar sem condições. Minha vizinha usa transporte porta a porta e não consegue caminhar confortavelmente do ponto proposto a duas ruas. Dizer que retirar carros torna tudo acessível ignoraria essa barreira."],
        ["pinky", "That's an issue the proposal should address, rather than an argument we automatically have to take as opposing pedestrianisation altogether. We could distinguish the general objective from the current design. Is there a controlled access point or a closer drop-off option that preserves space for pedestrians without excluding those residents?", "A proposta deve tratar disso; não é necessariamente oposição a toda pedestrianização. Podemos separar objetivo e desenho atual. Há entrada controlada ou desembarque próximo que preserve espaço sem excluir moradores?"],
        ["sparky", "Possibly, though we'd need people who use the service to assess it. Delivery access is another question. The proposal says deliveries should happen before eight, but it doesn't show whether the smaller stallholders can arrange that. We should ask for evidence rather than assume every business has the same flexibility.", "Talvez, mas usuários precisam avaliar. Há também entregas: a proposta pede que ocorram antes das oito, sem mostrar se pequenos comerciantes conseguem. Vamos pedir evidência, não presumir flexibilidade igual entre negócios."],
        ["pinky", "Our response could support a time-limited trial subject to an access plan developed with affected users and a realistic delivery arrangement. During the trial, we'd want observations of pedestrian movement and feedback from residents and traders. More footfall alone wouldn't tell us whether the scheme worked fairly.", "Podemos apoiar um teste limitado, condicionado a um plano de acesso com usuários afetados e entregas viáveis. No teste, observaríamos circulação e ouviríamos moradores e comerciantes. Mais pedestres, sozinho, não diria se funcionou de forma justa."],
        ["sparky", "Let's also avoid presenting my neighbour as the voice of every disabled resident. Her experience identifies a concrete concern; others may have different needs or strongly support the change. We can ask for accessible consultation routes without claiming that one example gives us a mandate to represent everyone.", "Também não vamos tratar minha vizinha como porta-voz de todos os moradores com deficiência. Ela traz uma preocupação concreta; outros podem ter necessidades diferentes ou apoiar a mudança. Podemos pedir consulta acessível sem presumir representação universal."],
        ["pinky", "Agreed. I'll write that our support is conditional and list the conditions separately from suggestions that would merely improve the scheme. If a condition is essential to participation, it shouldn't disappear into a long list of optional ideas such as extra benches or decorative planting.", "Concordo. Direi que o apoio é condicionado e separarei condições de sugestões apenas desejáveis. Uma condição essencial de participação não deve sumir numa lista de ideias opcionais como bancos ou plantas decorativas."],
        ["sparky", "And we'll ask how the organisers will report changes made in response to the consultation. Inviting comments isn't the same as explaining their influence. A short account of what was adopted, what was rejected and why would help residents see whether participation affected the design.", "Perguntaremos como a organização comunicará mudanças decorrentes da consulta. Convidar comentários não é explicar sua influência. Um relato do que foi aceito, recusado e por quê ajudaria a ver se a participação alterou o desenho."]
      ], gist: ["What position do they develop?", "Conditional support for a trial with access, delivery and evaluation requirements", "Unqualified support for the design exactly as written", "A demand to reject every possible pedestrian scheme", "Eles apoiam o objetivo, mas subordinam o teste a requisitos concretos."],
      detail: ["What delivery time does the proposal currently specify?", "Before eight in the morning", "Only after the market closes on Sunday", "At any time with no restrictions", "O horário antes das oito está na proposta; a viabilidade para pequenos comerciantes não está comprovada."],
      inference: ["Why distinguish essential conditions from optional improvements?", "To prevent requirements for participation from being treated as dispensable extras", "To ensure every decorative suggestion becomes legally mandatory", "To avoid explaining why access matters", "A hierarquia deixa visível o que condiciona o apoio, em vez de misturar necessidade e preferência."],
      mediation: "Prepare em português uma contribuição de 130–160 palavras à consulta, com objetivo apoiado, duas condições essenciais e uma pergunta sobre prestação de contas. Atribua o exemplo individual sem falar por todas as pessoas com deficiência."
    }), rule: "Apoio condicionado exige explicitar sua estrutura: support the aim, subject to… separa objetivo de desenho. Uma objeção pode buscar correção, não rejeição total. Ao mediar participação pública, preserve quem falou, quem falta ouvir e quais condições determinam o apoio. Não converta uma experiência individual em mandato para representar um grupo heterogêneo.",
      example: "We support a trial, subject to an access plan developed with affected users.", translation: "Apoiamos um teste, condicionado a um plano de acesso desenvolvido com os usuários afetados.",
      vocabulary: "unqualified support — apoio sem ressalvas\nfootfall — fluxo de pedestres/visitantes\ndrop-off point — ponto de desembarque",
      pitfall: "Subject to indica condição; along with pode soar como mera adição. Trocar a expressão pode tornar opcional um requisito essencial.",
      gap: "Our support is conditional ___ a workable access arrangement.", fills: ["on", "by", "with of"], gapExplanation: "Conditional on é a combinação para subordinar o apoio a uma condição.",
      production: "Escreva uma resposta de 250–290 palavras à consulta. Declare posição, diferencie condição e sugestão, use um exemplo sem generalizar um grupo e proponha duas medidas de avaliação que vão além do número de visitantes.",
      speakingTask: "Apresente uma contribuição de dois minutos. Responda a Are you for the scheme or against it?, explicando apoio ao objetivo e condições para o desenho sem fugir da decisão prática solicitada."
    }),
    listeningLesson({ id: "c1-long-listening-06", title: "Projeto: sintetizar e responder à objeção", listening: conversation({
      id: "c1-synthesis-reply", title: "Projeto: sintetizar e responder à objeção", level: "C1", context,
      scene: "Two adult learners rehearse a recommendation after reading two fictional reports on a community study centre. Pinky challenges Sparky's synthesis, which he refines without dropping his recommendation.",
      turns: [
        ["sparky", "My recommendation is to keep the study centre open later for a three-month trial. Report A says evening users value a quiet workspace and reliable internet. Report B says late opening has increased staffing costs and that some sessions were poorly attended. Taken together, they suggest a useful service whose current schedule may need adjusting.", "Recomendo manter o centro aberto até mais tarde num teste de três meses. O relatório A registra valor de silêncio e internet para usuários noturnos; o B aponta custo maior e baixa presença em algumas sessões. Juntos, sugerem um serviço útil com horário talvez ajustável."],
        ["pinky", "That synthesis sounds plausible, but are the reports talking about the same period? If one describes exam season and the other describes the holiday weeks, presenting them as a direct contradiction would make the evidence look more inconsistent than it really is. What do we know about their scope?", "A síntese parece plausível, mas tratam do mesmo período? Se um fala de provas e outro de férias, apresentá-los como contradição direta exagera a inconsistência. O que sabemos sobre o alcance?"],
        ["sparky", "Report A interviewed twenty evening users during the final month of term. Report B summarised attendance and costs across the following six weeks, including the holiday break. So we can't make a direct numerical comparison. We can still use them to identify different questions: what users value and when demand justifies the staffing arrangement.", "O A entrevistou vinte usuários no último mês letivo. O B resumiu presença e custos nas seis semanas seguintes, incluindo férias. Não cabe comparação numérica direta. Ainda servem para perguntas diferentes: o que usuários valorizam e quando a procura justifica a equipe."],
        ["pinky", "Here's the objection you're likely to face: if the evidence isn't comparable, why recommend any extension at all? A sceptical committee member might say that you're using uncertainty to postpone an unpopular closure. You'll need to explain what the trial would resolve and what result could change your recommendation.", "A objeção provável é: se os dados não são comparáveis, por que recomendar extensão? Alguém cético pode dizer que usa incerteza para adiar um fechamento impopular. Explique o que o teste resolve e qual resultado mudaria sua recomendação."],
        ["sparky", "I'd say the existing reports establish enough potential value to justify a bounded test, not enough evidence for indefinite opening. During ordinary teaching weeks, we'd compare two late evenings using the same attendance definitions, record staffing costs and ask whether the session enabled study that wasn't otherwise possible. We'd publish the criteria before collecting the results.", "Eu diria que os relatórios mostram valor potencial para justificar um teste delimitado, não abertura indefinida. Em semanas letivas comuns, compararíamos duas noites com definições iguais de presença, custos e se a sessão possibilitou estudo que não ocorreria de outro modo. Publicaríamos critérios antes dos resultados."],
        ["pinky", "And if neither evening attracts enough use under those agreed criteria? I'm pressing this because a trial with no possible negative decision isn't really testing the recommendation. It's simply extending the service while borrowing the language of evaluation to make the extension sound provisional.", "E se nenhuma noite alcançar uso suficiente nos critérios acordados? Insisto porque um teste sem possível decisão negativa não está testando a recomendação: apenas prolonga o serviço usando linguagem de avaliação para parecer provisório."],
        ["sparky", "Then we'd reduce or end late opening and explain the evidence, while considering a smaller alternative such as access to one supervised room. I wouldn't promise that alternative before costing it. The important point is that the trial has an endpoint, a decision owner and consequences that aren't fixed in advance.", "Nesse caso, reduziríamos ou encerraríamos a abertura noturna, explicando os dados e considerando alternativa menor, como uma sala supervisionada. Não a prometeria antes de calcular custos. O teste tem término, responsável pela decisão e consequências não predeterminadas."],
        ["pinky", "That makes your recommendation much stronger. You've retained the useful part of both reports, corrected the mismatch in scope and answered the objection with a decision process rather than reassurance. In your final summary, leave room for that condition; it's central to why the trial is defensible, not a detail to cut for brevity.", "Isso fortalece a recomendação. Você preservou a utilidade dos dois relatórios, corrigiu a diferença de alcance e respondeu à objeção com um processo decisório, não só tranquilização. A condição é central à justificativa do teste, não detalhe dispensável no resumo."]
      ], gist: ["How is Sparky's recommendation strengthened?", "He clarifies the sources' scope and makes the trial capable of changing the decision", "He removes cost evidence so the extension appears risk-free", "He promises permanent opening regardless of trial results", "A defesa incorpora limitação e possibilidade real de revisão, em vez de apenas reafirmar a preferência."],
      detail: ["When were the users in Report A interviewed?", "During the final month of term", "Throughout the six holiday weeks covered by Report B", "After the proposed three-month trial had finished", "O relatório A é do último mês letivo; B cobre as seis semanas posteriores, com férias."],
      inference: ["What is Pinky questioning when she describes a trial with no possible negative decision?", "Whether the evaluation can genuinely alter the preferred policy", "Whether any positive outcome could ever justify a public service", "Whether reports must always use interviews rather than counts", "Ela testa se os dados podem mudar a decisão ou se avaliação é apenas um rótulo para prolongar a política."],
      mediation: "Escreva uma síntese em português de 130–160 palavras para um membro ausente do comitê. Preserve diferenças de período e método, recomendação delimitada e possíveis decisões após o teste. Identifique critérios numéricos e responsável como itens ainda a definir, sem inventá-los."
    }), rule: "Uma réplica forte responde à melhor versão da objeção. Reconheça a limitação, explique por que ainda há base para uma ação delimitada e diga o que mudaria sua decisão. Not enough for X, but enough to test Y calibra força da evidência. Síntese não exige comparação numérica entre fontes que respondem a perguntas e períodos diferentes.",
      example: "The evidence justifies a bounded trial, not an indefinite commitment.", translation: "A evidência justifica um teste delimitado, não um compromisso indefinido.",
      vocabulary: "bounded trial — teste com limites definidos\ndecision owner — responsável pela decisão\nfixed in advance — predeterminado",
      pitfall: "Publicar critérios antes do teste é uma proposta do diálogo; não foram definidos números mínimos. Não invente um corte e o apresente como já acordado.",
      gap: "The findings could justify a trial, ___ they cannot support permanent adoption yet.", fills: ["even though", "in spite", "because of"], gapExplanation: "Even though introduz uma concessão com oração completa, preservando diferença entre teste e adoção permanente.",
      production: "Escreva uma recomendação de 260–300 palavras sintetizando as duas fontes por questão. Inclua a objeção mais forte, uma resposta proporcional, método de teste e decisões possíveis. Termine com os dados ou definições ainda necessários, sem preencher lacunas com fatos inventados.",
      speakingTask: "Defenda a recomendação em dois minutos e responda a What evidence would make you change your mind? Ofereça uma condição concreta de revisão e explique como preservaria o registro da decisão para quem discordar."
    })
  ]
}];
