import type { ModuleDraft } from "./types";
import { conversation, listeningLesson } from "./listening-authoring.ts";

const context = "Thoughtful, natural adult conversation at 130–145 words per minute with purposeful pauses. Preserve the complete script. Sparky/Achird: warm, confident lower-middle pitch. Pinky/Zephyr: clear, curious higher-middle pitch. No caricature, music, sound effects, or overlapping words. Convey uncertainty, qualification and changes of stance through subtle stress rather than exaggerated acting.";

export const c1MediationModules: ModuleDraft[] = [{
  id: "c1-mediation", title: "Conversas delicadas e mediação", level: "C1", prerequisiteId: "c1-evidencias",
  description: "Interpretar pedidos implícitos, estabelecer limites e reconstruir posições sem apagar divergências ou presumir intenções.",
  lessons: [
    listeningLesson({ id: "c1-mediation-01", title: "O pedido que não veio em forma de pergunta", listening: conversation({
      id: "c1-implicit-request", title: "O pedido que não veio em forma de pergunta", level: "C1", context,
      scene: "At a shared flat, two friends discuss a dinner invitation and an unfinished kitchen clean-up. Slight initial awkwardness gives way to a specific, mutually agreed request.",
      turns: [
        ["pinky", "My sister's arriving at seven, and the kitchen still looks as though we've been running a restaurant. I know you've had a long day, so I wasn't sure whether to mention it. I suppose we could just eat somewhere else if the flat isn't ready.", "Minha irmã chega às sete, e a cozinha ainda parece a de um restaurante em pleno serviço. Sei que seu dia foi longo, então hesitei em comentar. Talvez possamos comer fora se o apartamento não estiver pronto."],
        ["sparky", "I can hear that you're worried about getting it ready, but I'm not quite sure what you're asking me to do. Do you need help clearing the worktop, or are you suggesting that we change the plan? I'd rather check than guess and get it wrong.", "Percebo sua preocupação em deixar tudo pronto, mas não sei exatamente o que está me pedindo. Precisa de ajuda com a bancada ou sugere mudar o plano? Prefiro confirmar a adivinhar e errar."],
        ["pinky", "Fair point. I was hoping you could wash the pans while I prepare the food. Saying we could go out was really a way of avoiding a direct request. I didn't mean that you'd already agreed to host, or that the whole kitchen was your responsibility.", "Tem razão. Esperava que você lavasse as panelas enquanto preparo a comida. Falar em sair foi uma forma de evitar um pedido direto. Não quis dizer que você já aceitara receber a visita nem que toda a cozinha fosse sua responsabilidade."],
        ["sparky", "Thanks, that helps. I can give you twenty minutes before my call, but I can't take on the rest of the evening. If washing the pans is the priority, I'll start there. I'd also like us to separate today's favour from our usual cleaning arrangement.", "Obrigado, agora entendo. Posso ajudar por vinte minutos antes da ligação, mas não assumir o resto da noite. Se a prioridade são as panelas, começo por elas. Também quero separar o favor de hoje do nosso acordo habitual de limpeza."],
        ["pinky", "Absolutely. The normal arrangement hasn't changed. I invited my sister, so organising dinner is on me. Would it make more sense for you to clear the table instead? That would fit the time you have, and I can leave the larger pans soaking until later.", "Claro. O acordo habitual não mudou. Eu convidei minha irmã, então organizar o jantar cabe a mim. Seria melhor você liberar a mesa? Isso cabe no seu tempo, e posso deixar as panelas maiores de molho."],
        ["sparky", "Yes, I can do that. One thing, though: when you said we could just eat elsewhere, I heard a hint of disappointment. That may not have been your intention. Could we say the request first next time, even if we soften it a little?", "Sim, posso. Uma coisa: quando disse que podíamos comer fora, percebi um pouco de decepção. Talvez não fosse sua intenção. Da próxima vez, podemos começar pelo pedido, mesmo formulado com delicadeza?"],
        ["pinky", "I can try. I was embarrassed about asking at short notice, rather than disappointed in you. Something like, Would you have fifteen minutes to help me set up? would have made the choice clearer. You could then say what was realistic without having to decode my mood.", "Vou tentar. Estava constrangida por pedir em cima da hora, não decepcionada com você. Algo como Você teria quinze minutos para ajudar a arrumar? deixaria a escolha clara. Assim você poderia dizer o que é viável sem decifrar meu humor."],
        ["sparky", "That would work for me. I'll clear the table now, and you handle dinner. We don't need to turn one awkward request into a verdict on how considerate either of us is. Once the immediate problem is sorted, we can enjoy seeing your sister.", "Para mim funciona. Libero a mesa agora, e você cuida do jantar. Um pedido mal formulado não precisa virar um julgamento sobre a consideração de cada um. Resolvido o problema imediato, podemos aproveitar a visita da sua irmã."]
      ],
      gist: ["What changes as the conversation develops?", "An indirect hint becomes a specific request with negotiated limits", "A shared cleaning agreement is permanently cancelled", "A dinner invitation becomes an argument about who owns the flat", "A conversa explicita o pedido, negocia tarefa e tempo e preserva o acordo habitual."],
      detail: ["What does Sparky finally agree to do?", "Clear the table before his call", "Wash every pan after dinner", "Take responsibility for hosting the whole evening", "Lavar panelas é a proposta inicial; a decisão final é liberar a mesa."],
      inference: ["Why does Pinky explain that she was embarrassed?", "To correct an interpretation of her mood without denying the unclear request", "To prove that Sparky deliberately ignored an obvious instruction", "To withdraw her sister's invitation without saying so directly", "Ela distingue a intenção de sua fala do efeito percebido por Sparky e reconhece a falta de clareza."],
      mediation: "Explique a outro morador, em português e em 100–130 palavras, o acordo final e a origem do mal-entendido. Diferencie palavras observadas, interpretação de Sparky e intenção esclarecida por Pinky; não atribua culpa ou obrigação permanente."
    }), rule: "Pedidos indiretos podem preservar a delicadeza, mas exigem inferência. I was hoping you could… costuma introduzir um pedido, não uma obrigação aceita. Para confirmar, separe observação de interpretação: I heard a hint of disappointment; that may not have been your intention. Uma resposta competente explicita tarefa, limite e alternativa sem tratar uma hipótese sobre o tom como fato psicológico.",
      example: "I was hoping you could help, but I hadn't meant to imply you'd agreed.", translation: "Eu esperava que você pudesse ajudar, mas não quis dar a entender que já havia concordado.",
      vocabulary: "at short notice — em cima da hora\non me — sob minha responsabilidade\ndecode a hint — interpretar uma indireta",
      pitfall: "I was hoping indica uma expectativa ou pedido; não demonstra consentimento anterior. Uma voz desapontada também não prova intenção de manipular.",
      gap: "I was hoping you ___ spare fifteen minutes before your call.", fills: ["could", "must to", "had to have"], gapExplanation: "Could formula um pedido mitigado de disponibilidade; as outras formas não produzem a construção proposta.",
      production: "Escreva 220–260 palavras de diálogo em que um pedido doméstico indireto é esclarecido. Inclua uma interpretação corrigida, um limite, uma alternativa aceita e uma frase que preserve o acordo habitual. Evite narrar pensamentos que os participantes não expressam.",
      speakingTask: "Responda por dois minutos a alguém que diz I suppose I'll do everything myself. Reconheça a dificuldade, confira o pedido e negocie uma contribuição. Depois responda à réplica I only needed ten minutes, sem defender uma interpretação já corrigida."
    }),
    listeningLesson({ id: "c1-mediation-02", title: "Um limite que preserva a colaboração", listening: conversation({
      id: "c1-setting-boundaries", title: "Um limite que preserva a colaboração", level: "C1", context,
      scene: "Two volunteers planning a community newsletter on a Friday afternoon. One is asked for weekend availability. Calm firmness, acknowledgement and a practical alternative.",
      turns: [
        ["sparky", "The newsletter is nearly ready, but two contributors haven't approved their quotations. Would you be able to keep an eye on the shared document over the weekend? I'm not asking for a full shift, just the odd check in case something comes through before Monday's deadline.", "O boletim está quase pronto, mas dois colaboradores não aprovaram as citações. Você poderia acompanhar o documento no fim de semana? Não peço um turno inteiro, só uma olhada de vez em quando caso algo chegue antes do prazo de segunda."],
        ["pinky", "I understand why that sounds like a small request. For me, though, being available to check means staying mentally on call, and I've committed that time to my family. I can finish the layout today, but I won't be monitoring messages on Saturday or Sunday.", "Entendo por que parece um pedido pequeno. Para mim, ficar disponível para conferir significa permanecer mentalmente de plantão, e reservei esse tempo à família. Posso terminar a diagramação hoje, mas não acompanharei mensagens sábado ou domingo."],
        ["sparky", "I hadn't thought about it that way. My concern is that if approval arrives late, the entire issue gets held up. Could we agree on one specific check on Sunday evening? I'm trying to find the smallest commitment that would protect the publication date.", "Não tinha pensado assim. Preocupa-me que a aprovação tardia atrase a edição inteira. Poderíamos combinar uma única consulta no domingo à noite? Estou procurando o menor compromisso que preserve a data de publicação."],
        ["pinky", "I appreciate you making the request more specific, but Sunday is still outside what I can offer. Could we prepare a version without those quotations? If approval arrives by four today, we use them; otherwise, we publish the shorter piece and follow up in the next issue.", "Agradeço por tornar o pedido mais específico, mas domingo continua fora da minha disponibilidade. Podemos preparar uma versão sem essas citações? Se aprovarem até as quatro de hoje, usamos; caso contrário, publicamos a versão menor e retomamos na próxima edição."],
        ["sparky", "That could work, provided we don't present an unapproved quotation as though the speaker had checked it. We would need to remove it completely, not quietly turn it into an unattributed claim. Is there enough confirmed information left for the shorter article to stand on its own?", "Pode funcionar, desde que não apresentemos uma citação não aprovada como revisada pelo entrevistado. Precisamos removê-la, não transformá-la discretamente numa afirmação sem fonte. Restam informações confirmadas suficientes para a matéria menor se sustentar?"],
        ["pinky", "Yes. The opening dates and booking arrangements are already confirmed in writing. I can build the piece around those and send both versions before I leave. Someone else will need to make the final selection, but it won't require redesigning the page or chasing me for access.", "Sim. As datas de abertura e a forma de reserva já foram confirmadas por escrito. Posso organizar a matéria com isso e enviar as duas versões antes de sair. Outra pessoa fará a escolha final, sem redesenhar a página nem depender do meu acesso."],
        ["sparky", "I'll take responsibility for that selection. Let's also tell the contributors that four o'clock is the cutoff for this issue, rather than implying that volunteers will keep waiting indefinitely. We should probably build an approval buffer into the next schedule so this doesn't become a recurring favour.", "Assumo essa escolha. Vamos informar que quatro horas é o limite desta edição, em vez de sugerir que os voluntários esperarão indefinidamente. Convém reservar uma margem para aprovação no próximo cronograma, para isso não virar um favor recorrente."],
        ["pinky", "Agreed. I'm happy to help improve the process, and I'll deliver what we've just agreed today. The boundary isn't a measure of how much I care about the newsletter. It tells us what resources we actually have, which makes the plan more dependable for everyone.", "Combinado. Quero ajudar a melhorar o processo e entregarei hoje o que acertamos. O limite não mede meu interesse pelo boletim; mostra os recursos de que realmente dispomos e torna o plano mais confiável para todos."]
      ],
      gist: ["How do they protect the publication date?", "They redesign the handover around confirmed content and available time", "Pinky agrees to remain informally available throughout the weekend", "They publish the quotations before permission arrives", "A solução muda o processo e a passagem de responsabilidade, sem ultrapassar o limite reafirmado."],
      detail: ["What is the cutoff for using the quotations in this issue?", "Four o'clock on Friday", "Sunday evening after one final check", "Monday after the newsletter has been published", "A conversa ocorre na sexta e fixa quatro horas de hoje como limite."],
      inference: ["What is the purpose of Pinky's final distinction?", "To separate commitment to the project from unlimited availability", "To imply that colleagues should never request help", "To suggest that deadlines have no value in voluntary work", "Ela rejeita usar disponibilidade irrestrita como medida de cuidado e oferece uma entrega concreta."],
      mediation: "Escreva, em português, uma passagem de trabalho de 110–140 palavras para o voluntário que publicará o boletim. Inclua prazo, versões, responsável pela escolha e tratamento das citações não aprovadas, sem expor detalhes pessoais de Pinky."
    }), rule: "Um limite colaborativo combina reconhecimento, declaração inequívoca de disponibilidade e alternativa executável. I appreciate…, but… não anula a recusa seguinte. Provided introduz condição necessária: a solução funciona desde que preserve a aprovação das citações. Ao resumir o acordo, mantenha condições e responsáveis; omiti-los transforma uma proposta limitada numa promessa aberta.",
      example: "That could work, provided the unapproved quotations are removed.", translation: "Isso pode funcionar, desde que as citações não aprovadas sejam retiradas.",
      vocabulary: "on call — de plantão/disponível para demandas\ncutoff — horário ou ponto limite\napproval buffer — margem de tempo para aprovação",
      pitfall: "Just the odd check minimiza a duração de cada consulta, mas não elimina a exigência de disponibilidade. A palavra just não determina quanto o pedido custa à outra pessoa.",
      gap: "We can publish on Monday, ___ the unapproved quotations are removed.", fills: ["provided", "despite", "unless that"], gapExplanation: "Provided introduz uma condição com oração completa; despite exige outra construção e unless inverteria a condição.",
      production: "Escreva um e-mail de 220–260 palavras recusando disponibilidade fora do combinado para um projeto voluntário. Reconheça a necessidade, mantenha o limite sem excesso de justificativas e ofereça uma alternativa com prazo, responsável e critério de decisão.",
      speakingTask: "Negocie oralmente por dois minutos uma solicitação de última hora. Após a réplica But it will only take five minutes, explique a diferença entre duração e disponibilidade e proponha um plano que a outra pessoa possa executar."
    }),
    listeningLesson({ id: "c1-mediation-03", title: "Reparar um mal-entendido sem reescrever o passado", listening: conversation({
      id: "c1-repairing-misunderstanding", title: "Reparar um mal-entendido sem reescrever o passado", level: "C1", context,
      scene: "Two colleagues reviewing an ambiguous message about a draft presentation. Initial defensiveness eases as they distinguish intention, reasonable interpretation and concrete repair.",
      turns: [
        ["pinky", "I wanted to clear up yesterday's message before we meet the rest of the team. When you wrote that the presentation needed a more professional finish, I understood you to mean the whole approach was amateurish. I spent the evening rewriting sections you apparently wanted to keep.", "Queria esclarecer sua mensagem de ontem antes da reunião. Quando escreveu que a apresentação precisava de um acabamento mais profissional, entendi que toda a abordagem era amadora. Passei a noite reescrevendo partes que, pelo visto, você queria manter."],
        ["sparky", "I'm sorry. I was referring to the inconsistent slide headings and the missing source labels, but I can see that I didn't say that. The phrase was much broader than the problem. I shouldn't expect you to reconstruct the specific feedback that stayed in my head.", "Desculpe. Referia-me aos títulos inconsistentes e às fontes ausentes, mas vejo que não expliquei isso. A frase foi muito mais ampla que o problema. Não deveria esperar que você reconstruísse um feedback específico que ficou só na minha cabeça."],
        ["pinky", "That distinction matters. I don't need you to agree that you intended to dismiss my work; I'm saying the wording gave me reasonable grounds to read it that way. If we focus only on what you meant, the extra work and uncertainty disappear from the account.", "Essa distinção importa. Não preciso que admita uma intenção de desprezar meu trabalho; digo que as palavras permitiam razoavelmente essa leitura. Se focarmos só no que pretendia, o trabalho extra e a incerteza somem do relato."],
        ["sparky", "You're right. Let me restate the feedback precisely: the argument and examples were strong; the formatting and references needed a consistent pass. I also should have marked which changes were essential before the meeting and which could wait. None of that was clear in my original message.", "Tem razão. Vou reformular: o argumento e os exemplos eram fortes; a formatação e as referências precisavam de padronização. Também deveria distinguir mudanças essenciais antes da reunião das que podiam esperar. Nada disso ficou claro na mensagem."],
        ["pinky", "I've kept the previous version, so we can recover it. Some of the new introduction may still be useful, but I don't want to keep it just to justify the time I spent. Could we compare the two against the purpose of the presentation, rather than against who wrote what?", "Guardei a versão anterior, então podemos recuperá-la. Parte da nova introdução pode ser útil, mas não quero mantê-la só para justificar meu tempo. Podemos comparar as duas com o objetivo da apresentação, em vez de com quem escreveu cada parte?"],
        ["sparky", "Yes. The audience needs to understand the proposal, its evidence and the decision we're asking for. Let's choose the opening that makes those things clearest. I'll handle the reference labels and tell the team that my vague feedback caused the unnecessary rewrite, without sharing our private conversation word for word.", "Sim. O público precisa entender a proposta, as evidências e a decisão solicitada. Escolhamos a abertura que esclarece isso. Cuido das fontes e digo à equipe que meu feedback vago causou a reescrita desnecessária, sem reproduzir nossa conversa privada inteira."],
        ["pinky", "I'd appreciate that. For future feedback, could we use an observation, its effect on the audience and a requested change? Something like, These two headings describe the same category differently, so readers may think they're separate; please use one label. That gives me something specific to act on.", "Agradeço. No próximo feedback, podemos usar observação, efeito no público e mudança solicitada? Por exemplo: Estes títulos nomeiam a mesma categoria de formas diferentes; o leitor pode achar que são separadas; use um só rótulo. Isso dá uma ação específica."],
        ["sparky", "Agreed. And if a comment still sounds broader than the evidence supports, please ask me to narrow it down. That doesn't transfer responsibility for clarity to you. It just gives us a way to catch ambiguity early, alongside my responsibility to write better feedback in the first place.", "Combinado. Se um comentário ainda soar mais amplo que a evidência, pode pedir que eu delimite. Isso não transfere a você a responsabilidade pela clareza; apenas ajuda a detectar ambiguidades cedo, junto da minha obrigação de escrever feedback melhor."]
      ],
      gist: ["What does their repair involve?", "Acknowledging the wording's impact and agreeing on specific changes and future feedback", "Establishing that Pinky deliberately misread an unambiguous instruction", "Keeping every new section to compensate for the hours already spent", "O reparo reconhece impacto, corrige o escopo do feedback e define ações presentes e futuras."],
      detail: ["What had Sparky originally intended to flag?", "Inconsistent headings and missing source labels", "An unsupported central argument and unsuitable examples", "A need to replace the entire presentation before the meeting", "Ele esclarece dois problemas de apresentação, não uma rejeição do conteúdo inteiro."],
      inference: ["Why does Pinky resist keeping the introduction merely because she rewrote it?", "She wants usefulness to guide the choice rather than time already invested", "She believes that original versions are always better", "She wants Sparky to rewrite every section as a punishment", "O tempo gasto explica o impacto, mas não é o critério de qualidade para escolher a versão final."],
      mediation: "Produza em português uma nota de 110–140 palavras para a equipe: explique o problema de comunicação, o que será recuperado ou comparado e o novo protocolo de feedback. Preserve a privacidade e não afirme intenção depreciativa como fato."
    }), rule: "Reparar um mal-entendido não exige escolher entre intenção e impacto. I understood you to mean… atribui a interpretação a quem ouviu; I was referring to… delimita o referente pretendido. Na reformulação, substitua avaliações globais por observação verificável, efeito e pedido. Ao relatar a conversa, não converta uma intenção esclarecida em prova de que a interpretação original era absurda.",
      example: "I understood you to mean the whole approach needed replacing.", translation: "Entendi que você queria dizer que toda a abordagem precisava ser substituída.",
      vocabulary: "clear up — esclarecer\nnarrow down — delimitar\na consistent pass — uma revisão para uniformizar",
      pitfall: "I didn't mean that esclarece intenção, mas não reconhece sozinho a consequência da formulação. Um reparo completo inclui o que ocorreu e como será corrigido.",
      gap: "I understood you ___ that the whole approach was unsuitable.", fills: ["to mean", "meaning to that", "to meaning"], gapExplanation: "Understand someone to mean é a construção para explicar a interpretação atribuída às palavras de alguém.",
      production: "Escreva 220–260 palavras reparando um feedback ambíguo em um projeto fictício. Distinga intenção e interpretação, reconheça uma consequência concreta e reescreva dois comentários globais como observação, efeito e ação. Termine com um acordo verificável.",
      speakingTask: "Explique um mal-entendido por dois minutos sem acusar a outra pessoa de má intenção. Responda à réplica But that isn't what I meant, reconhecendo o esclarecimento e mantendo a necessidade de reparar a consequência concreta."
    }),
    listeningLesson({ id: "c1-mediation-04", title: "Interesses por trás de posições incompatíveis", listening: conversation({
      id: "c1-group-conflict", title: "Interesses por trás de posições incompatíveis", level: "C1", context,
      scene: "Two members of a student society prepare to facilitate a dispute about access to a rehearsal room. They test options and avoid inventing consent for absent members.",
      turns: [
        ["sparky", "The society chat has split into two camps over the rehearsal room. The performers want to keep their regular Thursday slot; the workshop group says that leaves them with a time nobody can attend. By this morning, each side was accusing the other of treating the room as its own.", "O grupo se dividiu sobre a sala de ensaio. Os artistas querem manter a quinta habitual; o grupo de oficinas diz que sobra um horário inviável. Hoje cedo, cada lado acusava o outro de agir como dono da sala."],
        ["pinky", "Before proposing a compromise, let's check what each position is protecting. Do the performers need Thursday itself, or a predictable weekly slot? And does nobody can attend mean literally no one, or that the people responsible for running the workshop are unavailable at the alternative time?", "Antes de propor um meio-termo, vamos entender o que cada posição protege. Os artistas precisam da quinta ou de um horário semanal previsível? Ninguém pode significa ninguém mesmo ou que os responsáveis pela oficina não podem no horário alternativo?"],
        ["sparky", "From the messages, the performers have a show in three weeks and two members work most other evenings. The workshop leaders both teach on Tuesdays, which is the only slot they've been offered. We shouldn't assume those constraints are negotiable simply because we would prefer a tidy compromise.", "Pelas mensagens, haverá espetáculo em três semanas e dois artistas trabalham nas outras noites. Os dois líderes da oficina dão aula às terças, único horário oferecido. Não devemos presumir que essas restrições sejam negociáveis só porque queremos um acordo simples."],
        ["pinky", "Exactly. Equal amounts of inconvenience don't automatically make an arrangement workable. Could another room support the workshop temporarily? We would need to check capacity, accessibility and equipment, not just whether a space is empty. A nominal alternative that excludes participants isn't much of an alternative.", "Exatamente. Quantidades iguais de inconveniência não tornam um acordo viável. Outra sala poderia receber a oficina temporariamente? É preciso conferir lotação, acessibilidade e equipamentos, não só se está vazia. Uma alternativa que exclui participantes pouco resolve."],
        ["sparky", "The library meeting room is available on Thursdays, but it has a lower capacity and no storage. The workshop sometimes uses bulky materials. We could ask whether the next three sessions can use smaller activities, but that has to be a genuine question, not a condition we've already imposed.", "A sala da biblioteca está livre às quintas, mas comporta menos gente e não tem depósito. A oficina às vezes usa materiais grandes. Podemos perguntar se três encontros podem ter atividades menores, mas como pergunta real, não condição já imposta."],
        ["pinky", "Then our role is to present a possible short-term arrangement with its trade-offs. After the show, the room allocation should be reviewed using agreed criteria. Otherwise, temporary priority can quietly become permanent entitlement, and the same dispute returns with even less trust next term.", "Nosso papel é apresentar uma possibilidade temporária com seus custos. Depois do espetáculo, a distribuição deve ser revista com critérios acordados. Caso contrário, uma prioridade temporária vira um direito permanente e o conflito retorna com menos confiança no próximo período."],
        ["sparky", "I'll draft a summary that separates confirmed constraints from options needing approval. It will say that nobody has agreed to move yet. We should invite one representative from each group to check the summary before the joint meeting, especially the wording about attendance and accessibility.", "Vou separar restrições confirmadas de opções que exigem aprovação e dizer que ninguém aceitou mudar ainda. Um representante de cada grupo deve conferir o resumo antes da reunião conjunta, especialmente a parte sobre presença e acessibilidade."],
        ["pinky", "Good. We can open the meeting by asking whether we've represented their needs fairly, rather than announcing that we've solved the problem. If the library option fails, we still have a clearer set of constraints to work with. Mediation can make progress before it produces agreement.", "Ótimo. Podemos começar perguntando se representamos as necessidades de forma justa, em vez de anunciar uma solução. Se a biblioteca não servir, ainda teremos restrições mais claras. A mediação pode avançar antes de produzir um acordo."]
      ],
      gist: ["What is the main purpose of their preparation?", "Clarify interests and test a temporary option without claiming agreement", "Allocate the room permanently before consulting either group", "Divide the inconvenience equally regardless of practical consequences", "Eles organizam restrições, interesses e opções, preservando a decisão dos grupos envolvidos."],
      detail: ["Which limitations of the library room are explicitly mentioned?", "Lower capacity and no storage", "A ban on Thursday use and no electricity", "No available tables and compulsory fees", "A sala está disponível, mas lotação e armazenamento podem limitar a oficina."],
      inference: ["Why insist that a temporary arrangement has a review date?", "To prevent a short-term exception from becoming an assumed permanent right", "To guarantee that the workshop must always receive priority", "To avoid discussing accessibility with the groups", "Pinky alerta para a passagem silenciosa de prioridade temporária a direito permanente."],
      mediation: "Prepare uma pauta em português de 120–150 palavras para a reunião conjunta. Separe restrições, opção provisória, verificações de acessibilidade e decisões em aberto. Inclua uma pergunta de validação para cada grupo e não invente consentimento."
    }), rule: "Na mediação, posição é o pedido declarado; interesse é a necessidade que o sustenta. We would need to check… mantém uma condição em aberto. Uma síntese fiel distingue fatos confirmados, possibilidades e consentimento. Não use have agreed para algo apenas sugerido. Concessões formais só ajudam se respeitarem restrições reais de participação.",
      example: "The room could work, subject to a capacity and accessibility check.", translation: "A sala poderia servir, sujeita à verificação de lotação e acessibilidade.",
      vocabulary: "trade-off — ganho acompanhado de custo ou perda\nentitlement — direito presumido ou reconhecido\nroom allocation — distribuição de salas/horários",
      pitfall: "Both groups have agreed to consider é diferente de both groups have agreed to move. Concordar em discutir uma opção não é aceitá-la.",
      gap: "The alternative is available, ___ its suitability still needs checking.", fills: ["although", "despite of", "unless that"], gapExplanation: "Although introduz o contraste entre disponibilidade e adequação ainda não confirmada.",
      production: "Escreva um relatório de mediação de 240–280 palavras para os dois grupos. Apresente necessidades sem rótulos pessoais, duas verificações essenciais, uma proposta limitada no tempo e critérios para a revisão posterior. Marque claramente o que ainda depende de aceite.",
      speakingTask: "Abra uma reunião de mediação em dois minutos. Depois responda à objeção You're just taking their side, explicando os critérios e convidando a pessoa a corrigir a representação de sua necessidade. Não prometa que todos sairão satisfeitos."
    }),
    listeningLesson({ id: "c1-mediation-05", title: "Humor, registro e uma audiência que mudou", listening: conversation({
      id: "c1-humour-register", title: "Humor, registro e uma audiência que mudou", level: "C1", context,
      scene: "Two organisers reconsider a playful reminder before it goes to both longstanding and new club members. Gentle humour is discussed, not acted out as a joke routine.",
      turns: [
        ["pinky", "I've drafted the reminder for the club's equipment return: To our legendary collectors of borrowed cables, your museums are now accepting returns. It made the organising group laugh, but the mailing list now includes new members. I'm wondering whether the joke travels beyond people who know us well.", "Escrevi o lembrete de devolução: Aos lendários colecionadores de cabos emprestados, seus museus já aceitam devoluções. A organização riu, mas a lista agora inclui novatos. Será que a piada funciona fora de quem nos conhece bem?"],
        ["sparky", "I can see the playful intention. Someone who doesn't know the history might hear an accusation of hoarding, though, especially if they returned everything already. The humour relies on a shared understanding that the organisers sometimes forget cables too. That background isn't actually in the message.", "Entendo a intenção brincalhona. Quem não conhece a história pode ouvir uma acusação de acumular coisas, especialmente se já devolveu tudo. O humor depende de saber que os organizadores também esquecem cabos; esse contexto não está na mensagem."],
        ["pinky", "So perhaps I should make it more self-inclusive: Those of us with club cables in our bags, including your absent-minded organisers, please bring them back by Friday. That keeps a little warmth without assigning a bad motive. Or does the aside still distract from the practical instruction?", "Talvez eu deva me incluir: Quem está com cabos do clube na bolsa, inclusive seus organizadores distraídos, por favor devolva até sexta. Mantém certa leveza sem atribuir má intenção. Ou o comentário ainda distrai da instrução prática?"],
        ["sparky", "It depends on the channel. In the familiar group chat, the aside would probably work. In an email that may be forwarded, I'd put the deadline, location and contact first. We can sound friendly through a clear thank-you rather than needing every reader to recognise an ironic voice.", "Depende do canal. No grupo conhecido, o comentário provavelmente funciona. Num e-mail que pode ser encaminhado, eu começaria por prazo, local e contato. Podemos ser cordiais com um agradecimento claro, sem depender de todos reconhecerem ironia."],
        ["pinky", "That's helpful. I also don't want to conclude that new members lack a sense of humour if they find the original wording uncomfortable. They simply have less evidence about our relationships. Even people who know us might read a written message differently when they're in a hurry.", "Ajuda. Também não quero concluir que novatos não têm humor se a frase original incomodar. Eles têm menos informação sobre nossas relações. Mesmo conhecidos podem ler a mensagem de outra forma quando estão com pressa."],
        ["sparky", "Exactly. Tone is partly built by context; it isn't carried intact from the writer's head into the reader's. If someone objects after we send it, we can acknowledge the wording and clarify the request. Saying it was only a joke would leave the practical and relational problems unresolved.", "Exato. O contexto constrói parte do tom; ele não passa intacto da cabeça de quem escreve à de quem lê. Se houver objeção, podemos reconhecer a formulação e esclarecer. Dizer que era só piada deixaria sem solução os problemas prático e relacional."],
        ["pinky", "I'll use the straightforward email: Please return borrowed club cables to the front desk by Friday afternoon; if that isn't possible, contact us so we can arrange another time. Thanks for helping us prepare next week's workshop. The joke can stay in our private draft folder.", "Usarei o e-mail direto: Devolvam os cabos à recepção até sexta à tarde; se não for possível, entrem em contato para combinar outra data. Obrigada por ajudar a preparar a próxima oficina. A piada pode ficar no rascunho privado."],
        ["sparky", "That gives people an action and a reasonable route if they can't meet the deadline. We haven't removed personality from the club; we've chosen a register that suits this audience and purpose. There will be other occasions when shared humour genuinely helps people feel included.", "Isso oferece uma ação e uma alternativa razoável para quem não consegue cumprir o prazo. Não tiramos a personalidade do clube; escolhemos um registro adequado ao público e ao objetivo. Haverá outras ocasiões em que o humor compartilhado ajuda na inclusão."]
      ],
      gist: ["Why do they choose a more straightforward reminder?", "Its audience and possible forwarding make shared context unreliable", "They decide that humour is unacceptable in every club interaction", "They need to accuse new members more explicitly", "A decisão é contextual: audiência ampliada, encaminhamento e necessidade de instrução clara."],
      detail: ["What should someone do if they cannot return a cable by the deadline?", "Contact the organisers to arrange another time", "Keep it until a public apology is requested", "Leave the mailing list before the next workshop", "A versão final inclui um caminho de contato para negociar outra data."],
      inference: ["What does Pinky reject when discussing new members' reactions?", "Treating lack of shared context as a personal failure to understand humour", "The possibility that written tone can be misunderstood", "The idea that organisers should include practical information", "Ela evita atribuir uma deficiência pessoal a uma diferença de contexto e relação."],
      mediation: "Explique em português, em 110–140 palavras, por que a mensagem mudou. Compare intenção humorística e possíveis leituras; descreva como público, canal e finalidade orientaram o registro, sem formular uma regra de que humor é sempre inadequado."
    }), rule: "Humor e ironia dependem de conhecimento compartilhado, relação e canal. Might hear an accusation apresenta uma leitura possível, não uma reação universal. Adaptar o registro exige preservar a ação solicitada e reconsiderar pressupostos. Uma paráfrase competente explica a função da piada sem exigir que a tradução provoque o mesmo efeito humorístico.",
      example: "The joke relies on background knowledge that not every reader shares.", translation: "A piada depende de um conhecimento de contexto que nem todo leitor compartilha.",
      vocabulary: "aside — comentário lateral\nself-inclusive — que inclui quem fala no grupo referido\nforward a message — encaminhar uma mensagem",
      pitfall: "It was only a joke descreve a intenção alegada; não demonstra que todos tinham contexto para interpretar a frase do mesmo modo.",
      gap: "The humour depends ___ knowing the organisers personally.", fills: ["on", "of", "to"], gapExplanation: "Depend on rege a forma em -ing: depends on knowing. O foco é a condição de interpretação.",
      production: "Escreva 240–280 palavras com duas versões de um lembrete: uma para um grupo íntimo e outra para uma lista ampla. Acrescente uma nota editorial justificando as escolhas de registro, sem estereotipar idade, nacionalidade ou capacidade de entender humor.",
      speakingTask: "Explique oralmente uma piada contextual sem tentar obrigar o interlocutor a achá-la engraçada. Responda a I understand the joke, but I still dislike the wording, reconhecendo que compreensão e aprovação são coisas diferentes."
    }),
    listeningLesson({ id: "c1-mediation-06", title: "Projeto: uma síntese que as partes reconhecem", listening: conversation({
      id: "c1-mediation-project", title: "Projeto: uma síntese que as partes reconhecem", level: "C1", context,
      scene: "Two facilitators prepare a written summary after a neighbourhood meeting about a shared courtyard. Reflective, precise, with disagreement left visible rather than a celebratory ending.",
      turns: [
        ["sparky", "I've drafted the courtyard meeting summary, but the closing sentence feels too neat: Residents agreed on a balanced solution. They agreed to try a booking calendar, yet the discussion about evening noise wasn't resolved. I don't want the summary to manufacture consensus simply because a positive ending reads well.", "Escrevi o resumo da reunião sobre o pátio, mas o fechamento ficou simples demais: Os moradores concordaram com uma solução equilibrada. Aceitaram testar um calendário, mas o ruído noturno ficou sem solução. Não quero fabricar consenso porque um final positivo fica bonito."],
        ["pinky", "Then name the scope of the agreement. A four-week calendar trial was accepted; quiet hours and responsibility for enforcement remain open. We should also distinguish support for the trial from support for making it permanent. Several people explicitly wanted evidence about how it worked before deciding that.", "Então delimite o acordo. Aceitaram um teste de calendário de quatro semanas; horário de silêncio e fiscalização continuam abertos. Apoiar o teste é diferente de apoiar permanência. Várias pessoas pediram evidências do funcionamento antes dessa decisão."],
        ["sparky", "One resident said the courtyard was becoming unusable. Another said complaints were stopping any community activity. Those are strong claims, and repeating them as facts would polarise the summary. But removing them entirely might hide why the meeting mattered. How should we represent the concerns fairly?", "Um morador disse que o pátio estava ficando inutilizável. Outro, que reclamações impediam toda atividade comunitária. Repetir isso como fato polarizaria o resumo, mas retirar tudo esconderia o motivo da reunião. Como representar as preocupações com justiça?"],
        ["pinky", "Attribute them and explain the needs underneath: some residents described difficulty resting, while others feared losing opportunities to meet neighbours. We don't have to reproduce every absolute expression. We do need to avoid weakening a serious concern into a vague preference for things to be slightly different.", "Atribua e explique as necessidades: alguns relataram dificuldade para descansar; outros temiam perder oportunidades de convivência. Não é preciso reproduzir todo termo absoluto, mas também não diluir uma preocupação séria numa preferência vaga por uma pequena mudança."],
        ["sparky", "For the trial, the caretaker will maintain the calendar, and organisers must record the event's end time. The residents' group will collect feedback through paper forms as well as an online survey. That matters because two attendees said they don't use the building's messaging app.", "No teste, o zelador manterá o calendário e organizadores registrarão o horário de término. O grupo recolherá opiniões em papel e on-line. Isso importa porque dois participantes disseram não usar o aplicativo do prédio."],
        ["pinky", "Include the review date and who will bring the feedback together. Otherwise, collection can look like participation without influencing a decision. Let's also say that a low number of complaints won't automatically prove satisfaction; people may not know the channel exists or may feel uncomfortable using it.", "Inclua a data de revisão e quem reunirá as respostas. Sem isso, coletar opiniões pode parecer participação sem influir na decisão. Poucas reclamações não provarão automaticamente satisfação: talvez as pessoas desconheçam o canal ou não se sintam à vontade para usá-lo."],
        ["sparky", "I'll ask the two volunteer representatives to check whether the summary captures their concerns before circulating it to everyone. They can correct a misrepresentation, but neither gets to remove the other perspective. We'll mark any remaining disagreement explicitly rather than quietly editing it out to obtain approval.", "Pedirei aos dois representantes voluntários que confiram se o texto registra suas preocupações antes da circulação. Podem corrigir uma representação inadequada, mas não remover a outra perspectiva. Marcaremos divergências restantes em vez de apagá-las para obter aprovação."],
        ["pinky", "That sounds fair. A useful summary doesn't promise harmony; it gives people a reliable record of what happened, what will happen next and what still needs a decision. If each side can recognise its concern without seeing the other erased, we've created a better basis for the next conversation.", "Parece justo. Um resumo útil não promete harmonia; registra com confiança o que ocorreu, os próximos passos e o que ainda exige decisão. Se cada lado reconhece sua preocupação sem apagar o outro, há uma base melhor para conversar novamente."]
      ],
      gist: ["What makes the proposed summary trustworthy?", "It preserves the limited agreement, unresolved concerns and next responsibilities", "It removes disagreement so every resident appears satisfied", "It repeats every strong claim as an established fact", "Fidelidade exige limites do consenso, atribuição de preocupações e ações com responsabilidade."],
      detail: ["Why will feedback also be collected on paper?", "Some attendees do not use the building's messaging app", "The online survey has already been permanently cancelled", "Only residents who complain are allowed to participate", "O papel amplia o acesso para pessoas fora do aplicativo; não substitui necessariamente o canal on-line."],
      inference: ["Why might few complaints be weak evidence of satisfaction?", "Access and willingness to report can affect the number received", "Every resident has already rejected the calendar trial", "Complaints can never provide useful information about a shared space", "O número depende também de conhecimento do canal e conforto para usá-lo; ausência de registro não equivale automaticamente a satisfação."],
      mediation: "Produza um resumo bilíngue da reunião: 180–220 palavras em inglês e uma versão funcional de 100–130 em português para um morador recém-chegado. Preserve os limites do acordo, canais de participação e questões abertas. Marque data e responsável pela síntese como informações ainda a confirmar; não invente esses dados."
    }), rule: "Uma síntese mediadora seleciona e reorganiza informação para um destinatário sem mudar o grau de certeza ou consenso. Agreed to try não equivale a approved permanently. Atribua avaliações fortes e preserve a gravidade da preocupação ao reformular. Lacunas relevantes devem permanecer visíveis: inclua to be confirmed quando o diálogo pede uma data mas não a fornece.",
      example: "Residents agreed to a trial; permanent adoption remains undecided.", translation: "Os moradores aceitaram um teste; a adoção permanente segue sem decisão.",
      vocabulary: "manufacture consensus — produzir uma aparência falsa de consenso\nmisrepresentation — representação distorcida\ncirculate a summary — distribuir um resumo",
      pitfall: "O diálogo pede que seja incluída uma data de revisão, mas não informa qual. Preencher uma data plausível sem fonte cria informação falsa.",
      gap: "Permanent adoption remains ___ until the trial is reviewed.", fills: ["undecided", "unanimously approved", "already implemented"], gapExplanation: "Undecided preserva a decisão em aberto. As outras opções contradizem a distinção entre teste e permanência.",
      production: "Escreva um relatório em inglês de 260–300 palavras para os moradores. Separe acordo, preocupações atribuídas, responsabilidades, participação e decisões pendentes. Inclua uma nota de duas frases explicando uma informação que você deliberadamente não inventou.",
      speakingTask: "Apresente a síntese em dois minutos. Responda a So everybody is happy with the new rules? Corrija a conclusão preservando o avanço real, e convide o interlocutor a verificar se sua própria preocupação foi representada com fidelidade."
    })
  ]
}];
