import type { ModuleDraft } from "./types";
import { conversation, listeningLesson } from "./listening-authoring.ts";
const context = "A nuanced extended dialogue between two thoughtful adults. Sparky/Achird has a warm lower-middle pitch; Pinky/Zephyr is clear and warm with a higher-middle pitch. A measured natural pace of 135–145 words per minute, with subtle stress on qualifications, self-corrections and changes of stance. Preserve all words and turn boundaries. No music, effects, caricature or overlapping words. Allow the listener time to follow complex distinctions.";

export const c2InterculturalModules: ModuleDraft[] = [{
  id: "c2-intercultural", title: "Inglês internacional e nuance cultural", level: "C2", prerequisiteId: "c2-estilo-cultura",
  description: "Interpretar linguagem figurada, implicaturas e referências sem reduzir pessoas a estereótipos; adaptar mensagens preservando nuances e finalidade.",
  lessons: [
    listeningLesson({ id: "c2-intercultural-01", title: "Quando a expressão muda de função", listening: conversation({
      id: "c2-idioms-context", title: "Quando a expressão muda de função", level: "C2", context,
      scene: "Two colleagues unpack the expression move the goalposts after an international project meeting. Their analysis becomes a practical decision about what to write to the team.",
      turns: [
        ["sparky", "When the coordinator said we couldn't move the goalposts halfway through the project, I took it as a rejection of any change to the assessment criteria. But afterwards she approved an additional accessibility option. I'm trying to work out whether she contradicted herself or whether I made the expression do more work than it was meant to.", "Quando a coordenadora disse que não podíamos mudar as regras no meio do projeto, entendi rejeição a qualquer mudança nos critérios. Depois ela aprovou uma alternativa de acessibilidade. Tento entender se houve contradição ou se atribuí à expressão um alcance maior que o pretendido."],
        ["pinky", "The expression usually criticises a change that makes an agreed target unfairly different or harder to reach. It doesn't necessarily condemn every procedural adjustment. What exactly had someone proposed before she used it? The surrounding exchange may tell us whether she was defending the learning outcome, the deadline or one particular submission format.", "A expressão costuma criticar mudança que torna uma meta acordada injustamente diferente ou mais difícil. Não condena necessariamente todo ajuste de procedimento. O que propuseram antes? O contexto pode indicar se defendia o resultado de aprendizagem, o prazo ou um formato de entrega."],
        ["sparky", "One person suggested requiring an extra written report after the work had already been submitted. The accessibility option, by contrast, let a participant present the same analysis through an alternative format that had been discussed before the deadline. So the two changes didn't alter the obligation in the same way, even though both involved departing from the initial document.", "Alguém propôs exigir um relatório extra depois da entrega. A alternativa acessível permitia apresentar a mesma análise em formato discutido antes do prazo. As mudanças não alteravam a obrigação do mesmo modo, embora ambas divergissem do documento inicial."],
        ["pinky", "Then the apparent inconsistency may disappear once we separate an added demand from an alternative route to the same objective. I'd still confirm that interpretation with her rather than treat our reconstruction as a ruling. Figurative language can signal a stance very efficiently while leaving its exact scope unstated, which is useful in conversation and risky in a formal record.", "A aparente incoerência pode desaparecer ao separar exigência adicional de outra via ao mesmo objetivo. Ainda confirmaria com ela, sem tratar nossa reconstrução como decisão oficial. A linguagem figurada sinaliza posição de modo eficiente, mas pode deixar o alcance implícito: útil na conversa, arriscado no registro formal."],
        ["sparky", "I'm preparing the summary for colleagues who weren't there. Would you retain move the goalposts and explain it, or replace it entirely? I don't want to flatten the coordinator's objection into a neutral statement that some paperwork changed. She was making a fairness argument, and that evaluative force is part of what the summary needs to preserve.", "Vou resumir para ausentes. Manteria a expressão com explicação ou a substituiria? Não quero reduzir a objeção a uma frase neutra sobre mudança de documentos. Ela argumentava sobre justiça, e essa força avaliativa precisa permanecer."],
        ["pinky", "I'd write that she objected to imposing a new requirement after submission because participants had worked towards the previously agreed target. That preserves both the criticism and its reason without assuming everyone shares the sporting metaphor. If the expression itself becomes relevant to a dispute about her wording, quote it separately and distinguish the quotation from your interpretation.", "Escreveria que ela se opôs a impor uma exigência após a entrega porque participantes trabalharam para a meta acordada. Isso preserva crítica e motivo sem exigir a metáfora esportiva. Se a expressão entrar numa disputa sobre suas palavras, cite separadamente e diferencie citação de interpretação."],
        ["sparky", "That also avoids turning one vivid phrase into a universal rule about change. I notice how easy it is to remember the idiom and forget the proposal it responded to. The phrase then feels like a policy, although the actual policy would need to specify what remains fixed, what can be adjusted and who has authority to decide.", "Isso evita converter uma frase marcante numa regra universal. É fácil lembrar a expressão e esquecer a proposta a que respondia. Ela passa a parecer uma política, que na verdade precisaria dizer o que é fixo, ajustável e quem decide."],
        ["pinky", "Exactly. Recognising an idiom is only the first step; interpreting its function requires the turn before it and the action after it. For the summary, preserve the fairness objection, mark our inference as provisional and ask the coordinator to confirm the distinction. We can be precise without pretending the metaphor carries a complete rulebook inside it.", "Exatamente. Reconhecer a expressão é só o início; sua função depende do turno anterior e da ação posterior. Preserve a objeção de justiça, marque a inferência como provisória e peça confirmação. Podemos ser precisos sem fingir que a metáfora contém um regulamento inteiro."]
      ], gist: ["What resolves the apparent inconsistency?", "Distinguishing an added obligation from an alternative way to meet the same objective", "Assuming that all procedural changes are forbidden by the idiom", "Concluding that the coordinator's later action cancels every earlier criterion", "As alterações diferem em sua função e efeito sobre a obrigação; a interpretação ainda precisa de confirmação."],
      detail: ["Which proposed change triggered the coordinator's objection?", "An extra written report required after submission", "An alternative format discussed before the deadline", "A request to explain an unfamiliar sporting expression", "O turno anterior tratava de acrescentar uma exigência depois de o trabalho ser entregue."],
      inference: ["Why does Pinky resist treating the metaphor as a formal rule?", "Its evaluative stance is clearer than its precise operational scope", "Its meaning is unrelated to fairness in any possible context", "Figurative expressions cannot convey a speaker's position", "A metáfora expressa crítica com força, mas não define sozinha escopo, condições e autoridade."],
      mediation: "Escreva em português, em 140–180 palavras, um registro para colegas ausentes. Preserve a objeção e seu fundamento, explique a diferença entre as alterações e identifique o que é reconstrução provisória. Se citar a expressão, separe as palavras da coordenadora de sua paráfrase."
    }), rule: "Dominar uma expressão idiomática inclui seu valor avaliativo e seu alcance local. Move the goalposts costuma criticar alteração injusta de meta, mas o contexto delimita qual mudança está em questão. Na mediação, preserve posição e justificativa, não apenas o conteúdo literal. Diferencie reconhecimento lexical, inferência contextual e regra institucional confirmada.",
      example: "The objection concerned an added obligation, not every conceivable adjustment.", translation: "A objeção dizia respeito a uma obrigação adicional, não a todo ajuste concebível.",
      vocabulary: "evaluative force — força de avaliação/crítica\nformal record — registro formal\nrulebook — conjunto de regras; aqui, usado figuradamente",
      pitfall: "Uma expressão reconhecível pode parecer mais precisa do que é. Recuperar o turno a que ela responde evita ampliar uma objeção local para uma proibição geral.",
      gap: "The metaphor conveyed a criticism ___ specifying its complete scope.", fills: ["without", "despite of", "unless to"], gapExplanation: "Without + -ing expressa o que a metáfora não fez, preservando a crítica que efetivamente comunicou.",
      production: "Escreva uma análise de 280–330 palavras para uma equipe internacional. Compare a leitura inicial e a contextual, proponha uma paráfrase funcional e explique o que seria perdido numa versão excessivamente neutra. Termine com uma pergunta de confirmação que não induza a resposta.",
      speakingTask: "Explique a expressão e seu uso neste caso em três minutos. Responda à objeção But she said we couldn't change the rules, distinguindo citação, inferência e aplicação sem atribuir certeza maior que a disponível."
    }),
    listeningLesson({ id: "c2-intercultural-02", title: "O que uma concordância parcial deixa em aberto", listening: conversation({
      id: "c2-implicature", title: "O que uma concordância parcial deixa em aberto", level: "C2", context,
      scene: "Two project partners examine a restrained response to a proposal. They weigh competing interpretations and formulate a precise follow-up rather than assuming politeness means consent.",
      turns: [
        ["pinky", "The partner replied, Your proposal is certainly ambitious; it gives us a great deal to think about. Everyone in our chat treated that as enthusiastic support, but I wasn't convinced. The reply acknowledges the proposal without committing to the schedule, budget or even a next meeting. Am I reading reluctance into a perfectly polite message?", "A parceira respondeu que a proposta era certamente ambiciosa e dava muito em que pensar. O grupo entendeu apoio entusiasmado, mas não me convenceu. Reconhece a proposta sem assumir prazo, orçamento ou reunião. Estou enxergando relutância numa mensagem apenas educada?"],
        ["sparky", "Possibly, but enthusiasm is also an inference here. Ambitious can praise vision or gently flag unrealistic demands; the word alone doesn't settle which. The surrounding facts matter. Did the partner previously ask for a smaller pilot? Was she responding immediately, or after a detailed review? We should compare interpretations rather than substitute one confident reading for another.", "Talvez, mas entusiasmo também é inferência. Ambitious pode elogiar visão ou sinalizar exigências pouco realistas; a palavra não decide. Ela pedira um piloto menor? Respondeu imediatamente ou após revisão? Devemos comparar leituras, não trocar uma certeza por outra."],
        ["pinky", "She had asked whether we could start with one location, whereas our revised proposal still covers four. Her reply came within an hour and included no detailed comments. That makes hesitation plausible, but it doesn't prove she has rejected the project. She may simply not have had time to consult the people responsible for delivery.", "Ela perguntara se poderíamos começar num local, mas a revisão ainda prevê quatro. Respondeu em uma hora, sem comentários detalhados. Isso torna hesitação plausível, não prova rejeição. Talvez faltasse tempo para consultar quem executaria."],
        ["sparky", "Exactly. We can act on uncertainty without resolving her private attitude. A useful reply would thank her, acknowledge the outstanding question about scale and ask whether she wants a one-location option before the next discussion. That creates a decision she can respond to, instead of asking her to label herself enthusiastic or reluctant.", "Exato. Podemos agir diante da incerteza sem descobrir sua atitude privada. A resposta pode agradecer, reconhecer a questão de escala e perguntar se deseja uma opção de um local antes da próxima discussão. Isso cria uma decisão concreta, sem pedir que se declare entusiasmada ou relutante."],
        ["pinky", "I was tempted to write, We're delighted you support our ambitious approach. I can see now how that would smuggle agreement into the exchange. She would then have to correct a position she never stated, which could make the next message feel more confrontational than simply clarifying the open issue now.", "Pensei em escrever que estávamos felizes com seu apoio à abordagem ambiciosa. Isso introduziria um acordo que não houve. Ela teria de corrigir uma posição nunca declarada, tornando a mensagem seguinte mais confrontadora que esclarecer a questão agora."],
        ["sparky", "Yes, and the opposite reply would be equally risky: We're sorry the proposal doesn't meet your expectations. That presupposes dissatisfaction. A neutral acknowledgement needn't be cold; it can show careful attention to the actual content. Thanks for considering this; the scale question remains open, and we can prepare a smaller option if useful.", "Sim, e a resposta oposta também seria arriscada: Lamentamos que a proposta não atenda às expectativas. Isso pressupõe insatisfação. Reconhecer sem presumir não é ser frio; pode mostrar atenção. Obrigado pela análise; a escala segue em aberto e podemos preparar uma opção menor."],
        ["pinky", "For the internal update, I'll say that we received an initial acknowledgement and are seeking clarification on scope. I won't describe the partner as evasive. We have evidence of non-commitment in this message, not evidence of a stable personality trait or a general reluctance to collaborate with us.", "No informe interno, direi que recebemos reconhecimento inicial e buscamos esclarecer o escopo. Não a chamarei de evasiva. Temos evidência de ausência de compromisso nesta mensagem, não de um traço permanente ou de relutância geral em colaborar."],
        ["sparky", "That distinction is precisely what keeps an ambiguous exchange from hardening into a story about someone's character. We should notice implications, weigh them against context and still leave room for correction. Advanced comprehension isn't certainty about hidden motives; it's knowing which interpretation is supported enough to guide a proportionate next step.", "É essa distinção que impede uma troca ambígua de virar uma história sobre o caráter de alguém. Devemos notar implicações, pesar o contexto e permitir correção. Compreensão avançada não é certeza sobre motivos ocultos; é saber qual leitura sustenta um próximo passo proporcional."]
      ], gist: ["What response do they decide is justified?", "Acknowledge the message and clarify scope without presuming support or rejection", "Announce that the partner has approved all four locations", "Treat polite wording as conclusive evidence of dishonesty", "Eles preservam a ambiguidade relevante e convertem a questão em uma pergunta de decisão concreta."],
      detail: ["What discrepancy remains between the partner's earlier question and the proposal?", "One initial location was raised, but the proposal still covers four", "The partner requested four locations and the proposal covers none", "The budget was approved, but the location has already closed", "A escala de um local versus quatro fundamenta uma hipótese de hesitação, sem comprová-la."],
      inference: ["Why would We're delighted you support our approach be problematic?", "It embeds agreement that the partner has not explicitly given", "It avoids making any assumption about the partner's stance", "It directly answers the unresolved scale question", "O agradecimento pressupõe apoio e transfere à parceira o trabalho de desfazer uma posição não assumida."],
      mediation: "Redija em português um informe de 140–180 palavras distinguindo conteúdo explícito, duas leituras plausíveis e próximo passo. Não descreva personalidade ou intenção oculta como fato. Explique por que a questão de escala merece confirmação."
    }), rule: "Implicaturas dependem de contexto e podem ser canceladas por esclarecimento. Certainly ambitious não determina sozinho elogio ou reserva. Pressuposições podem aparecer dentro de um agradecimento: delighted you support assume apoio. Para responder com precisão, mantenha separadas observação textual, inferência de atitude e compromisso operacional.",
      example: "The reply acknowledges the proposal without committing to its scope.", translation: "A resposta reconhece a proposta sem se comprometer com seu escopo.",
      vocabulary: "non-commitment — ausência de compromisso assumido\nsmuggle agreement into — introduzir acordo como pressuposto\nharden into — consolidar-se, tornar-se rígido",
      pitfall: "Perceber possível hesitação não autoriza rotular alguém de evasivo. Uma inferência sobre uma mensagem não comprova um traço pessoal.",
      gap: "Calling the partner reluctant would go ___ what the message establishes.", fills: ["beyond", "within of", "under to"], gapExplanation: "Go beyond expressa ultrapassar o alcance da evidência disponível.",
      production: "Escreva 280–330 palavras contendo um informe interno e uma resposta à parceira. No informe, compare hipóteses; na resposta, formule uma pergunta que permita esclarecimento sem pressupor aprovação ou descontentamento. Justifique duas escolhas de linguagem.",
      speakingTask: "Explique em três minutos por que elogio verbal e compromisso são distintos. Responda a Surely ambitious means she likes it, reconhecendo essa possibilidade e apresentando uma alternativa contextual sem afirmar intenção oculta."
    }),
    listeningLesson({ id: "c2-intercultural-03", title: "O silêncio que não autoriza uma decisão", listening: conversation({
      id: "c2-pragmatic-silence", title: "O silêncio que não autoriza uma decisão", level: "C2", context,
      scene: "Two facilitators reflect on a pause during an online multilingual meeting. They distinguish conversational silence from evidence of agreement and redesign the decision procedure.",
      turns: [
        ["sparky", "After I asked whether anyone objected to the new schedule, there was a long pause, so I announced that we had agreement. Later, two colleagues wrote that the schedule was impossible for them. My first reaction was that they should have spoken up, but I'm beginning to question what the silence actually allowed me to conclude.", "Perguntei se alguém se opunha ao cronograma. Houve uma pausa longa, e anunciei acordo. Depois, dois colegas disseram que era impossível para eles. Achei primeiro que deveriam ter falado, mas questiono agora o que o silêncio permitia concluir."],
        ["pinky", "What did participants know about the decision process? Had you said that silence would count as agreement, and had everyone accepted that rule? Without that, you may have treated the absence of an objection in one moment as positive consent. Even an explicit rule would need a fair opportunity to understand the proposal and respond.", "O que sabiam sobre o processo? Você disse que silêncio contaria como acordo, e todos aceitaram essa regra? Sem isso, talvez tenha convertido ausência de objeção num momento em consentimento. Mesmo uma regra explícita exigiria oportunidade justa de entender e responder."],
        ["sparky", "I shared the timetable on screen while describing it, then moved straight to the question. Some people were viewing the call on phones, and the text was small. One colleague later said she was working out the time-zone difference. Another had begun typing a question in the chat, but I moved to the next agenda item before it appeared.", "Mostrei o cronograma na tela enquanto explicava e perguntei em seguida. Alguns estavam no celular, com texto pequeno. Uma colega calculava o fuso; outra digitava no chat, mas passei de assunto antes de a pergunta aparecer."],
        ["pinky", "Those are concrete explanations worth addressing. I'd avoid reaching first for a claim that people from a particular culture never disagree publicly. Preferences about turn-taking vary within groups, and technical access, hierarchy or simple processing time can produce similar silences. A cultural explanation may be possible, but it shouldn't replace evidence about this meeting.", "São explicações concretas. Eu evitaria começar dizendo que pessoas de certa cultura nunca discordam em público. Há variação dentro dos grupos, e acesso técnico, hierarquia ou tempo de processamento podem produzir silêncios semelhantes. Uma explicação cultural pode ser possível, mas não substitui evidência desta reunião."],
        ["sparky", "So the repair should start with the process I controlled. I can send a readable schedule with time zones labelled, state the decision deadline and invite people to flag an unworkable slot privately or in the shared channel. But I don't want a fresh consultation to imply that the original announcement never happened.", "O reparo deve começar pelo processo que eu controlava. Posso enviar uma tabela legível, com fusos, prazo de decisão e possibilidade de apontar problemas em privado ou no grupo. Mas a nova consulta não deve fingir que o anúncio anterior não existiu."],
        ["pinky", "Then correct the record explicitly: I described the pause as agreement, but that overstated what we had established. The schedule is provisional pending confirmation. Give a clear way to say yes, no or I need clarification. Those responses provide different information, and collapsing the third into either of the first two would recreate the problem.", "Corrija explicitamente: Descrevi a pausa como acordo, mas isso exagerou o estabelecido. O horário é provisório até confirmação. Ofereça sim, não ou preciso esclarecer. São informações diferentes; converter a terceira em uma das primeiras repetiria o problema."],
        ["sparky", "For future meetings, we could circulate decisions in advance and pause after the proposal for questions before asking for a position. I'd also wait for the chat and check the written responses. That won't eliminate every imbalance, but it creates more than one route into the conversation and makes the final decision less dependent on speaking quickly.", "Podemos circular decisões antes e reservar perguntas após a proposta, antes de pedir posições. Eu esperaria o chat e conferiria respostas escritas. Não elimina toda desigualdade, mas cria mais de uma via de participação e reduz a dependência de falar rápido."],
        ["pinky", "Yes. Silence can be interactionally meaningful without being a reliable vote. The competent response is not to declare it meaningless, nor to assign it one universal meaning. It's to recognise the limits of your interpretation and use a procedure that lets participants make their position available in a form they can actually use.", "Sim. O silêncio pode ter significado na interação sem ser um voto confiável. A resposta competente não é esvaziá-lo nem dar-lhe um significado universal, mas reconhecer limites e usar um processo pelo qual as pessoas expressem sua posição de forma acessível."]
      ], gist: ["What is the core correction to the meeting process?", "Replace an assumption of consent with an accessible, explicit confirmation procedure", "Treat all silence as definite opposition", "Require faster spoken responses so written questions become unnecessary", "O reparo distingue ausência momentânea de fala e consentimento e melhora condições de participação."],
      detail: ["What were two colleagues doing during the pause?", "Calculating a time-zone difference and typing a question", "Approving the schedule in a separate binding vote", "Leaving the project because the decision had already been confirmed", "Os exemplos concretos mostram atividades compatíveis com silêncio sem acordo."],
      inference: ["Why does Pinky resist an immediate national-cultural explanation?", "It could obscure observed procedural barriers and variation within groups", "She believes culture can never influence interaction", "She wants to assign the silence a single technical cause", "Ela não nega influência cultural; recusa usá-la como substituto de evidências locais e diversidade individual."],
      mediation: "Escreva em português uma correção de ata de 140–180 palavras. Reconheça o anúncio anterior, restabeleça o caráter provisório e proponha confirmação acessível. Preserve a diferença entre discordância e necessidade de esclarecimento, sem estereótipos culturais."
    }), rule: "Silêncio é subdeterminado: pode acompanhar reflexão, dificuldade de acesso, deferência ou oposição, conforme o contexto. Ausência de objeção não é automaticamente consentimento. Na mediação, descreva comportamentos observados e condições de participação antes de explicar intenções. Nor permite rejeitar uma segunda generalização sem escolher a primeira.",
      example: "Silence is neither a reliable vote nor proof of a single cultural preference.", translation: "O silêncio não é voto confiável nem prova de uma única preferência cultural.",
      vocabulary: "turn-taking — organização dos turnos de fala\nprovisional — provisório\noverstate — afirmar além do que foi estabelecido",
      pitfall: "Não trocar o estereótipo silêncio = acordo por silêncio = discordância. A necessidade é um procedimento de confirmação, não uma nova interpretação universal.",
      gap: "The schedule remains provisional ___ explicit confirmation from participants.", fills: ["pending", "despite of", "because to"], gapExplanation: "Pending, aqui preposição, significa à espera de; mantém a decisão sem confirmação definitiva.",
      production: "Escreva 290–340 palavras com uma correção de ata e um protocolo de reunião. Inclua oportunidade de leitura, perguntas, múltiplos canais e registro da decisão. Explique por que o protocolo evita depender de hipóteses sobre a personalidade ou cultura de cada participante.",
      speakingTask: "Repare oralmente o anúncio de um acordo não confirmado em três minutos. Responda a But nobody said no, distinguindo oportunidade de responder, resposta observável e consentimento sem atribuir culpa aos participantes."
    }),
    listeningLesson({ id: "c2-intercultural-04", title: "Traduzir uma referência sem apagar sua força", listening: conversation({
      id: "c2-cultural-reference", title: "Traduzir uma referência sem apagar sua força", level: "C2", context,
      scene: "Two editors adapt a fictional opinion column for an international newsletter. They discuss a sporting metaphor and a local cultural reference without assuming shared knowledge.",
      turns: [
        ["pinky", "The column calls the committee's promise to consult residents a rain check on democracy. It's a sharp line, but several international readers may know neither the expression rain check nor the local history of postponed meetings. A literal translation would preserve the weather image and lose most of the criticism. I'm unsure how much explanation the sentence can carry.", "A coluna chama a promessa de consulta de um rain check on democracy. A frase é incisiva, mas leitores internacionais talvez não conheçam a expressão nem o histórico local de reuniões adiadas. Traduzir literalmente preservaria a chuva e perderia a crítica. Não sei quanta explicação cabe na frase."],
        ["sparky", "We should first identify what the line is doing. A rain check usually offers the possibility of taking something up later; here, the writer is suggesting that participation is repeatedly deferred rather than genuinely provided. The humour depends on making a civic commitment sound like a casual invitation that can be postponed. That's the functional contrast we need to retain.", "Primeiro, a função: rain check costuma oferecer retomar algo depois; aqui, a autora sugere participação repetidamente adiada em vez de realizada. O humor trata um compromisso cívico como convite casual adiável. Esse contraste funcional precisa permanecer."],
        ["pinky", "The evidence in the column is that three scheduled consultations were postponed and no replacement date was announced. It doesn't establish that the committee secretly intends never to hold one. If I paraphrase the line as the committee has abolished public participation, I'd intensify the accusation beyond what the writer actually supports, even though the paraphrase sounds forceful.", "A coluna informa três consultas adiadas sem nova data. Não prova intenção secreta de nunca realizá-las. Se eu escrever que o comitê aboliu a participação, intensificarei a acusação além do sustentado, ainda que soe forte."],
        ["sparky", "Exactly. We could say the writer portrays consultation as a promise endlessly pushed into the future, then give the three postponements as the basis for that portrayal. Endlessly is rhetorical rather than a measured duration, so the attribution matters. If we want a more neutral news summary, we should keep the documented postponements and label the author's judgement separately.", "Exato. Podemos dizer que a autora retrata a consulta como promessa sempre empurrada para o futuro, com os três adiamentos como base. Sempre é retórico, não duração medida; por isso a atribuição importa. Num resumo noticioso neutro, manteríamos os adiamentos e separaríamos o julgamento."],
        ["pinky", "There is also a reference to the old town hall clock, which locals associate with announcements that arrived late. Without that background, the next joke simply looks like a complaint about faulty machinery. I could add a brief note, but two explanations in one paragraph might make the adapted version feel like a lesson in local trivia.", "Há ainda referência ao relógio antigo da prefeitura, associado localmente a avisos tardios. Sem contexto, a piada parece reclamação de máquina defeituosa. Posso pôr nota, mas duas explicações no parágrafo podem transformar a adaptação numa aula de curiosidades locais."],
        ["sparky", "Then prioritise the reference that carries the argument. Keep the rain-check idea through a functional paraphrase and explain the clock only if its history is necessary for understanding a later point. An adaptation doesn't owe every detail equal space. It owes the intended reader an equivalent opportunity to follow the argument and recognise the author's stance.", "Priorize a referência que sustenta o argumento. Preserve a ideia de adiamento por paráfrase funcional e explique o relógio só se sua história for necessária depois. A adaptação não deve espaço igual a cada detalhe; deve dar ao leitor oportunidade equivalente de acompanhar argumento e posição."],
        ["pinky", "I'll also label the piece as an opinion column, because otherwise the rhetorical choices could be mistaken for the newsletter's factual findings. In the editorial note, I'll explain which reference was paraphrased and why. That makes the adaptation visible without interrupting every sentence to announce that another wording choice has been made.", "Também identificarei como coluna de opinião, para escolhas retóricas não parecerem descobertas factuais do boletim. Na nota editorial, explicarei qual referência foi parafraseada e por quê, tornando a adaptação visível sem interromper cada frase."],
        ["sparky", "That seems proportionate. We're preserving criticism, attribution and the evidence behind it, while allowing the form to change for a different audience. The goal isn't to make every reader laugh at exactly the same point. It's to avoid giving one audience a sharp argument and another a puzzling weather report or an accusation stronger than the original.", "Parece proporcional. Preservamos crítica, atribuição e evidência, mudando a forma para outro público. Não precisamos fazer todos rirem no mesmo ponto, mas evitar que um público receba um argumento incisivo e outro, uma previsão confusa ou acusação mais forte que a original."]
      ], gist: ["What principle guides their adaptation?", "Preserve argument, evaluative force and attribution while adjusting references to the audience", "Keep every metaphor literally even when its function becomes unclear", "Strengthen the accusation to compensate for lost humour", "A adaptação altera forma sem falsificar função, intensidade ou evidência."],
      detail: ["What documented events support the column's criticism?", "Three consultations were postponed without a replacement date", "The committee formally abolished all public consultation", "A broken clock prevented residents from entering the building", "Os três adiamentos são fatos do texto fictício; intenção secreta e abolição não foram estabelecidas."],
      inference: ["Why does the genre label matter?", "Readers need to distinguish rhetorical judgement from reported factual findings", "Opinion columns are exempt from the need for accurate evidence", "Labelling the genre makes every cultural explanation unnecessary", "O rótulo ajuda a situar a voz avaliativa, mas não autoriza distorcer fatos."],
      mediation: "Adapte a crítica para leitores brasileiros em 150–190 palavras. Preserve fatos, autoria e força avaliativa sem tradução literal confusa nem acusação ampliada. Acrescente uma nota curta explicando uma referência mantida, parafraseada ou omitida."
    }), rule: "Mediação intercultural não é substituição palavra por palavra. Identifique a função discursiva da referência: argumento, ironia, evidência ou ambientação. Uma paráfrase funcional pode preservar a crítica melhor que uma metáfora literal. Mantenha atribuição e gênero para não converter linguagem retórica em fato nem aumentar uma acusação por conveniência estilística.",
      example: "The adaptation preserves the criticism without escalating the accusation.", translation: "A adaptação preserva a crítica sem ampliar a acusação.",
      vocabulary: "take a rain check — deixar uma proposta para outra ocasião\nportray — retratar de determinado modo\nfunctional paraphrase — paráfrase que preserva a função comunicativa",
      pitfall: "Uma expressão retórica como endlessly não equivale a prova de duração infinita ou intenção definitiva. Atribua a avaliação e mantenha os eventos que a sustentam.",
      gap: "The writer portrays consultation ___ a promise repeatedly deferred.", fills: ["as", "like to", "for being to"], gapExplanation: "Portray something as introduz a forma como a autora representa algo, preservando a atribuição da avaliação.",
      production: "Escreva 300–350 palavras contendo uma adaptação em inglês simples para leitores internacionais e uma nota editorial em inglês. Explique como tratou metáfora, referência local, gênero e alcance da acusação. Não invente fatos sobre o relógio além dos fornecidos.",
      speakingTask: "Explique a crítica por três minutos a alguém que desconhece as referências. Responda a Why not translate every word exactly?, comparando fidelidade à forma e à função com um exemplo concreto do diálogo."
    }),
    listeningLesson({ id: "c2-intercultural-05", title: "Adaptar a interação sem imitar identidades", listening: conversation({
      id: "c2-intercultural-adaptation", title: "Adaptar a interação sem imitar identidades", level: "C2", context,
      scene: "Two facilitators prepare an international online workshop. They discuss register, accommodation and clarification, explicitly avoiding national stereotypes or accent imitation.",
      turns: [
        ["sparky", "We've been asked to make the workshop feel more international, and the draft guidance suggests matching our style to each participant's nationality. That sounds superficially attentive, but I can imagine it producing awkward assumptions: being unusually indirect with one person, over-familiar with another, or treating an accent as a guide to someone's professional preferences.", "Pedem um workshop mais internacional, e a orientação sugere adaptar estilo à nacionalidade. Parece atencioso, mas pode gerar pressupostos constrangedores: indireção excessiva com alguém, familiaridade com outro ou usar sotaque como indício de preferência profissional."],
        ["pinky", "I'd replace that with responsiveness to observable needs and stated preferences. We can ask how people want to be addressed, explain the discussion format and offer ways to request clarification. Accommodation doesn't require impersonating another variety of English or guessing a person's relationship to a cultural convention. It means making the exchange more workable while treating their identity as theirs to define.", "Eu usaria necessidades observáveis e preferências declaradas. Podemos perguntar formas de tratamento, explicar a discussão e oferecer esclarecimento. Acomodação não exige imitar uma variedade de inglês nem adivinhar relação com convenções; torna a troca viável sem definir a identidade alheia."],
        ["sparky", "What about simplifying our language? I don't want to bury the discussion in local idioms, but speaking in unnaturally short sentences to highly experienced colleagues could sound patronising. Their unfamiliarity with our organisation's abbreviations isn't evidence that they need the ideas themselves reduced to elementary content.", "E simplificar? Não quero encher a conversa de expressões locais, mas frases artificialmente curtas para colegas experientes podem soar condescendentes. Não conhecer siglas da organização não prova necessidade de reduzir as ideias a conteúdo elementar."],
        ["pinky", "Exactly. We can unpack references and structure complex information without removing complexity. Say the full name before using an abbreviation, signpost a change of topic and check understanding at meaningful points. A question such as Which part needs a clearer example? invites useful feedback more effectively than a repeated Do you understand?, which can make a public admission of difficulty feel costly.", "Exato. Podemos explicar referências e estruturar informação complexa sem eliminar complexidade. Apresente o nome antes da sigla, sinalize mudanças e confira em pontos relevantes. Qual parte precisa de exemplo melhor? ajuda mais que repetir Entendeu?, o que pode tornar constrangedor admitir dificuldade."],
        ["sparky", "There's a related issue with disagreement. Some facilitators fill every pause by offering their own interpretation, as though a quick response were proof of engagement. I'd like to allow a short thinking interval and a written contribution option. We should explain that these are available to everyone, rather than assigning them to people we assume will be less confident speaking.", "Há a discordância. Alguns facilitadores preenchem pausas com sua interpretação, como se rapidez provasse participação. Quero tempo de reflexão e contribuição escrita, disponíveis a todos, não atribuídos a quem presumimos menos confiante."],
        ["pinky", "Yes, and we should preserve genuine disagreement once it appears. Making communication comfortable doesn't mean translating a firm objection into a mild suggestion so the meeting feels harmonious. We can restate the objection, ask whether we've captured it and separate the position from an attack on the person who raised the proposal.", "Sim, e precisamos preservar divergência real. Tornar a comunicação confortável não significa transformar objeção firme em sugestão leve para parecer harmonia. Podemos reformular, confirmar fidelidade e separar posição de ataque pessoal ao proponente."],
        ["sparky", "I'll revise the facilitator notes accordingly. We'll offer the agenda and key terms in advance, invite preferred names, make turn-taking explicit and summarise decisions in writing. Where someone asks for a particular adjustment, we'll discuss it directly rather than announcing that it is what people from their background normally require.", "Revisarei as notas: pauta e termos antes, nomes preferidos, turnos claros e decisões escritas. Se alguém pedir ajuste, discutiremos diretamente, sem anunciar que é o que pessoas de sua origem normalmente precisam."],
        ["pinky", "That makes international communication a shared design responsibility, not a performance of cultural expertise. We can remain curious about conventions while being corrigible about our assumptions. The most convincing evidence of adaptation will be whether people can contribute, challenge a point and recognise the final record as an accurate account of what they meant.", "Isso torna a comunicação internacional responsabilidade de organização compartilhada, não demonstração de suposto domínio cultural. Podemos ter curiosidade e corrigir pressupostos. A melhor evidência será participação, possibilidade de contestar e reconhecimento do registro como fiel ao que quiseram dizer."]
      ], gist: ["What approach replaces nationality-based style matching?", "Shared communication design responsive to expressed preferences and observed needs", "Accent imitation as proof of respect for each participant", "Removing all complex ideas from the workshop", "O foco passa de categorias presumidas para condições concretas de participação e preferências expressas."],
      detail: ["Which clarification prompt does Pinky suggest?", "Which part needs a clearer example?", "Why don't people from your country answer faster?", "Do you agree with everything we have said?", "O pedido de exemplo torna o esclarecimento específico e reduz o custo social de admitir dificuldade."],
      inference: ["Why should written contributions be available to everyone?", "To avoid assigning needs or confidence levels on the basis of assumed identity", "To ensure nobody ever contributes orally", "To hide disagreement from the facilitator", "A disponibilidade universal permite escolha sem rotular participantes antecipadamente."],
      mediation: "Crie em português uma orientação de 150–190 palavras para facilitadores. Preserve complexidade, opções de participação e desacordo real. Substitua duas recomendações baseadas em nacionalidade por ações verificáveis, sem afirmar que cultura nunca influencia comunicação."
    }), rule: "Acomodação linguística adapta explicitação, ritmo, referência e organização à interação. Não exige imitar sotaques nem pressupor necessidades por identidade. Preserve o grau de discordância ao reformular: um resumo agradável mas infiel prejudica a participação. Corrigible significa disposto a revisar a própria interpretação diante da resposta do interlocutor.",
      example: "Clarifying the reference need not mean simplifying the idea itself.", translation: "Esclarecer a referência não precisa significar simplificar a própria ideia.",
      vocabulary: "patronising — condescendente\nsignpost — sinalizar a organização do discurso\ncorrigible — passível de correção; aberto a rever pressupostos",
      pitfall: "Desconhecer uma sigla local não indica baixa capacidade intelectual ou linguística. Explique a referência antes de reduzir a complexidade da ideia.",
      gap: "Accommodation should respond to expressed needs rather than ___ them from nationality.", fills: ["infer", "inferring to", "to inferred"], gapExplanation: "Rather than liga os verbos coordenados respond e infer sob should; o contraste é entre responder a necessidades e presumir sua existência.",
      production: "Escreva 300–350 palavras de guia para um workshop internacional. Proponha preparação, turnos, esclarecimento, manejo de discordância e confirmação final. Inclua dois exemplos de fala do facilitador e explique como poderão ser corrigidos pelo participante.",
      speakingTask: "Facilite uma troca de três minutos em que alguém contesta firmemente uma proposta. Reformule sem suavizar a posição, confirme fidelidade e responda a You're making this too complicated, defendendo clareza de acesso sem prometer eliminar diferenças."
    }),
    listeningLesson({ id: "c2-intercultural-06", title: "Projeto: negociar uma mensagem entre públicos", listening: conversation({
      id: "c2-intercultural-project", title: "Projeto: negociar uma mensagem entre públicos", level: "C2", context,
      scene: "Two editors prepare versions of a partnership announcement for a familiar local team and a wider international network. They negotiate precise wording after an initially celebratory draft.",
      turns: [
        ["pinky", "The local team's announcement says we've finally got our international partners on board and can stop going round in circles. It captures the relief people feel after months of meetings, but it could sound quite different to the partners themselves. They approved a limited pilot, not every part of the programme, and they may not see the earlier discussions as pointless delay.", "O anúncio diz que finalmente conseguimos trazer os parceiros internacionais a bordo e parar de andar em círculos. Reflete alívio após meses de reuniões, mas pode soar diferente aos parceiros. Eles aprovaram um piloto limitado, não o programa inteiro, e talvez não considerem as discussões perda de tempo."],
        ["sparky", "The phrase got them on board also places our team at the centre of the story and the partners in the role of people persuaded to join it. Was the pilot actually co-designed? If so, the wording underplays their contribution as well as overstating the scope of agreement. We need to distinguish celebration from ownership of the process.", "Conseguimos trazê-los a bordo coloca nossa equipe no centro e os parceiros como convencidos a aderir. O piloto foi concebido em conjunto? Se foi, a frase minimiza sua contribuição e amplia o acordo. Devemos separar celebração e autoria do processo."],
        ["pinky", "It was co-designed. Their accessibility requirements changed the delivery format, and their local coordinators helped identify a realistic schedule. The agreement covers two trial sessions and a joint review before any extension. There is no commitment to fund a full programme yet. Those aren't minor qualifications; they define what has actually been agreed.", "Foi conjunto. Requisitos de acessibilidade mudaram a entrega, e coordenadores locais ajudaram no cronograma. O acordo cobre duas sessões de teste e revisão conjunta antes de ampliar. Não há compromisso de financiar o programa inteiro. Isso define o acordo, não são ressalvas menores."],
        ["sparky", "Then both versions should preserve those limits, even if their tone differs. For the local team, we can acknowledge the work and relief without casting consultation as an obstacle overcome. For the wider network, name the co-design process, the two sessions and the review point. Readers should not need access to private meeting notes to discover that the announcement is conditional.", "As duas versões devem preservar limites, mesmo com tons diferentes. Para a equipe, reconhecemos trabalho e alívio sem tratar consulta como obstáculo vencido. Para a rede, nomeamos concepção conjunta, duas sessões e revisão. O caráter condicionado não deve exigir acesso a atas privadas."],
        ["pinky", "I'm considering: After several rounds of joint planning, the teams have agreed to test an accessible workshop format in two sessions, followed by a shared review. That is accurate, but it loses the sense that this was difficult and worth celebrating. Can we retain some warmth without sliding back into a victory narrative in which one side finally gave way?", "Penso em: Após planejamento conjunto, as equipes aceitaram testar um formato acessível em duas sessões, seguido de revisão compartilhada. É fiel, mas perde o esforço e a celebração. Podemos manter calor sem voltar à narrativa de vitória em que um lado cedeu?"],
        ["sparky", "Add a sentence thanking everyone for the careful work that made the pilot possible, and say what opportunity it creates for participants. That locates the positive meaning in collaboration and a concrete next step. We don't need to invent frictionless agreement, but neither do we need to turn the announcement into a dramatic account of who resisted whom.", "Acrescente agradecimento pelo trabalho cuidadoso que tornou o piloto possível e a oportunidade aos participantes. O positivo fica na colaboração e no passo concreto. Não precisamos inventar acordo sem atritos nem dramatizar quem resistiu a quem."],
        ["pinky", "I'll send both drafts to the partner coordinator for a factual and representational check. I'll make clear that we're asking whether the scope and contributions are portrayed fairly, not asking her to endorse every expression of enthusiasm in our internal message. If she proposes a correction, we'll record the agreed wording before either version is circulated.", "Enviarei os dois rascunhos à coordenadora para conferir fatos e representação. Perguntarei se escopo e contribuições são retratados com justiça, não se endossa toda manifestação de entusiasmo interno. Se corrigir, registraremos a formulação acordada antes de circular."],
        ["sparky", "Good. The two audiences can receive different levels of background and different degrees of familiarity while receiving the same commitments. That's the test of the adaptation: if someone compared the versions, would they find a change in register or a change in reality? We should be able to defend the former without having quietly introduced the latter.", "Ótimo. Públicos podem receber contexto e familiaridade diferentes, mas os mesmos compromissos. O teste é comparar: mudou o registro ou mudou a realidade? Devemos defender a primeira mudança sem introduzir silenciosamente a segunda."]
      ], gist: ["What must remain invariant across the two announcements?", "The actual commitments, contributions and conditions of the pilot", "Every idiom and degree of familiarity in the original draft", "The local team's portrayal of the partners as reluctant followers", "Registro e contexto podem variar; escopo, autoria e condições não podem virar fatos diferentes."],
      detail: ["What does the agreement currently cover?", "Two trial sessions and a joint review before any extension", "A fully funded permanent programme with no further review", "One private meeting with no sessions for participants", "O acordo é um piloto de duas sessões com revisão conjunta; financiamento integral não foi assumido."],
      inference: ["Why is got our partners on board potentially misleading?", "It can minimise co-design while implying broader alignment than was agreed", "It necessarily means that the partners travelled by ship", "It states the accessibility requirements in full detail", "A expressão organiza autoria e adesão de modo assimétrico e pode sugerir aprovação mais abrangente."],
      mediation: "Produza duas versões em português: informe interno de 100–130 palavras e anúncio à rede de 120–150. Varie registro e contexto, mantendo os mesmos compromissos, contribuição dos parceiros e condição de revisão. Acrescente uma verificação comparativa de três frases."
    }), rule: "Uma adaptação entre públicos pode variar tom, explicação e familiaridade, mas deve manter compromissos e condições. Metáforas de adesão e vitória também distribuem autoria e agência. Compare versões para detectar mudanças de realidade disfarçadas de estilo. Antes de publicar, uma conferência de representação verifica se as partes reconhecem seu papel e o acordo.",
      example: "The register may change; the scope of the commitment must remain consistent.", translation: "O registro pode mudar; o alcance do compromisso deve permanecer consistente.",
      vocabulary: "co-design — concepção conjunta\ngive way — ceder\nrepresentational check — conferência de como pessoas e contribuições são retratadas",
      pitfall: "Excluir a revisão posterior numa versão mais curta faz o piloto parecer adoção permanente. Condições centrais não são detalhes opcionais de edição.",
      gap: "Any extension is subject ___ a joint review of the two trial sessions.", fills: ["to", "for", "on to"], gapExplanation: "Subject to introduz a condição necessária; a revisão conjunta antecede eventual extensão.",
      production: "Escreva 320–370 palavras com dois anúncios em inglês para públicos distintos e uma nota comparativa. Mantenha escopo e autoria, varie registro e justifique uma metáfora retirada. Inclua uma pergunta aos parceiros para verificar representação sem exigir aprovação de sentimentos pessoais.",
      speakingTask: "Apresente o acordo por três minutos a um novo parceiro. Responda a So you've secured funding for the whole programme?, corrija o alcance e mantenha o significado positivo do avanço real. Depois adapte a explicação para um colega que participou das reuniões."
    })
  ]
}];
