import type { ModuleDraft } from "./types";
import { conversation, listeningLesson } from "./listening-authoring.ts";
const context = "Extended C2 adult conversation at a measured natural 135–145 words per minute. Sparky/Achird: warm lower-middle pitch, thoughtful confidence. Pinky/Zephyr: clear, warm higher-middle pitch. Preserve every scripted word; use subtle contrastive emphasis and purposeful pauses during reformulation. No music, sound effects, audience, caricature or overlapping speech. Challenges are firm and civil, never shouted.";

export const c2PrecisionModules: ModuleDraft[] = [{
  id: "c2-precision", title: "Fluência e intervenção precisa", level: "C2", prerequisiteId: "c2-intercultural",
  description: "Responder sob pressão, corrigir com diplomacia, reformular distinções e sustentar uma posição revisável em negociações extensas.",
  lessons: [
    listeningLesson({ id: "c2-precision-01", title: "Improvisar com uma estrutura que se sustenta", listening: conversation({
      id: "c2-improvised-response", title: "Improvisar com uma estrutura que se sustenta", level: "C2", context,
      scene: "Pinky rehearses an unexpected audience question with Sparky after a talk about community learning. Sparky structures an unscripted response and revises it when a counterexample appears.",
      turns: [
        ["pinky", "Let me put you on the spot with a question that wasn't in your presentation: if online courses can reach so many people, why should a neighbourhood spend money on a physical learning centre? You have about a minute for the initial response. I don't expect a perfect speech, but I do want an answer to that question rather than a tour of everything you know.", "Vou fazer uma pergunta inesperada: se cursos on-line alcançam tanta gente, por que o bairro financiaria um centro físico? Você tem cerca de um minuto. Não espero discurso perfeito, mas resposta à pergunta, não um passeio por tudo que sabe."],
        ["sparky", "I'd distinguish reach from effective participation. An online course may be available to thousands while still being hard to use for someone without a quiet room, reliable connectivity or occasional face-to-face support. A physical centre can address some of those barriers. That isn't an argument for a building regardless of cost; it's an argument for comparing what each option enables for the people the programme is meant to serve.", "Eu distinguiria alcance e participação efetiva. Um curso disponível a milhares pode ser difícil para quem não tem silêncio, conexão confiável ou apoio presencial ocasional. Um centro pode tratar dessas barreiras. Isso não defende um prédio a qualquer custo; pede comparar o que cada opção possibilita ao público-alvo."],
        ["pinky", "That gives me a distinction, but it risks sounding as though online learning necessarily leaves people isolated. Some online programmes have excellent peer support, loan equipment and live advice. If that were true of the available programme, what would remain of your case for the centre? Try not to defend a weaker version of the alternative just because it's easier to answer.", "A distinção ajuda, mas pode parecer que o on-line necessariamente isola. Alguns programas têm apoio entre pares, equipamento e orientação ao vivo. Se fosse assim, o que restaria da defesa do centro? Evite defender uma versão fraca da alternativa por ser mais fácil."],
        ["sparky", "Fair challenge. I should have said that those barriers depend on the actual provision, not the medium alone. If the online programme already addresses them effectively, the case for a separate centre becomes narrower. It might still provide a usable study space or access for particular groups, but we'd need evidence of that additional benefit before committing to a substantial recurring cost.", "Justo. Deveria ter dito que as barreiras dependem da oferta concreta, não só do meio. Se o programa já as resolve, a justificativa do centro se estreita. Pode oferecer espaço ou acesso a certos grupos, mas precisaríamos demonstrar benefício adicional antes de assumir custo recorrente significativo."],
        ["pinky", "I noticed you corrected the premise without abandoning the whole answer. That sounded more convincing than pretending the counterexample didn't matter. What structure were you using? Your response had a clear direction, but it didn't feel like you were forcing the question into a memorised introduction, three points and a conclusion regardless of relevance.", "Você corrigiu a premissa sem abandonar tudo; convenceu mais que ignorar o contraexemplo. Qual estrutura usou? Havia direção, mas não parecia encaixar a pergunta à força numa introdução, três pontos e conclusão decorados."],
        ["sparky", "I started with the decision the question implied, chose one distinction that mattered and gave a conditional consequence. When you challenged the example, I kept the decision criterion and revised the scope of the claim. That gave me somewhere to go without needing to invent a statistic or list every possible benefit of a community building.", "Comecei pela decisão implícita, escolhi uma distinção relevante e dei uma consequência condicionada. Ao contestar o exemplo, mantive o critério e revi o alcance. Assim pude avançar sem inventar estatísticas ou listar todos os benefícios possíveis de um prédio comunitário."],
        ["pinky", "Would a brief pause before answering have weakened the impression of fluency? People sometimes fill the first seconds with phrases like That's a fascinating and enormously complex question. If the same opening appears regardless of the question, it can start to sound like a device for avoiding commitment rather than taking useful thinking time.", "Uma pausa breve prejudicaria a impressão de fluência? Às vezes preenchem os primeiros segundos dizendo que a pergunta é fascinante e enormemente complexa. Repetido sempre, pode soar como fuga, não tempo útil de reflexão."],
        ["sparky", "A short pause would have been fine. Fluency should let the listener follow the response, not prevent the speaker from thinking. If I need to clarify the decision, I can ask a specific question. If I understand it, I should answer directly, qualify what needs qualification and stop once I've given the listener a usable basis for the next turn.", "Uma pausa curta seria aceitável. Fluência deve permitir acompanhar a resposta, não impedir pensar. Se preciso esclarecer a decisão, faço uma pergunta específica. Se entendo, respondo, qualifico o necessário e paro ao oferecer base útil para o próximo turno."]
      ], gist: ["What makes the improvised response effective?", "A relevant decision criterion survives while an overbroad premise is revised", "A fixed speech is delivered without responding to the counterexample", "Every possible advantage is listed to avoid taking a position", "Sparky mantém uma estrutura pertinente e ajusta a premissa à objeção real."],
      detail: ["What does Sparky say would narrow the case for a separate centre?", "An online programme that already addresses the identified barriers effectively", "The mere existence of any website with course listings", "A guarantee that physical centres never have recurring costs", "O contraexemplo descreve uma oferta concreta que já resolve barreiras, não apenas presença digital."],
      inference: ["Why does Pinky question the repeated elaborate opening?", "It may consume thinking time without advancing the specific answer", "All acknowledgement of a question is inherently dishonest", "A fluent response must begin instantly with no pause", "A crítica é à fórmula vazia e repetida; o diálogo aceita pausa breve e esclarecimento específico."],
      mediation: "Explique em português, em 140–180 palavras, a posição final de Sparky a alguém que só ouviu a pergunta inicial. Preserve o contraexemplo, o critério decisório e a necessidade de evidência adicional, sem convertê-lo em defensor incondicional de qualquer modalidade."
    }), rule: "Improvisação avançada combina seleção e revisabilidade. Responda à decisão implícita, escolha uma distinção funcional e explicite a consequência. Ao receber um contraexemplo, ajuste o alcance em vez de repetir a afirmação. Fluência inclui pausas úteis, reparos e encerramento proporcional; velocidade e quantidade de palavras não substituem pertinência.",
      example: "If those barriers are already addressed, the case for a separate centre narrows.", translation: "Se essas barreiras já são tratadas, a justificativa para um centro separado se estreita.",
      vocabulary: "put someone on the spot — pedir resposta imediata sob pressão\nrecurring cost — custo recorrente\ncounterexample — caso que contesta uma generalização",
      pitfall: "Corrigir uma premissa não exige abandonar o critério válido que orienta a resposta. Diferencie revisão do argumento e mudança arbitrária de assunto.",
      gap: "The need depends on actual provision, not on the medium ___ .", fills: ["alone", "lonely", "only of"], gapExplanation: "Alone após o substantivo significa por si só; lonely descreve solidão e muda a estrutura e o sentido.",
      production: "Escreva 290–340 palavras com uma resposta inicial de até 100 palavras, um contraexemplo e uma réplica revisada. Comente o que manteve e o que alterou. Use critérios explícitos e não invente números para dar aparência de autoridade.",
      speakingTask: "Responda sem roteiro por um minuto: Should a neighbourhood fund a physical learning centre? Em seguida, considere um programa on-line que já oferece apoio completo e responda por mais dois minutos, ajustando o argumento. Uma pausa breve de planejamento é permitida."
    }),
    listeningLesson({ id: "c2-precision-02", title: "Uma pergunta hostil com uma questão legítima", listening: conversation({
      id: "c2-hostile-question", title: "Uma pergunta hostil com uma questão legítima", level: "C2", context,
      scene: "A rehearsal for a public question session. Pinky voices a sceptical question firmly but without aggression; Sparky separates its loaded premise from a legitimate request for accountability.",
      turns: [
        ["pinky", "Here's a difficult question for your rehearsal: why are you wasting residents' money on another fashionable pilot when the last project achieved nothing? The wording is deliberately loaded, but there may be a legitimate concern underneath it. Try to respond without accepting the whole premise and without using the hostile tone as an excuse to ignore the spending question.", "Uma pergunta difícil: por que desperdiça dinheiro dos moradores em outro piloto da moda se o anterior não deu resultado algum? A formulação é carregada, mas pode haver uma preocupação legítima. Responda sem aceitar toda a premissa nem usar o tom para ignorar o gasto."],
        ["sparky", "Residents are entitled to know what the money is expected to achieve and how we'll judge the result. I wouldn't describe the previous project as achieving nothing: it delivered the scheduled sessions, though we didn't establish the longer-term outcome we'd hoped to measure. For this proposal, the budget, decision criteria and reporting date need to be explicit before spending begins.", "Moradores têm direito de saber o resultado esperado e como será julgado. Eu não diria que o anterior nada alcançou: entregou sessões, embora não estabelecesse o resultado duradouro que pretendíamos medir. Nesta proposta, orçamento, critérios e data de relatório precisam ser explícitos antes dos gastos."],
        ["pinky", "That corrects the absolute claim, but a sceptic could say you're hiding behind a distinction between delivering activity and producing value. If the longer-term outcome wasn't measured, how can residents tell whether another pilot is a sensible use of money? Don't answer only the inaccurate part of my question and leave the stronger challenge untouched.", "Você corrige o absoluto, mas alguém pode dizer que se esconde na distinção entre atividade e valor. Sem medir o efeito duradouro, como saber se outro piloto é sensato? Não responda só à parte inexata deixando a objeção mais forte intacta."],
        ["sparky", "That's the stronger challenge, and it's fair. Delivering sessions isn't sufficient evidence of value on its own. The new proposal should identify the unresolved question, explain why the chosen method can answer it and specify the maximum cost of finding out. If it cannot do those things convincingly, I wouldn't recommend approving it merely because the idea sounds promising.", "Essa é a objeção mais forte e é justa. Entregar sessões não basta para demonstrar valor. A proposta deve identificar a questão aberta, explicar como o método pode respondê-la e limitar o custo de descobrir. Se não fizer isso de forma convincente, não recomendo aprovar só porque parece promissora."],
        ["pinky", "Would you acknowledge frustration directly? Some public replies sound technically precise but emotionally untouched by the fact that people were promised an answer and didn't receive it. On the other hand, apologising for wasting money would adopt a conclusion you haven't established. There's a narrow path between those two unhelpful responses.", "Reconheceria frustração diretamente? Algumas respostas são precisas, mas ignoram que prometeram uma resposta não entregue. Por outro lado, desculpar-se por desperdiçar dinheiro aceitaria uma conclusão não estabelecida. Há um caminho entre essas duas respostas ruins."],
        ["sparky", "I'd say it is reasonable to be frustrated that the promised evaluation wasn't completed, and explain who is responsible for correcting that gap. I can apologise for a missed reporting commitment if it is ours. That differs from asserting that every part of the expenditure was worthless. The acknowledgement should name the actual failure and the remedy, not become a vague performance of regret.", "Diria ser razoável frustrar-se com a avaliação prometida e incompleta e explicaria a responsabilidade por corrigir a lacuna. Posso pedir desculpas pelo compromisso de relatório descumprido se era nosso. Isso não afirma que toda despesa foi inútil. O reconhecimento deve nomear falha real e reparo, não encenar arrependimento vago."],
        ["pinky", "And if the questioner interrupts with So you admit it was a waste? You won't have much time for a long distinction. You need a short reply that keeps the record accurate while leaving the discussion open. Repeating the entire explanation could sound evasive even if every sentence is defensible in isolation.", "E se interromperem: Então admite desperdício? Não haverá tempo para uma distinção longa. Precisa manter o registro fiel e a discussão aberta. Repetir tudo pode soar evasivo, mesmo com frases individualmente defensáveis."],
        ["sparky", "I'd answer, I accept that we failed to deliver the promised evaluation; that does not establish that all expenditure was wasted. Here is what we'll publish to let residents assess it. Then I'd give the concrete next step. The aim isn't to win a verbal contest. It's to answer the accountability question without letting an unsupported premise become the agreed starting point.", "Eu diria: Reconheço que não entregamos a avaliação prometida; isso não estabelece que toda despesa foi desperdiçada. Eis o que publicaremos para permitir julgamento. Depois, a ação concreta. O objetivo não é vencer verbalmente, mas prestar contas sem converter premissa sem apoio em ponto de partida aceito."]
      ], gist: ["What response strategy do they refine?", "Correct unsupported premises while answering the substantive accountability concern", "Dismiss all criticism because the initial question sounds hostile", "Admit total waste to end the exchange quickly", "Precisão e prestação de contas precisam coexistir; corrigir o exagero não elimina a pergunta legítima."],
      detail: ["What failure is explicitly acknowledged in the rehearsal?", "The promised evaluation was not delivered", "No scheduled session ever took place", "Every expense was proven to have no value", "O diálogo distingue relatório/avaliação não entregue de ausência total de atividade ou valor."],
      inference: ["Why does Pinky challenge the distinction between activity and value?", "Correcting one exaggeration is not enough to justify the proposed spending", "She wants all distinctions removed from public discussion", "She believes delivering sessions proves every long-term benefit", "Ela exige resposta ao argumento mais forte, não apenas ao trecho mais fácil de refutar."],
      mediation: "Faça em português um registro de 150–190 palavras para moradores: separe alegação contestada, falha admitida e requisitos para novo gasto. Não invente um orçamento ou data que não foi informado. Preserve a preocupação legítima sem repetir a acusação como fato."
    }), rule: "Uma pergunta carregada incorpora premissas discutíveis. Separe a preocupação legítima da conclusão embutida, corrija esta brevemente e responda àquela. Reconhecer uma falha específica não confirma todo rótulo associado a ela. Uma réplica precisa mantém responsabilidade concreta e não se limita a explorar o exagero mais fácil da pergunta.",
      example: "I accept the reporting failure; that does not establish that all expenditure was wasted.", translation: "Reconheço a falha no relatório; isso não demonstra que toda a despesa foi desperdiçada.",
      vocabulary: "loaded premise — premissa carregada/que embute conclusão\naccountability — prestação de contas e responsabilização\nremedy — ação de reparação",
      pitfall: "Responder apenas a achieved nothing pode deixar sem resposta a questão sobre valor e gasto futuro. A precisão lexical precisa servir à pergunta substantiva.",
      gap: "Delivering the sessions does not, ___ itself, establish their long-term value.", fills: ["in", "at", "onto"], gapExplanation: "In itself delimita o que uma evidência demonstra por si só; não nega que as sessões ocorreram.",
      production: "Escreva uma resposta pública de 300–350 palavras com reconhecimento específico, correção de premissa, argumento principal e ação verificável. Depois reduza a resposta a uma réplica de até 40 palavras que preserve a distinção central; conte ambas no limite total.",
      speakingTask: "Responda à pergunta hostil em dois minutos. Em seguida, responda em até 30 segundos a So you admit it was a waste? Mantenha tom civil, admissão específica e próximo passo, sem atacar a intenção de quem perguntou."
    }),
    listeningLesson({ id: "c2-precision-03", title: "Corrigir em público sem transformar em disputa pessoal", listening: conversation({
      id: "c2-diplomatic-correction", title: "Corrigir em público sem transformar em disputa pessoal", level: "C2", context,
      scene: "Two colleagues rehearse correcting a misleading chart explanation during a committee meeting. Their tone is precise, calm and attentive to the audience's decision.",
      turns: [
        ["sparky", "During the rehearsal, the chair said that applications had doubled after the new outreach campaign. The chart actually shows enquiries rising from forty to eighty; completed applications rose from twenty to twenty-four. I need to correct the distinction before the committee makes a funding decision, but I don't want the intervention to sound like a public demonstration that I know the figures better.", "No ensaio, o presidente disse que as candidaturas dobraram após a campanha. O gráfico mostra consultas de quarenta para oitenta; candidaturas completas foram de vinte para vinte e quatro. Preciso corrigir antes da decisão, sem parecer demonstração pública de superioridade."],
        ["pinky", "Anchor the correction in the decision and the source, not in the chair's competence. Could I clarify which measure doubled? The chart shows enquiries, whereas completed applications increased more modestly. That gives the audience the relevant distinction immediately. You can then explain why it matters for judging the campaign without speculating about how the chair made the mistake.", "Vincule a correção à decisão e à fonte, não à competência pessoal. Posso esclarecer qual medida dobrou? O gráfico mostra consultas; candidaturas cresceram menos. A distinção chega imediatamente. Depois explique sua relevância, sem especular sobre a origem do erro."],
        ["sparky", "Would Could I clarify soften it so much that it sounds optional? There are situations where a gentle opening becomes an invitation to ignore the correction. The chair might say the broader point still stands and move on, leaving people with the original number in their notes. I need to be civil without allowing the factual correction to dissolve.", "Posso esclarecer suaviza a ponto de parecer opcional? Às vezes uma abertura gentil permite ignorar a correção. O presidente pode dizer que o argumento geral continua e seguir, deixando o número original nas notas. Preciso ser civil sem dissolver a correção factual."],
        ["pinky", "Then follow the opening with an unambiguous statement: enquiries doubled; completed applications did not. The softer entry manages the turn, while the statement carries the correction. If necessary, ask that the distinction be reflected in the minutes. Politeness should affect how you enter the exchange, not whether the evidence is allowed to retain its actual meaning.", "Então siga com afirmação inequívoca: consultas dobraram; candidaturas completas não. A abertura organiza o turno; a afirmação corrige. Se necessário, peça registro em ata. Educação deve orientar a entrada na conversa, não determinar se a evidência mantém seu significado."],
        ["sparky", "There's also the word after. The campaign began before the increase, but the chart alone doesn't show that it caused it. A new application deadline and a separate information event happened in the same period. Should I raise that immediately as well, or would stacking corrections make the intervention harder to follow?", "Há também after. A campanha veio antes, mas o gráfico não prova causa. Mudança de prazo e outro evento informativo ocorreram no período. Devo levantar isso já ou acumular correções dificultaria acompanhar?"],
        ["pinky", "I'd make the distinction between the two corrections explicit. First, a factual point about the measure: enquiries doubled. Second, a limitation on explanation: the timing doesn't isolate the campaign's effect. They are connected, but they have different evidential status. We can be certain about what the chart labels while remaining uncertain about the cause of the observed change.", "Eu distinguiria explicitamente. Primeiro, fato sobre a medida: consultas dobraram. Segundo, limite de explicação: o período não isola o efeito da campanha. São relacionados, mas com estatutos de evidência diferentes. Podemos ter certeza sobre o rótulo e incerteza sobre a causa."],
        ["sparky", "If the chair accepts the correction, I should probably stop rather than keep elaborating until it feels like a rebuke. I could say that the figures still warrant investigation and suggest what additional information would help. That moves the committee back to the decision instead of keeping attention on the mistake and the person who made it.", "Se aceitar, devo parar, sem elaborar até parecer reprimenda. Posso dizer que os dados merecem investigação e sugerir informação adicional. Isso devolve o foco à decisão, não ao erro e à pessoa."],
        ["pinky", "Exactly. A successful intervention changes the shared record and improves the decision. It doesn't need to secure a prolonged acknowledgement of your correctness. Be firm about the measure, calibrated about the causal claim and brief once the repair has been accepted. That combination protects both the accuracy of the discussion and the possibility of continuing it productively.", "Exato. Uma intervenção bem-sucedida muda o registro e melhora a decisão, sem exigir reconhecimento prolongado de que você tinha razão. Seja firme sobre a medida, proporcional sobre causa e breve após o reparo aceito. Assim preserva precisão e continuidade produtiva."]
      ], gist: ["What does an effective public correction prioritise?", "An accurate shared record and a better decision, with clear distinctions and proportionate delivery", "A prolonged public admission that the chair is incompetent", "Soft wording that leaves the incorrect measure unchanged", "A intervenção serve ao registro e à decisão, não à superioridade pessoal nem à evasão do erro."],
      detail: ["What happened to completed applications?", "They rose from twenty to twenty-four", "They doubled from forty to eighty", "They fell from twenty-four to twenty", "Consultas dobraram; candidaturas completas passaram de 20 para 24."],
      inference: ["Why separate the measure correction from the causal limitation?", "One is established by the chart, while the other concerns what the chart cannot explain", "Both points are equally uncertain guesses about the chair", "A correct label proves that the campaign caused the change", "O grau de certeza difere: o rótulo é verificável; a atribuição causal não foi isolada."],
      mediation: "Escreva em português uma correção de ata de 140–180 palavras. Preserve valores e medidas, distinga cronologia e causa e indique a decisão que precisa de informação adicional. Não atribua má-fé ou incompetência ao presidente."
    }), rule: "Uma abertura mitigada pode organizar o turno sem enfraquecer uma correção factual. Separe a entrada diplomática da afirmação inequívoca e calibre a certeza de cada ponto. After marca sequência, não prova causalidade. Depois de uma correção aceita, encerre o reparo e retome a finalidade da discussão, evitando convertê-lo em reprimenda.",
      example: "Enquiries doubled; completed applications did not.", translation: "As consultas dobraram; as candidaturas completas não.",
      vocabulary: "rebuke — reprimenda\nminutes — ata de reunião\nevidential status — grau e natureza do apoio em evidência",
      pitfall: "Suavizar o turno não precisa tornar a correção vaga. It might possibly be a slightly different number enfraqueceria um fato diretamente verificável no gráfico.",
      gap: "The chart establishes the increase, ___ it does not isolate its cause.", fills: ["but", "because of", "despite of"], gapExplanation: "But contrasta o que a evidência mostra com o que ela não permite concluir.",
      production: "Escreva 300–350 palavras com uma intervenção para a reunião e uma nota de ata. Diferencie duas correções, explique relevância para o financiamento e proponha evidência adicional. Inclua uma frase de encerramento após o presidente aceitar a correção.",
      speakingTask: "Corrija a afirmação Applications doubled because of the campaign em até um minuto. Responda a That's just a technical detail por mais dois minutos, explicando o impacto na decisão e encerrando quando o interlocutor aceitar o reparo."
    }),
    listeningLesson({ id: "c2-precision-04", title: "Reformular preservando a condição decisiva", listening: conversation({
      id: "c2-precise-reformulation", title: "Reformular preservando a condição decisiva", level: "C2", context,
      scene: "At a railway information desk, Pinky explains a fictional disruption policy to Sparky. He tests the wording against his itinerary, revealing why a short paraphrase can become misleading.",
      turns: [
        ["pinky", "Because the coastal line is closed this afternoon, passengers whose final destination lies beyond Riverton may use the replacement coach from the east entrance. Your rail ticket will be accepted on that service. Passengers travelling only as far as Riverton should use the local shuttle, which departs from the station forecourt. I realise the two options sound similar, so let's check your destination before I direct you.", "A linha costeira está fechada nesta tarde. Quem vai além de Riverton pode usar o ônibus substituto na entrada leste, com o bilhete de trem. Quem vai só até Riverton deve usar o transporte local na frente da estação. As opções parecem semelhantes; vamos conferir seu destino antes de orientar."],
        ["sparky", "I'm travelling to Bellhaven, beyond Riverton, but I arranged to meet my cousin in Riverton on the way. I was about to tell her that our tickets work on either bus. From what you've just said, that would be too broad. Does the replacement coach stop in Riverton, or does it bypass the town entirely?", "Vou a Bellhaven, além de Riverton, mas combinara encontrar minha prima em Riverton. Ia dizer que o bilhete vale em qualquer ônibus, o que seria amplo demais. O substituto para em Riverton ou passa direto?"],
        ["pinky", "It stops at Riverton's coach interchange, not at the railway station. That is about a fifteen-minute walk from the meeting point most people expect when they say the station. The ticket acceptance depends on using the replacement service for your disrupted rail journey; it isn't a general permission to use any local bus for additional travel around town.", "Para no terminal rodoviário de Riverton, não na estação ferroviária, cerca de quinze minutos a pé do ponto que as pessoas imaginam ao dizer estação. A aceitação vale para o serviço substituto da viagem interrompida, não para qualquer ônibus em deslocamentos adicionais."],
        ["sparky", "So a useful message to my cousin would be: I'm taking the replacement coach to the Riverton interchange, which is different from the railway station; please meet me there. Before I send that, can I actually get off and continue to Bellhaven later on the same ticket, or would I be assuming another condition that hasn't been established?", "Então posso dizer: Vou no substituto ao terminal de Riverton, diferente da estação; encontre-me lá. Antes de enviar, posso descer e continuar a Bellhaven depois com o mesmo bilhete ou estaria presumindo outra condição?"],
        ["pinky", "Thank you for checking. The information we've received confirms ticket acceptance on the replacement journey, but it doesn't specify an optional break for a social visit. I can't reliably authorise that from this notice. I can ask the duty supervisor, or you can remain on the coach through to Bellhaven and arrange to meet your cousin another time.", "Obrigada por conferir. O aviso confirma aceitação no trajeto substituto, mas não especifica parada opcional para visita. Não posso autorizar com segurança a partir dele. Posso perguntar à supervisão ou você segue a Bellhaven e combina outro encontro."],
        ["sparky", "Please ask the supervisor. I have time before departure, and I'd prefer a confirmed answer to a convenient guess. While you do that, I'll tell my cousin the meeting is provisional and explain the interchange. I won't say that you've refused a stopover, because what you've actually said is that the notice doesn't settle it.", "Pergunte, por favor. Tenho tempo e prefiro confirmação a um palpite conveniente. Avisarei que o encontro é provisório e explicarei o terminal. Não direi que recusou a parada; você disse que o aviso não resolve a questão."],
        ["pinky", "Exactly. The distinction is between an option ruled out and an option awaiting confirmation. I'll also check the departure time of the next onward coach, because permission to break the journey would be of limited use if there were no later service to complete it. A valid ticket and a workable itinerary are related but separate questions.", "Exato: opção proibida é diferente de opção aguardando confirmação. Também verificarei a próxima saída, pois autorização para interromper pouco serviria sem transporte posterior. Bilhete válido e itinerário viável são questões relacionadas, mas distintas."],
        ["sparky", "Then my short version is: the rail disruption has a replacement coach, but our meeting place and any break in the journey need checking before I promise a visit. That is less reassuring than Everything is sorted, yet much more useful. It tells my cousin what she can act on now and what should remain open until you have the supervisor's answer.", "Minha versão curta: há ônibus substituto, mas local de encontro e parada na viagem precisam de confirmação antes de prometer a visita. É menos tranquilizador que Está tudo resolvido, mas mais útil: mostra o que ela pode fazer e o que segue aberto até a resposta da supervisão."]
      ], gist: ["What does their clarification establish?", "The replacement route is available, but a voluntary stopover and onward timing still require confirmation", "The ticket grants unlimited travel on every local bus", "The staff member has definitively prohibited all stops in Riverton", "O diálogo confirma parte do trajeto e preserva duas condições ainda abertas, sem transformar desconhecimento em proibição."],
      detail: ["Where does the replacement coach stop in Riverton?", "At the coach interchange rather than the railway station", "At the railway station forecourt only", "It bypasses Riverton without stopping", "A diferença de terminal é explícita e muda o lugar de encontro."],
      inference: ["Why does Pinky also check a later onward coach?", "Permission for a stopover would not by itself make the itinerary feasible", "She has already decided that the ticket is invalid everywhere", "A later coach would automatically remove every ticket condition", "A viabilidade depende de serviço disponível além da regra de bilhete."],
      mediation: "Escreva para a prima, em português, uma mensagem de 100–130 palavras e uma explicação de 60–80 palavras sobre o que você omitiu ou preservou. Distinga terminal, autorização de parada e próxima saída; não invente resposta da supervisão."
    }), rule: "Uma reformulação precisa mantém as condições que mudam a ação do destinatário. Accepted on this replacement service não equivale a valid on any bus. Awaiting confirmation difere de ruled out. No resumo funcional, priorize o que a pessoa pode fazer agora, o que precisa conferir e quem pode decidir, mesmo que a versão fique menos tranquilizadora.",
      example: "The notice leaves the stopover unresolved; it does not expressly rule it out.", translation: "O aviso deixa a parada sem solução; não a proíbe expressamente.",
      vocabulary: "forecourt — área em frente à estação\ncoach interchange — terminal de conexão de ônibus\nstopover — parada intermediária na viagem",
      pitfall: "Trocar não sei autorizar por foi proibido altera o estado da decisão. Preserve ausência de confirmação sem transformá-la em permissão ou negativa.",
      gap: "Ticket acceptance is confirmed, but the optional stopover remains ___ .", fills: ["unresolved", "unconditionally authorised", "definitively prohibited"], gapExplanation: "Unresolved preserva a lacuna que exige consulta; as outras alternativas inventam decisões opostas.",
      production: "Escreva 300–350 palavras contendo uma mensagem curta à prima e uma nota de orientação para outro passageiro com destino diferente. Compare o que pode ser reaproveitado e o que depende do itinerário. Marque explicitamente as informações ainda não confirmadas.",
      speakingTask: "Explique o trajeto em dois minutos e responda à réplica So I can take any bus and stop wherever I like? Repare as duas generalizações e formule a pergunta exata que ainda precisa ser respondida pela supervisão."
    }),
    listeningLesson({ id: "c2-precision-05", title: "Negociar um evento até um acordo executável", listening: conversation({
      id: "c2-extended-negotiation", title: "Negociar um evento até um acordo executável", level: "C2", context,
      scene: "At a community arts venue, Sparky represents a student film group and Pinky manages the space. They negotiate a screening with competing time, staffing and accessibility constraints.",
      turns: [
        ["sparky", "We'd like to book the hall for a student film screening next month. The programme lasts ninety minutes, and we want a discussion afterwards because the films raise questions that deserve more than a quick round of applause. Our preferred start is seven thirty, but I understand the venue normally closes at nine thirty. Is there room to negotiate that closing time?", "Queremos reservar o salão para filmes estudantis no mês que vem. A programação dura noventa minutos e queremos debate depois. Preferimos começar às sete e meia, mas sei que fecha às nove e meia. Há margem para negociar o encerramento?"],
        ["pinky", "The public event must finish at nine, with the remaining half-hour reserved for clearing the room and staff checks. Extending the public programme would require an additional staffing arrangement that I can't authorise within the standard hire. I can discuss options, but I don't want to imply that a later finish is available simply because the building's final closing time sounds flexible.", "O evento público deve acabar às nove; a meia hora restante é para limpeza e conferência. Estender exige equipe adicional que não posso autorizar na locação comum. Posso discutir opções, mas não quero sugerir que terminar mais tarde está disponível só porque o fechamento final parece flexível."],
        ["sparky", "Then starting at seven would give us thirty minutes for discussion, provided the screening runs on time. Some students travel from evening placements and might struggle to arrive before seven fifteen. We could shorten the film programme, but cutting the student contributions without consultation would undermine the reason we're holding the event. I'd like to preserve both access and a meaningful discussion.", "Começar às sete daria trinta minutos de debate se tudo correr no horário. Alguns vêm de estágios e talvez só cheguem às sete e quinze. Podemos encurtar, mas cortar trabalhos sem consulta prejudicaria a finalidade. Quero preservar acesso e debate significativo."],
        ["pinky", "Could the introductory material move online, with the films beginning at seven fifteen? That would leave fifteen minutes for discussion before nine. It wouldn't meet your original discussion length, so I'm offering it as a trade-off rather than pretending nothing is lost. Another option is a weekend afternoon, when the staffing window is longer, although I would need to check availability.", "A introdução pode ir on-line e os filmes começar às sete e quinze? Sobrariam quinze minutos de debate antes das nove. Não atende à duração original; é uma troca, não fingimento de que nada se perde. Outra opção é tarde de fim de semana, com janela maior, dependendo de disponibilidade."],
        ["sparky", "Fifteen minutes would probably become a token discussion once introductions and the first question are included. The weekend may work better, but two filmmakers have weekend jobs. What if we split the programme across two shorter weekday screenings, with a focused discussion each time? That changes the audience experience and possibly the cost, so we'd need to compare it against one afternoon event.", "Quinze minutos podem virar um debate simbólico, contando apresentação e primeira pergunta. Fim de semana talvez seja melhor, mas dois realizadores trabalham. E dividir em duas sessões menores durante a semana, com debate em cada? Isso muda experiência e custo; precisamos comparar com uma tarde única."],
        ["pinky", "Two bookings would involve two hire charges, so I wouldn't recommend assuming it is the cheaper option. I can hold one provisional weekday slot until Friday without taking a deposit. During that time, you can consult the filmmakers about a weekend and I can check the afternoon calendar and the cost of extended staffing. Then we can compare real options rather than hypothetical concessions.", "Duas reservas geram duas cobranças; não presumiria menor custo. Posso segurar provisoriamente um horário de semana até sexta, sem depósito. Você consulta realizadores sobre fim de semana, e eu verifico calendário e custo de equipe extra. Depois comparamos opções reais, não concessões hipotéticas."],
        ["sparky", "That gives us a workable next step. Before we settle the date, we also need to check caption display and wheelchair positions with a clear view of the screen. Those are conditions of the event, not extras we can discard if scheduling becomes difficult. I'll send the technical requirements today and ask the filmmakers for their availability by Thursday evening.", "Isso dá um próximo passo viável. Antes da data, precisamos conferir legendas e posições para cadeiras de rodas com visão da tela. São condições, não extras descartáveis por dificuldade de agenda. Envio requisitos hoje e peço disponibilidade até quinta à noite."],
        ["pinky", "I'll respond with the verified time and cost options by Friday morning, including whether the technical requirements can be met. The provisional hold is not a confirmed booking, and neither of us should advertise the event yet. If none of the options meets the essential conditions, we'll release the hold and look for another venue rather than silently reducing what participants were promised.", "Responderei com horários e custos verificados até sexta de manhã, incluindo requisitos técnicos. A reserva provisória não é confirmação, e não devemos anunciar ainda. Se nenhuma opção atender às condições essenciais, liberamos e buscamos outro local em vez de reduzir silenciosamente o prometido."]
      ], gist: ["What is the outcome of the negotiation?", "A provisional hold and assigned checks before a booking decision", "A confirmed late-night screening with all extra staffing already authorised", "An agreement to remove accessibility requirements to preserve the original date", "O avanço é um processo com responsáveis e prazo; ainda não há evento confirmado."],
      detail: ["When must the public event end under the standard hire?", "Nine o'clock, leaving thirty minutes for clearance and checks", "Nine thirty, followed by an unlimited discussion", "Seven fifteen, before any films can be shown", "Nove é o limite público; nove e meia é o fechamento após trabalho da equipe."],
      inference: ["Why does Sparky call fifteen minutes a token discussion?", "Procedural opening time could consume much of the opportunity for substantive exchange", "He believes audiences should never ask questions after films", "The venue has promised that fifteen minutes will cover every concern", "A preocupação é a diferença entre incluir nominalmente um debate e permitir troca significativa."],
      mediation: "Faça em português uma passagem de negociação de 150–190 palavras para outro organizador. Separe opções, custos não confirmados, responsabilidades, prazos e condições essenciais. Explique por que ainda não se pode anunciar o evento e quando a reserva provisória deve ser liberada."
    }), rule: "Negociações extensas avançam por propostas, condições, custos e verificações. Uma opção provisória não é concessão confirmada. Provided delimita uma condição; rather than pretending explicita uma perda real. Ao fechar, registre quem fará o quê, até quando e o que ocorre se requisitos essenciais não forem atendidos. Não use linguagem de acordo concluído para uma verificação pendente.",
      example: "The provisional hold gives us time to check options; it is not a confirmed booking.", translation: "A reserva provisória dá tempo para conferir opções; não é uma contratação confirmada.",
      vocabulary: "token discussion — debate apenas simbólico\nprovisional hold — retenção temporária de uma reserva\nhire charge — valor cobrado pela locação",
      pitfall: "Fechamento do prédio às 21h30 não significa programação pública até 21h30. A janela de limpeza e conferência é uma condição operacional explícita.",
      gap: "We can hold the slot until Friday ___ treating it as a confirmed booking.", fills: ["without", "despite of", "unless to"], gapExplanation: "Without + -ing preserva a diferença entre disponibilidade temporariamente retida e contrato confirmado.",
      production: "Escreva um e-mail de 320–370 palavras resumindo a negociação para ambas as partes. Compare três opções sem inventar preços, registre condições essenciais e atribua verificações. Inclua uma frase de decisão para o caso de nenhuma opção atender aos requisitos.",
      speakingTask: "Negocie por três minutos uma sessão com debate e horário limitado. Responda a Can't you just drop the accessibility checks and confirm now?, mantenha as condições e ofereça um próximo passo executável sem assumir autoridade que não possui."
    }),
    listeningLesson({ id: "c2-precision-06", title: "Projeto final: defender uma decisão que pode ser revista", listening: conversation({
      id: "c2-final-defence", title: "Projeto final: defender uma decisão que pode ser revista", level: "C2", context,
      scene: "A final discussion before a community committee recommendation. Sparky defends a bounded learning-space pilot; Pinky scrutinises opportunity costs, participation, evaluation and the possibility of ending it.",
      turns: [
        ["sparky", "My recommendation is a twelve-week evening study-space pilot using one room in the existing library, rather than leasing a separate building. The case rests on a specific unmet need reported by residents: access to a quiet workspace after daytime responsibilities. The proposal is deliberately limited. It tests whether that need translates into sustained use of this room under a staffing arrangement the library can actually maintain.", "Recomendo um piloto de doze semanas numa sala da biblioteca, sem alugar outro prédio. A justificativa é uma necessidade relatada: silêncio para estudar após responsabilidades diurnas. A proposta é limitada e testa se isso vira uso contínuo desta sala com equipe sustentável."],
        ["pinky", "You have explained why the idea may be useful, but the committee has other claims on the same funds. Why should this pilot take priority over improving daytime access or lending equipment? A proposal can be worthwhile in isolation and still be the weaker choice once opportunity costs are considered. I need a comparative argument, not simply a list of its potential benefits.", "Explicou utilidade possível, mas há outros usos do mesmo dinheiro. Por que priorizar isso sobre acesso diurno ou empréstimo de equipamentos? Algo pode valer isoladamente e ser opção inferior ao considerar custo de oportunidade. Preciso de comparação, não só benefícios."],
        ["sparky", "Agreed. Equipment lending addresses device access, while this proposal targets a usable place and time to study; neither automatically substitutes for the other. Before approval, the committee should compare costs and the groups each option would reach. If a smaller daytime change would meet the same unmet need more effectively, the evening pilot should not receive priority merely because it is the proposal I developed.", "Concordo. Emprestar equipamento trata de acesso a aparelho; aqui, lugar e horário utilizáveis. Um não substitui automaticamente o outro. Antes de aprovar, comparem custos e grupos alcançados. Se um ajuste diurno menor atender melhor à mesma necessidade, meu piloto não deve ter prioridade só por ser minha proposta."],
        ["pinky", "Let's assume the comparison supports a trial. What would you count as success, and whose experience might your measures miss? A busy room can still exclude the people used to justify opening it. Equally, a quiet session might be particularly valuable to a smaller group. You need criteria that recognise those possibilities without becoming so flexible that any outcome can be presented as success.", "Suponhamos que a comparação apoie o teste. O que seria sucesso e quem as medidas deixariam de fora? Sala cheia pode excluir o público que justificou abri-la; uma sessão vazia pode ser valiosa para poucos. Os critérios devem reconhecer isso sem permitir chamar qualquer resultado de sucesso."],
        ["sparky", "I'd combine attendance patterns, the proportion of respondents who say the session enabled otherwise impossible study, and staffing cost per session. The thresholds need agreement before the trial, and the feedback should include an accessible route for people who tried to attend but couldn't. We'd report the response base and uncertainty, rather than generalise from the most enthusiastic participants. No single measure should quietly replace the agreed set after results arrive.", "Combinaria presença, proporção de respondentes para quem a sessão viabilizou estudo antes impossível e custo de pessoal por sessão. Cortes devem ser acordados antes, com canal acessível para quem tentou e não conseguiu vir. Informaríamos base e incerteza, sem generalizar entusiasmo. Nenhuma medida deve substituir silenciosamente o conjunto após os resultados."],
        ["pinky", "Suppose the trial helps a small group substantially but fails the agreed attendance threshold. Would you close it automatically? I'm testing whether your commitment to pre-agreed criteria leaves room for an exceptional finding, and whether that room is accountable. Otherwise, you risk either mechanical decision-making or a convenient exception that protects your preferred outcome from every unfavourable result.", "Se ajudar muito um grupo pequeno, mas não atingir o corte de presença, encerraria automaticamente? Testo se critérios prévios permitem um achado excepcional com responsabilidade. Senão, há decisão mecânica ou exceção conveniente protegendo sua preferência de qualquer resultado desfavorável."],
        ["sparky", "The default decision should follow the agreed criteria. An exception would require a separate, explicit justification that the committee can accept or reject, with the cost and affected alternatives visible. I wouldn't retrospectively declare the threshold irrelevant. We might consider a smaller targeted session, but that would be a new proposal to evaluate, not a way to relabel the original trial as an unqualified success.", "A decisão padrão segue critérios. Uma exceção exige justificativa separada, que o comitê pode aceitar ou recusar, com custos e alternativas visíveis. Não declararia o corte irrelevante depois. Uma sessão menor seria nova proposta a avaliar, não forma de rebatizar o teste como sucesso sem ressalvas."],
        ["pinky", "Then your defence has a clear boundary: you recommend investigating a defined need, subject to comparison, agreed evaluation and an accountable decision afterwards. You have not promised that the pilot will succeed or that the room must remain open. In your final statement, keep those conditions visible while explaining why the question is worth answering. Precision should strengthen the recommendation, not bury it beneath so many qualifications that nobody can tell what you propose.", "Sua defesa tem limites: investigar uma necessidade definida, sujeito a comparação, avaliação acordada e decisão responsável. Não prometeu sucesso nem permanência. Na fala final, mantenha condições e explique por que vale investigar. Precisão deve fortalecer, não soterrar a proposta em tantas ressalvas que ninguém a identifique."]
      ], gist: ["What is the final recommendation?", "A bounded pilot contingent on comparison, agreed evaluation and an accountable later decision", "Permanent opening regardless of cost or evidence", "A claim that equipment lending can never help any learner", "A proposta é clara e condicionada, com comparação e possibilidade real de revisão."],
      detail: ["How long would the proposed pilot last?", "Twelve weeks in one existing library room", "Twelve months in a newly leased building", "An indefinite period across all local libraries", "A duração e o espaço são explicitados na abertura e delimitam a proposta."],
      inference: ["Why treat a targeted follow-up session as a new proposal?", "To avoid retrospectively relabelling a trial that did not meet its agreed criteria", "To ensure useful unexpected evidence is never discussed", "To remove costs and alternative uses from scrutiny", "Uma adaptação pode ser válida, mas requer justificativa própria em vez de reescrever retrospectivamente o sucesso."],
      mediation: "Produza uma nota em português de 160–200 palavras para um conselheiro ausente. Registre recomendação, alternativa comparável, avaliação, tratamento de exceções e informações ainda não definidas. Não invente orçamento, cortes numéricos ou aprovação do comitê."
    }), rule: "Uma defesa final deve tornar a decisão clara e revisável. Compare alternativas pelo problema que resolvem, explicite condições antes de avaliar resultados e preserve o registro quando houver exceção. Qualifications só ajudam se delimitarem ações; acumulá-las sem proposta legível vira evasão. Achado inesperado pode justificar nova decisão sem reescrever critérios anteriores.",
      example: "An exception requires a new justification, not a retrospective change to the criteria.", translation: "Uma exceção exige nova justificativa, não mudança retrospectiva dos critérios.",
      vocabulary: "opportunity cost — valor da alternativa a que se renuncia\nthreshold — limite ou corte decisório\nretrospectively — depois do fato, reinterpretando o passado",
      pitfall: "O diálogo propõe definir cortes antes do teste, mas não os fornece. Um relatório fiel registra essa pendência em vez de inventar números para parecer completo.",
      gap: "A targeted session would be a new proposal ___ evaluate, not proof that the original trial met every criterion.", fills: ["to", "for to", "to being"], gapExplanation: "A new proposal to evaluate usa infinitivo para indicar a ação ainda necessária, sem transformar a proposta em resultado comprovado.",
      production: "Escreva uma defesa de 330–380 palavras com recomendação, comparação, objeção forte, resposta e avaliação revisável. Inclua uma conclusão de até 45 palavras que mantenha a ação proposta e suas condições decisivas. Não atribua à IA ou ao curso uma acreditação externa.",
      speakingTask: "Defenda a proposta em três minutos com no máximo cinco palavras-chave. Depois responda por um minuto a Why fund this rather than equipment? e por outro a What if your trial fails? Mantenha coerência entre as três respostas e indique honestamente o que ainda precisa ser definido."
    }),
  ]
}];
