import type { ModuleDraft } from "./types";

/** Original transfer tasks. CEFR-informed learning material, not a proficiency test. */
export const fluentPracticeModules: ModuleDraft[] = [
  {
    id: "b1-vida-em-movimento", level: "B1", title: "Resolver imprevistos juntos",
    description: "Conte um problema, confirme detalhes e combine soluções em situações cotidianas.",
    prerequisiteId: "b1-leitura",
    lessons: [
      {
        id: "b1-vida-em-movimento-01", title: "Explicar um atraso e combinar um plano",
        rule: "Para resolver um atraso, explique a causa, informe o que sabe e proponha uma ação. Be going to expressa uma previsão apoiada na situação atual; I'll pode apresentar uma decisão tomada na conversa. Use about para um horário aproximado e confirme o ponto de encontro, em vez de prometer precisão que você não tem.",
        example: "I'm going to be late, so I'll meet you at the entrance.",
        translation: "Vou me atrasar, então encontro você na entrada.",
        vocabulary: "entrance — entrada\nget held up — ficar preso em um atraso\nlet someone know — avisar alguém",
        pitfall: "I'm late descreve um atraso atual; I'm going to be late prevê um atraso. Para avisar alguém, diga let you know, sem acrescentar to antes de you.",
        dialogue: "Sparky: I've been waiting for the bus for twenty minutes. The app says the next one is cancelled.\nPinky: The film starts at seven thirty. Can you take the train?\nSparky: Yes, but I'll probably get there at about seven twenty-five. I'm going to be late for our coffee.\nPinky: That's fine. I'll collect the tickets, and we can have coffee afterwards. Shall I wait inside?\nSparky: Could you meet me at the main entrance instead? My phone battery is nearly empty.\nPinky: Of course. The main entrance, not the café door. Let me know before you leave the station if you can.",
        dialogueTranslation: "Sparky está esperando o ônibus há vinte minutos e o próximo foi cancelado. O filme começa às sete e meia. De trem, ele deve chegar por volta de sete e vinte e cinco, tarde para o café combinado. Pinky vai retirar os ingressos e eles tomarão café depois. Como a bateria do celular está acabando, combinam a entrada principal, não a porta do café. Se puder, Sparky avisará antes de sair da estação.",
        question: "O que os dois combinaram para evitar que Sparky precisasse usar o celular ao chegar?",
        choices: ["Meet at the main entrance before the film.", "Wait at the café until the cancelled bus arrives.", "Collect their tickets together after the film."],
        explanation: "Eles confirmam um ponto de encontro específico porque a bateria está acabando. O café fica para depois, mas o filme continua nos planos.",
        gap: "My train is delayed. I'll let you ___ when I arrive.", fills: ["know", "to know", "knowing"],
        gapExplanation: "Let + pessoa + verbo na forma base: let you know. A expressão completa significa avisar você, sem to antes de know.",
        production: "Prática opcional: envie uma mensagem de 70–100 palavras explicando um atraso, oferecendo uma alternativa e confirmando onde encontrar um colega. Não prometa um horário exato se só tiver uma estimativa.",
        speakingTask: "Avise um colega sobre um atraso em 45 segundos. Ele propõe outro local: confirme qual entrada e repita o plano com suas palavras.",
      },
      {
        id: "b1-vida-em-movimento-02", title: "Descrever um defeito e pedir uma solução",
        rule: "Em um atendimento, comece pelo produto e pelo problema observável: it stops working after ten minutes. O passado simples informa quando você comprou; o presente descreve o defeito habitual. Would it be possible to…? faz um pedido educado. Explique o que já tentou para que a outra pessoa não repita uma solução inútil.",
        example: "It keeps switching off, even when the battery is full.",
        translation: "Ele fica desligando, mesmo quando a bateria está cheia.",
        vocabulary: "receipt — recibo\nreplacement — produto substituto\nswitch off — desligar",
        pitfall: "Keep, no sentido de uma ação que se repete, recebe verbo em -ing: keeps switching off. Não use keeps to switch nem confunda receipt com receita.",
        dialogue: "Pinky: I bought this speaker last Saturday. It keeps switching off after ten minutes.\nSparky: Have you tried charging it with a different cable?\nPinky: Yes. I borrowed one from my sister, and the battery shows as full. The same thing happens.\nSparky: Thanks for checking. We can send it for repair, but that usually takes a week.\nPinky: I need it for a class on Friday. Would it be possible to get a replacement?\nSparky: We have the same model in blue. If you have the receipt, I can check whether an exchange is available.\nPinky: Here it is. Blue would be fine; the colour isn't important to me.",
        dialogueTranslation: "Pinky comprou a caixa de som no sábado e ela desliga após dez minutos. Já testou outro cabo e a bateria indica carga completa. Sparky oferece encaminhá-la para reparo, que costuma levar uma semana. Como Pinky precisa dela na sexta, pergunta sobre substituição. Há o mesmo modelo em azul, mas Sparky ainda precisa verificar o recibo e a possibilidade da troca. A cor não importa para Pinky.",
        question: "Por que Pinky pergunta sobre uma substituição em vez de escolher o reparo?",
        choices: ["She needs the speaker before the usual repair would be finished.", "She has already been promised a free blue speaker.", "She wants a different colour although the speaker works."],
        explanation: "A necessidade na sexta torna o prazo do reparo inconveniente. A troca ainda será verificada; mostrar o recibo não significa aprovação automática.",
        gap: "Would it be possible ___ this one for the same model?", fills: ["to exchange", "exchanging", "exchange"],
        gapExplanation: "Depois de would it be possible usamos to + verbo: to exchange. A estrutura apresenta uma possibilidade com educação, sem afirmar um direito já confirmado.",
        production: "Prática opcional: escreva 80–110 palavras para o atendimento de uma loja. Descreva o defeito, diga quando começou, informe um teste que já fez e peça uma solução dentro do prazo de que precisa.",
        speakingTask: "Explique o defeito em um minuto sem dizer apenas it is broken. Responda à sugestão de um atendente e confirme o próximo passo.",
      },
    ],
  },
  {
    id: "b2-acordos-cotidianos", level: "B2", title: "Negociar condições na vida real",
    description: "Pondere restrições, verifique acordos e adapte sugestões ao que cada pessoa precisa.",
    prerequisiteId: "b2-autonomia",
    lessons: [
      {
        id: "b2-acordos-cotidianos-01", title: "Negociar regras de convivência",
        rule: "Uma regra negociada distingue preferência, necessidade e condição. Provided that introduz uma condição para aceitar a proposta; rather than contrasta a alternativa evitada. Faça uma concessão concreta, defina o alcance do acordo e proponha uma revisão. Isso é mais preciso do que afirmar que alguém sempre faz barulho ou nunca coopera.",
        example: "Let's try the new schedule for two weeks and then discuss how it went.",
        translation: "Vamos testar o novo horário por duas semanas e depois conversar sobre como foi.",
        vocabulary: "quiet hours — horários de silêncio\ncompromise — chegar a um meio-termo\ncheck in — conversar para verificar como algo está indo",
        pitfall: "Compromise pode significar chegar a um meio-termo, não prometer algo. Uma condição com provided that não é um fato já garantido: ela ainda precisa ser cumprida.",
        dialogue: "Sparky: Could we talk about the evening calls? I can hear them through the wall, and I've got early shifts this month.\nPinky: I didn't realise they were keeping you up. My project partner is overseas, so earlier calls aren't always possible.\nSparky: I don't want you to cancel them. Would using the living room help?\nPinky: Probably, although the internet drops near the window. I could move the router and wear headphones.\nSparky: I'm happy to compromise, provided that we agree on quiet hours after ten on work nights.\nPinky: What about Tuesdays? Our only shared slot is ten thirty.\nSparky: One planned exception would work if you let me know in advance. Let's try it for two weeks rather than making a permanent rule tonight.\nPinky: Agreed. And if your shifts change, we'll check in again. I'd rather know there's a problem than assume the arrangement is working.",
        dialogueTranslation: "Sparky ouve as chamadas noturnas através da parede e está trabalhando cedo neste mês. Pinky depende do fuso do colega. Eles discutem usar a sala, mover o roteador e usar fones. Sparky aceita um meio-termo com silêncio após as dez nas noites anteriores ao trabalho. Combinam uma exceção planejada às terças, aviso prévio e um teste de duas semanas. Se os turnos mudarem, conversarão novamente.",
        question: "Qual detalhe mostra que o acordo é um teste negociado, e não uma proibição definitiva?",
        choices: ["It includes a planned exception and a review after two weeks.", "Pinky must cancel every call after ten, including Tuesdays.", "The rules apply permanently even if Sparky's shifts change."],
        explanation: "A exceção e a revisão mostram limites ajustáveis. Sparky reconhece a necessidade das chamadas, mas estabelece uma condição para conseguir dormir.",
        gap: "We can keep this arrangement, ___ that it works for both of us.", fills: ["provided", "despite", "unless"],
        gapExplanation: "Provided that significa desde que. Despite não introduz essa oração condicional, e unless that não é a construção adequada aqui.",
        production: "Prática opcional: proponha um acordo de convivência em 140–180 palavras, reconhecendo duas necessidades. Inclua uma condição, uma exceção delimitada e uma data para reavaliar o combinado.",
        speakingTask: "Negocie por dois minutos: seu colega aceita o horário, mas pede uma exceção. Reconheça a necessidade e reformule o acordo sem abandonar seu limite.",
      },
      {
        id: "b2-acordos-cotidianos-02", title: "Recomendar um roteiro com acessibilidade",
        rule: "Ao recomendar uma atividade, compare as opções pelos mesmos critérios e verifique informações incompletas. Be supposed to indica expectativa ou informação recebida, não uma confirmação. As long as explicita uma condição. Uma recomendação responsável separa acesso ao prédio de acesso ao percurso inteiro e pergunta à pessoa o que ela prefere.",
        example: "The museum sounds promising, as long as we can confirm the access.",
        translation: "O museu parece uma boa opção, desde que possamos confirmar as condições de acesso.",
        vocabulary: "step-free — sem degraus\ndetour — desvio de percurso\nbackup plan — plano alternativo",
        pitfall: "Accessible não especifica todas as necessidades de uma pessoa. Step-free fala de degraus; não garante banheiros adequados nem que todos os espaços estarão abertos.",
        dialogue: "Pinky: The walking tour looks interesting, but the route includes a steep hill. My uncle uses a wheelchair, and he asked us to check before booking.\nSparky: The museum is supposed to have a step-free entrance. Would he prefer that?\nPinky: He actually liked the tour more. We shouldn't choose for him just because the museum seems easier.\nSparky: Fair point. The tour company mentions an alternative route, but it doesn't say whether everyone stays together.\nPinky: I'll ask about that and the accessible toilets. The museum can be our backup plan, provided the lift is working.\nSparky: Let's send him both options with the details we can confirm. If the tour requires a separate route, he can decide whether that would still be enjoyable.\nPinky: Exactly. And we should check the cancellation deadline so he has time to make the choice without pressure.",
        dialogueTranslation: "Pinky e Sparky planejam um passeio para o tio dela, que usa cadeira de rodas. O roteiro inclui uma ladeira e a alternativa anunciada não esclarece se o grupo fica junto. Embora o museu pareça mais simples, o tio preferiu o passeio. Pinky vai verificar rota, banheiros e cancelamento. O museu será alternativa se o elevador funcionar. Eles enviarão informações confirmadas para que o próprio tio decida.",
        question: "O que Pinky contesta quando Sparky sugere o museu?",
        choices: ["Choosing for her uncle before checking the option he prefers.", "Asking the tour company for more precise access information.", "Keeping the museum as an alternative if the tour is unsuitable."],
        explanation: "Ela contesta decidir por ele com base em uma suposição. Verificar detalhes e ter alternativa continuam fazendo parte do plano dos dois.",
        gap: "The entrance is supposed ___ step-free, but let's call to confirm.", fills: ["to be", "being", "be"],
        gapExplanation: "Be supposed to + verbo transmite uma expectativa ou informação recebida. To be completa a estrutura e a segunda parte sinaliza que falta confirmação.",
        production: "Prática opcional: escreva 150–190 palavras comparando dois passeios. Separe fatos confirmados de dúvidas, peça a preferência do destinatário e explique quais informações ainda precisa verificar.",
        speakingTask: "Apresente duas opções em dois minutos. Seu interlocutor discorda da sua favorita: esclareça os critérios e adapte a recomendação à preferência dele.",
      },
    ],
  },
  {
    id: "c1-intencoes-e-impacto", level: "C1", title: "Interpretar intenção e administrar impacto",
    description: "Reconheça pedidos indiretos e transforme feedback ambíguo em ações verificáveis.",
    prerequisiteId: "c1-evidencias",
    lessons: [
      {
        id: "c1-intencoes-e-impacto-01", title: "Responder a um pedido que não foi explícito",
        rule: "Pedidos indiretos permitem negociar sem impor, mas dependem do contexto. I was wondering whether… abre uma possibilidade; o passado pode marcar distância social, não tempo passado. Para não adivinhar a intenção, ofereça uma interpretação provisória e verifique-a. Nomeie capacidade, prioridade e prazo: aceitar ouvir um problema não equivale a assumir todo o trabalho.",
        example: "If you're asking me to take this on, we'd need to revisit the deadline.",
        translation: "Se você está me pedindo para assumir isso, precisaríamos rever o prazo.",
        vocabulary: "take something on — assumir uma responsabilidade\ncapacity — disponibilidade para trabalho\nrevisit — reavaliar",
        pitfall: "I was wondering whether não prova que o pedido pertence ao passado. O distanciamento também pode torná-lo menos impositivo; confirme a intenção antes de aceitar uma tarefa implícita.",
        dialogue: "Pinky: I was wondering whether the report might benefit from another pair of eyes. The figures are fine, but the conclusion feels rushed.\nSparky: Do you mean a quick read, or are you asking me to rewrite the conclusion?\nPinky: Ideally, a rewrite. I didn't want to assume you had the capacity.\nSparky: Thanks for clarifying. If you're asking me to take this on, we'd need to revisit the deadline for the briefing I'm already preparing.\nPinky: The report goes to the partners tomorrow, whereas the briefing is internal. Could the briefing move to Thursday?\nSparky: It could, if the people waiting for it agree. I can review the conclusion today and identify the changes, but I shouldn't promise the full rewrite until we've checked that.\nPinky: I'll contact them now. If the date can't move, could you at least flag anything that overstates the evidence?\nSparky: Yes. Let's separate the essential accuracy check from the stylistic improvements. That way, we can make a realistic decision when they reply.",
        dialogueTranslation: "Pinky sugere que o relatório ganharia com uma segunda leitura, mas deseja uma reescrita. Sparky verifica o alcance do pedido antes de assumir. Para reescrever, precisaria adiar outro trabalho, dependendo da concordância dos destinatários. Enquanto isso, oferece revisar a conclusão e apontar mudanças. Se o prazo não puder mudar, fará ao menos a verificação de afirmações exageradas, separando precisão essencial de melhorias de estilo.",
        question: "Que função tem a pergunta de Sparky sobre leitura rápida ou reescrita?",
        choices: ["It clarifies the scope before he commits to work that affects another deadline.", "It establishes that Pinky's report contains incorrect figures.", "It rejects any involvement unless all other work is cancelled."],
        explanation: "A pergunta transforma uma sugestão indireta em um pedido delimitado. Sparky oferece ajuda parcial e condiciona o compromisso maior à negociação de prioridades.",
        gap: "I was wondering ___ you could check the conclusion before we send it.", fills: ["whether", "unless", "despite"],
        gapExplanation: "Whether introduz a questão indireta sobre a possibilidade de ajudar. Unless introduziria condição negativa; despite não recebe essa oração sem outra estrutura.",
        production: "Prática opcional: responda em 200–240 palavras a um pedido indireto de trabalho extra. Explicite sua interpretação, negocie prioridades e ofereça uma entrega mínima útil sem prometer o que depende de terceiros.",
        speakingTask: "Em dois minutos, responda a um pedido vago. Faça uma pergunta para esclarecer o alcance, proponha limites e resuma o acordo para uma terceira pessoa.",
      },
      {
        id: "c1-intencoes-e-impacto-02", title: "Transformar feedback vago em orientação útil",
        rule: "Feedback útil distingue observação, interpretação e ação. Rather vague é uma avaliação; I lost track when… localiza um efeito e permite discuti-lo. Ao receber comentários, peça um exemplo e teste sua interpretação com Would it help if…? Ajuste registro e detalhe ao destinatário sem presumir que tornar um texto acessível exige apagar incertezas.",
        example: "Would it help if I led with the finding and explained the caveat afterwards?",
        translation: "Ajudaria se eu começasse pela descoberta e explicasse a ressalva depois?",
        vocabulary: "lose track — perder o fio da explicação\ncaveat — ressalva\nactionable — que permite uma ação concreta",
        pitfall: "Accessible pode descrever uma explicação compreensível, sem significar superficial. Simplificar a ordem da informação não autoriza retirar uma ressalva que muda a conclusão.",
        dialogue: "Sparky: The presentation is thorough, but it could be more accessible.\nPinky: Could you point to a section where you lost track? I'm not sure whether you mean the vocabulary or the structure.\nSparky: The opening, mainly. You define three statistical terms before telling us what changed. I was trying to remember the definitions rather than follow your argument.\nPinky: Would it help if I led with the finding and explained the caveat afterwards?\nSparky: Yes, as long as afterwards doesn't mean burying it on the final slide. The sample was small, and people need to know that before acting on the result.\nPinky: So I could say the pilot improved attendance, immediately add that we can't yet generalise, and then show how we measured it.\nSparky: That would work. Keep the technical definitions in the notes for anyone who wants them.\nPinky: I'll try the revised opening with a colleague outside our team. If they can explain both the finding and its limitation, we'll have a better indication that the change helped.",
        dialogueTranslation: "Sparky considera a apresentação completa, mas pouco acessível. Pinky pede um exemplo e descobre que a dificuldade está na abertura com três definições antes do resultado. Propõe começar pela descoberta, mantendo a ressalva sobre a amostra pequena imediatamente visível. As definições podem ir para as notas. Para testar a revisão, pedirá a alguém de fora da equipe que explique tanto o resultado quanto sua limitação.",
        question: "Por que o teste com um colega de fora da equipe é mais informativo do que apenas perguntar se ele gostou?",
        choices: ["It checks whether he can communicate the finding and its limitation.", "It proves the small sample represents everyone in the target population.", "It removes the need to explain any technical terms in the presentation."],
        explanation: "A reformulação pelo colega revela compreensão de duas ideias essenciais. Gostar da apresentação não demonstra entendimento, e esse teste não valida a amostra do estudo.",
        gap: "I lost track ___ you introduced the third definition.", fills: ["when", "despite", "whereas"],
        gapExplanation: "When identifica o momento da dificuldade. Whereas indicaria contraste entre ideias, e despite precisaria de complemento nominal ou construção diferente.",
        production: "Prática opcional: reescreva uma abertura técnica em 180–220 palavras para um público não especialista. Preserve uma limitação relevante e proponha uma pergunta que permita verificar a compreensão.",
        speakingTask: "Dê feedback em dois minutos com uma observação específica, o efeito em você e uma sugestão. Depois, reformule sua orientação após ouvir uma objeção.",
      },
    ],
  },
  {
    id: "c2-significado-em-disputa", level: "C2", title: "Negociar significados sob pressão",
    description: "Analise pressupostos, ironia e reformulações com precisão, sem inventar intenções.",
    prerequisiteId: "c2-estilo-cultura",
    lessons: [
      {
        id: "c2-significado-em-disputa-01", title: "Contestar a premissa de uma pergunta",
        rule: "Uma pergunta pode embutir uma conclusão discutível: when did you stop listening? pressupõe que você deixou de ouvir. Responda ao problema legítimo sem ratificar essa premissa. Distinga fato, implicação e critério de decisão; reconhecer um impacto não exige aceitar uma descrição falsa. Reformule com precisão e volte à pergunta prática, evitando usar nuances para fugir da responsabilidade.",
        example: "That question assumes the decision was final, which is precisely what's disputed.",
        translation: "Essa pergunta pressupõe que a decisão era definitiva, e é justamente isso que está em discussão.",
        vocabulary: "premise — premissa\nratify — endossar formalmente\naccountability — responsabilidade de prestar contas",
        pitfall: "Contestar um pressuposto não responde automaticamente à preocupação de quem pergunta. Depois de esclarecer a premissa, trate do impacto concreto; precisão pode virar evasão se você parar na reformulação.",
        dialogue: "Pinky: At the public meeting, someone asked, 'Why did you ignore residents once the decision was final?' How would you answer without sounding evasive?\nSparky: I'd start by separating the two claims. The proposal had been shortlisted, not finally approved. But that doesn't settle whether residents had a meaningful chance to influence it.\nPinky: So correcting the word final isn't enough. People received a document that looked like an announcement.\nSparky: Exactly. That question assumes the decision was final, which is precisely what's disputed. Still, we should acknowledge that the document gave that impression and explain what can actually change.\nPinky: What if the budget and location are already fixed? Calling everything open for discussion would be misleading too.\nSparky: Then name those constraints. Say which design choices remain open, who will assess suggestions, and when residents will see a response.\nPinky: And address why the original document wasn't clearer?\nSparky: Yes. We can accept responsibility for unclear communication without pretending the entire process was either fully open or completely settled. The useful question is whether the remaining choices are significant enough for participation to matter. That's something we should be prepared to demonstrate, not merely assert.",
        dialogueTranslation: "Pinky propõe responder a uma pergunta que pressupõe decisão definitiva e desconsideração dos moradores. Sparky distingue seleção preliminar de aprovação, mas reconhece que a comunicação pareceu um anúncio fechado. Se orçamento e localização já estão fixos, isso precisa ser dito. A resposta deve identificar escolhas ainda abertas, responsáveis pela análise e prazo de retorno, além de assumir a falha de comunicação. A participação precisa ter consequências demonstráveis.",
        question: "Qual resposta melhor preserva a distinção defendida por Sparky sem evitar a prestação de contas?",
        choices: ["Clarify what was settled, acknowledge the misleading impression, and specify what residents can still influence.", "State that no final approval existed and conclude that residents' concerns are therefore unfounded.", "Describe every aspect as negotiable so residents feel their participation has been valued."],
        explanation: "A primeira opção corrige a premissa sem apagar o impacto. As demais usam uma distinção formal para desqualificar a preocupação ou prometem abertura que não existe.",
        gap: "The issue is not ___ consultation occurred, but whether it could affect the outcome.", fills: ["whether", "unless", "despite"],
        gapExplanation: "Whether introduz a alternativa em discussão: houve ou não consulta. O contraste seguinte desloca a análise da existência formal para a influência efetiva.",
        production: "Prática opcional: redija uma resposta pública de 240–280 palavras a uma pergunta com pressuposto contestável. Corrija-o, reconheça uma crítica legítima e estabeleça compromissos verificáveis sem prometer reabrir decisões fixadas.",
        speakingTask: "Responda por dois minutos a uma pergunta hostil sobre uma decisão. Um colega interrompe com uma objeção: esclareça a premissa e responda ao impacto sem atacar o interlocutor.",
      },
      {
        id: "c2-significado-em-disputa-02", title: "Reparar um comentário irônico entre culturas",
        rule: "A ironia pode depender de expectativas compartilhadas, entonação e relações sociais. Brilliant, another delay pode elogiar literalmente ou criticar, conforme o contexto; não existe uma leitura cultural única garantida. Quando o efeito diverge da intenção, descreva o que quis comunicar, reconheça o efeito e reformule. Explicar a piada não substitui reparar a interação nem autoriza atribuir a reação à nacionalidade da pessoa.",
        example: "Calling the delay a triumph of efficiency was hardly an unqualified compliment.",
        exampleFrom: "c2-nuance-02",
        translation: "Chamar o atraso de triunfo da eficiência dificilmente foi um elogio sem ressalvas.",
        vocabulary: "come across as — soar como; passar a impressão de\ndismissive — que desconsidera alguém ou algo\nshared assumptions — pressupostos compartilhados",
        pitfall: "I was only joking explica intenção, mas pode minimizar o efeito. Não conclua que um povo não entende ironia: relação, situação, entonação e experiência individual também influenciam a interpretação.",
        dialogue: "Sparky: When the booking system failed again, I said, 'Brilliant, exactly what we needed.' Pinky went quiet. I thought the irony was obvious.\nPinky: I understood that you weren't pleased. What wasn't clear was whether you were criticising the system or me for choosing it.\nSparky: I hadn't considered that. What I meant as a joke came across as dismissive, and I can see why. I was frustrated with the repeated failures, not with your effort to find a solution.\nPinky: I appreciate you saying that. During the meeting, I was already trying to explain the problem to a new colleague who didn't know the history. Your comment made that harder.\nSparky: Would it help if I clarified it with them?\nPinky: Briefly, yes. There's no need to turn it into a discussion about who understands our sense of humour. Just explain the concern and what we're doing next.\nSparky: I'll say the system has failed twice this week, that we chose it on reasonable information, and that we're checking an alternative.\nPinky: That gives them something useful. We can still joke together; I just need the criticism to be clear when other people are relying on us for an accurate explanation.",
        dialogueTranslation: "Sparky ironiza mais uma falha no sistema de reservas. Pinky percebe a ironia, mas não sabe se a crítica é ao sistema ou à escolha que ela fez. Ele reconhece o efeito e esclarece a intenção. Pinky pede uma explicação breve ao novo colega, sem generalizar sobre quem entende humor. Eles concordam em comunicar as duas falhas, o fundamento razoável da escolha original e a busca de alternativa.",
        question: "Qual interpretação do silêncio de Pinky é sustentada pela explicação dela?",
        choices: ["She recognised the irony but was unsure whom the criticism targeted in front of a new colleague.", "She took brilliant as sincere praise because people from her culture do not understand irony.", "She wanted all humour banned even in private conversations with Sparky."],
        explanation: "Pinky explica que reconheceu a ironia; o problema era o alvo ambíguo e seu efeito na reunião. O texto rejeita a generalização cultural e não proíbe humor entre os dois.",
        gap: "The remark came ___ as criticism of the person rather than the system.", fills: ["across", "up", "out"],
        gapExplanation: "Come across as descreve a impressão produzida. Come up e come out têm outros usos, mas não completam esse padrão com o sentido de soar como uma crítica.",
        production: "Prática opcional: escreva 240–280 palavras reformulando uma mensagem irônica para um grupo intercultural. Explique intenção e efeito sem estereótipos e preserve a preocupação legítima em uma versão clara e respeitosa.",
        speakingTask: "Em três minutos, repare um comentário que foi entendido como descaso. Ouça a interpretação do outro, reconheça o efeito e explique o problema a um terceiro em registro neutro.",
      },
    ],
  },
];
