// One authored extra distractor for each published interpretation and gap task.
// The existing first option remains the answer; these entries are always wrong in context.
export const fourthOptions: Record<string, readonly [choice: string, gap: string]> = {
  "a1-1-1": ["Nice to meet me too!", "I'm is"],
  "a1-identidade-01": ["Clara", "yours"],
  "a1-identidade-02": ["Japan", "be"],
  "a1-identidade-03": ["Nineteen", "am"],
  "a1-identidade-04": ["Chef", "be"],
  "a1-identidade-05": ["Yes, I am.", "am"],
  "a1-identidade-06": ["Omar", "spelled"],
  "a1-pessoas-01": ["Pilot", "any"],
  "a1-pessoas-02": ["Four", "childrens"],
  "a1-pessoas-03": ["Lia's cousin", "haves"],
  "a1-pessoas-04": ["The clerk's", "myself"],
  "a1-pessoas-05": ["The white shoes over there", "Theses"],
  "a1-pessoas-06": ["Cold", "smalling"],
  "a1-2-1": ["I start work on nine.", "to"],
  "a1-rotina-01": ["Mathematics", "is go"],
  "a1-rotina-02": ["By train", "to drink"],
  "a1-rotina-03": ["No, she doesn't.", "Are"],
  "a1-rotina-04": ["Taking the bus", "usually"],
  "a1-rotina-05": ["16:30", "to"],
  "a1-rotina-06": ["At eight", "in the"],
  "a1-casa-01": ["Four", "be"],
  "a1-casa-02": ["Behind the door", "at"],
  "a1-casa-03": ["The dining room", "bookshelf"],
  "a1-casa-04": ["Straight back", "To go"],
  "a1-casa-05": ["An open ticket", "foots"],
  "a1-casa-06": ["The back gate", "to park"],
  "a1-consumo-01": ["Tap water", "to liking"],
  "a1-consumo-02": ["Shopping", "readed"],
  "a1-consumo-03": ["A loaf of bread", "bottle"],
  "a1-consumo-04": ["Butter", "many"],
  "a1-consumo-05": ["Twenty pounds", "a lot"],
  "a1-consumo-06": ["Large", "with"],
  "a1-interacao-01": ["Run fast", "speaking"],
  "a1-interacao-02": ["By the window", "mine"],
  "a1-interacao-03": ["Clara", "be"],
  "a1-interacao-04": ["Calling Ben", "be"],
  "a1-interacao-05": ["It is windy.", "They"],
  "a1-interacao-06": ["Inside the library at four", "to"],

  "a2-passado-01": ["Ana's family", "be"],
  "a2-passado-02": ["She cooked dinner.", "was live"],
  "a2-passado-03": ["At a restaurant", "seen"],
  "a2-4-1": ["Did you going to the park?", "goed"],
  "a2-passado-04": ["A bicycle", "buying"],
  "a2-passado-05": ["They had breakfast.", "Until"],
  "a2-passado-06": ["Having breakfast", "be"],
  "a2-escolhas-01": ["Neither room has a price.", "as"],
  "a2-escolhas-02": ["All three cost the same", "most good"],
  "a2-escolhas-03": ["Price", "most heavy"],
  "a2-escolhas-04": ["The shop is closed.", "plenty"],
  "a2-escolhas-05": ["Space", "many of"],
  "a2-escolhas-06": ["Bottles", "less"],
  "a2-experiencias-01": ["In 2025", "had"],
  "a2-experiencias-02": ["Visiting Canada", "yet"],
  "a2-experiencias-03": ["Opening the message", "still"],
  "a2-experiencias-04": ["For two years", "during"],
  "a2-experiencias-05": ["Ana", "going"],
  "a2-experiencias-06": ["I will see it next Friday.", "has calling"],
  "a2-3-1": ["Let's coffee have.", "by"],
  "a2-planos-01": ["Stay at home", "for to"],
  "a2-planos-02": ["To pack the clothes", "will not to"],
  "a2-planos-03": ["She has a class.", "to meeting"],
  "a2-planos-04": ["Monday", "to to"],
  "a2-planos-05": ["Visit the beach", "going"],
  "a2-planos-06": ["Driving to work", "to feel"],
  "a2-servicos-01": ["Buy a car", "sharing"],
  "a2-servicos-02": ["Showing a passport", "must"],
  "a2-servicos-03": ["Using a pen", "must to"],
  "a2-servicos-04": ["Yes, but only on Sunday.", "during"],
  "a2-servicos-05": ["A cancellation", "receive"],
  "a2-servicos-06": ["Friday at ten", "availability"],
  "a2-textos-01": ["The booking", "they"],
  "a2-textos-02": ["The roads were flooded.", "since of"],
  "a2-textos-03": ["9:30", "emailing"],
  "a2-textos-04": ["A business meeting", "friend"],
  "a2-textos-05": ["A class recording", "informationes"],
  "a2-textos-06": ["A drink in a glass cup", "must to"],
  "a2-comunicacao-01": ["At the traffic lights.", "gets"],
  "a2-comunicacao-02": ["At the airport.", "getting"],
  "a2-comunicacao-03": ["Extra cheese.", "with no of"],
  "a2-comunicacao-04": ["B-4-9-7", "to saying"],
  "a2-comunicacao-05": ["Turn off the light.", "to close"],
  "a2-comunicacao-06": ["Seven o'clock.", "to work"],

  "b1-narrativas-01": ["Where Ben works", "uses"],
  "b1-narrativas-02": ["The closing credits rolled.", "leaving"],
  "b1-narrativas-03": ["A child lost a phone.", "to sleeping"],
  "b1-narrativas-04": ["Yes, every wall is finished.", "to work"],
  "b1-narrativas-05": ["He was ill.", "speaked"],
  "b1-narrativas-06": ["No, the doors were already locked.", "to opening"],
  "b1-5-1": ["I think useful because save time.", "because of"],
  "b1-argumentos-01": ["The paper is unavailable.", "agreeing"],
  "b1-argumentos-02": ["Enjoyable because it was short", "In spite"],
  "b1-argumentos-03": ["Replacing every container", "such like"],
  "b1-argumentos-04": ["Unreliable internet access", "drawbacked"],
  "b1-argumentos-05": ["Ben's holiday plans", "to read"],
  "b1-argumentos-06": ["The ticket price is printed.", "Into"],
  "b1-hipoteses-01": ["Yes, she has arrived.", "must to"],
  "b1-hipoteses-02": ["His coat is wet after rain.", "mustn't to"],
  "b1-hipoteses-03": ["Yes, for next Friday.", "would to"],
  "b1-hipoteses-04": ["Ana having a car", "going to"],
  "b1-hipoteses-05": ["Changing the venue", "to arrive"],
  "b1-hipoteses-06": ["Going out, because the restaurant is nearby", "to staying"],
  "b1-precisao-01": ["It has a blue handle.", "whose"],
  "b1-precisao-02": ["Art students abroad", "to made"],
  "b1-precisao-03": ["Friday afternoon", "be"],
  "b1-precisao-04": ["Repeat the first course", "to arriving"],
  "b1-precisao-05": ["Feed her fish", "its"],
  "b1-precisao-06": ["Drawing", "to"],
  "b1-6-1": ["Could you to explain that again?", "meant"],
  "b1-colaboracao-01": ["It closes at noon on Saturday.", "working"],
  "b1-colaboracao-02": ["The final presentation", "to checking"],
  "b1-colaboracao-03": ["By next Monday", "from"],
  "b1-colaboracao-04": ["The connection is offline.", "to try"],
  "b1-colaboracao-05": ["Refund the whole order", "to arrive"],
  "b1-colaboracao-06": ["Whether Ana will draft the text", "to meeting"],
  "b1-leitura-01": ["The club began selling books to members.", "increasement"],
  "b1-leitura-02": ["The writer will certainly take a taxi.", "suggesting"],
  "b1-leitura-03": ["The date, from Tuesday to Friday", "since"],
  "b1-leitura-04": ["Both drafts are equally courteous", "regarding"],
  "b1-leitura-05": ["The room was too noisy.", "From"],
  "b1-leitura-06": ["Meet at the library", "for"],
  "b2-argumentacao-01": ["End the trial before reviewing delivery access.", "Even despite"],
  "b2-argumentacao-02": ["Stress had already fallen before the schedule changed.", "contribution"],
  "b2-argumentacao-03": ["He agrees to promise next-day delivery for all orders.", "against to"],
  "b2-argumentacao-04": ["Only the initial purchase price.", "Into"],
  "b2-argumentacao-05": ["Eleven pages on Wednesday at no extra cost.", "approve"],
  "b2-argumentacao-06": ["It replaces printed notices with an app-only message.", "for by"],
  "b2-autonomia-01": ["The board should sign a five-year agreement.", "to inviting"],
  "b2-autonomia-02": ["New customers qualify by keeping a monthly plan.", "into"],
  "b2-autonomia-03": ["She wants a different colour for the event next month.", "for about"],
  "b2-autonomia-04": ["The survey excluded people attending morning classes.", "At to"],
  "b2-autonomia-05": ["The final file was never printed.", "would have"],
  "b2-autonomia-06": ["Use the two-day sample as a final verdict.", "measure to"],
  "b1-vida-em-movimento-01": ["Meet outside the cinema after the film.", "to knowing"],
  "b1-vida-em-movimento-02": ["She needs a replacement because she lost the receipt.", "to exchanging"],
  "b2-acordos-cotidianos-01": ["It sets a permanent rule with no review date.", "provided to"],
  "b2-acordos-cotidianos-02": ["Calling the tour company before booking anything.", "to being"],

  "c1-sintese-01": ["Equipment guarantees equal completion rates across all groups.", "unlike"],
  "c1-sintese-02": ["The decline proves that interest in the service disappeared.", "away from"],
  "c1-sintese-03": ["Comparing paid staff with unpaid volunteers.", "distinctive"],
  "c1-sintese-04": ["State that the study establishes the same effect in every organisation.", "to applying"],
  "c1-sintese-05": ["Treating the counterexample as irrelevant to the original claim.", "needing to"],
  "c1-sintese-06": ["A guarantee that staffing will never affect access.", "to being"],
  "c1-interacao-01": ["The external reviewers received the complete archive already.", "to receiving"],
  "c1-interacao-02": ["Whether the report has already been published.", "being"],
  "c1-interacao-03": ["Announce the date as unconditional regardless of funding.", "upon of"],
  "c1-interacao-04": ["The date on which scanning began.", "does"],
  "c1-interacao-05": ["She presents an unverified number as final.", "among between"],
  "c1-interacao-06": ["An indefinite trial with no planned review.", "onto"],
  "c1-evidencias-01": ["It establishes the preferences of residents who never joined the programme.", "despite"],
  "c1-evidencias-02": ["It correctly restricted its claim to the surveyed employees' attendance.", "consistent to"],
  "c1-evidencias-03": ["Every district can be ranked precisely by its point estimate.", "so"],
  "c1-evidencias-04": ["Present the percentage without the number of journeys or locations.", "for"],
  "c1-evidencias-05": ["It confirms the rumour before any source can be checked.", "off"],
  "c1-evidencias-06": ["It promises the trial will succeed in every district.", "provided if"],
  "c2-nuance-01": ["The writer treats faster processing as proof of fairer outcomes.", "conceives"],
  "c2-nuance-02": ["The reviewer's praise is followed by evidence that all deadlines were met.", "corroborates against"],
  "c2-nuance-03": ["It presents failure as unavoidable and beyond scrutiny.", "inevitably"],
  "c2-nuance-04": ["Every late application received final approval.", "entailed to"],
  "c2-nuance-05": ["The metaphor proves the programme has no measurable outcomes.", "foregrounded to"],
  "c2-nuance-06": ["The procedure for balancing needs is fully specified.", "supporting"],
  "c2-producao-01": ["Remove the staffing condition and leave the agent unspecified.", "integrity"],
  "c2-producao-02": ["A precise prediction for each individual household.", "retain to"],
  "c2-producao-03": ["The observer stated that all residents approved the timetable.", "imputed to"],
  "c2-producao-04": ["Dismiss identifiability as irrelevant to the objection.", "engage at"],
  "c2-producao-05": ["It turns the insinuation into an unsupported accusation.", "dismissal"],
  "c2-producao-06": ["Set a permanent policy before reviewing the available evidence.", "revising"],
  "c2-estilo-cultura-01": ["The phrase proves every reader will favour the advertised product.", "for"],
  "c2-estilo-cultura-02": ["The observed queue confirms the report's promise without qualification.", "at odds to"],
  "c2-estilo-cultura-03": ["Translate the line as sincere praise even though the scene signals irony.", "on"],
  "c2-estilo-cultura-04": ["The different emphases mean the two headlines describe unrelated events.", "salience"],
  "c2-estilo-cultura-05": ["It gives equal emphasis to all actions and hides the final decision.", "in"],
  "c2-estilo-cultura-06": ["Choose the text with the simpler vocabulary as automatically more truthful.", "to into"],
  "c1-intencoes-e-impacto-01": ["It confirms he has already accepted the whole rewrite.", "to whether"],
  "c1-intencoes-e-impacto-02": ["It checks whether the colleague remembers every figure exactly.", "whereas when"],
  "c2-significado-em-disputa-01": ["Promise that every decision will be reopened before explaining what remains open.", "unless whether"],
  "c2-significado-em-disputa-02": ["She could not hear the remark over the background noise.", "across as"],

  // Reserved listening modules are also built during editorial validation.
  "b2-pressure-01": ["An immediate replacement without an inspection", "since"],
  "b2-pressure-02": ["Take the expensive taxi without contacting the guesthouse", "regardless to"],
  "b2-pressure-03": ["Assign all cleaning to one flatmate indefinitely", "have take"],
  "b2-pressure-04": ["Move everyone to the inaccessible smaller room", "unless if"],
  "b2-pressure-05": ["Spend the budget on more coffee stalls", "from"],
  "b2-pressure-06": ["Increase bookings before reviewing the waiting times", "even though of"],
  "b2-narratives-01": ["He discovers that food donations need no checking", "have realised"],
  "b2-narratives-02": ["That every repair can be completed on the day", "done to"],
  "b2-narratives-03": ["To make a local finding sound universal", "were supply"],
  "b2-narratives-04": ["A strict ban on messages for all students", "on of"],
  "b2-narratives-05": ["Treat the first account as the complete record", "According for"],
  "b2-narratives-06": ["Publish a confident conclusion without further interviews", "hasn't receiving"],
  "c1-mediation-01": ["A clear request turns into a permanent refusal", "can to"],
  "c1-mediation-02": ["They wait for unapproved quotations before drafting anything", "unless of"],
  "c1-mediation-03": ["They agree to ignore the impact of the original wording", "to meant"],
  "c1-mediation-04": ["Confirm a permanent arrangement without consulting the groups", "although of"],
  "c1-mediation-05": ["They believe forwarding can never change how a message reads", "at"],
  "c1-mediation-06": ["It presents the temporary trial as a permanent consensus", "necessarily permanent"],
  "c1-long-listening-01": ["An empty seat alone proves that a course is accessible", "on their own behalf"],
  "c1-long-listening-02": ["They choose the cheapest night without asking users", "instead to"],
  "c1-long-listening-03": ["It proves a permanent change in neighbourhood spending", "already yet"],
  "c1-long-listening-04": ["The survey establishes the result for all eligible residents", "completed lessons"],
  "c1-long-listening-05": ["Approval of the scheme without an access review", "to for"],
  "c1-long-listening-06": ["He treats a small sample as decisive proof of long-term demand", "in despite"],
  "c2-intercultural-01": ["Treating the idiom as a literal ban on every change", "without to"],
  "c2-intercultural-02": ["Interpret polite wording as an unconditional endorsement", "beneath from"],
  "c2-intercultural-03": ["Assume quiet participants have agreed to the draft", "because of to"],
  "c2-intercultural-04": ["Translate every reference literally even when its force is lost", "as if to"],
  "c2-intercultural-05": ["Assign speaking styles by each person's nationality", "inferred to"],
  "c2-intercultural-06": ["The exact casual tone of the first message", "by to"],
  "c2-precision-01": ["He ignores the counterexample and repeats the original claim", "all alone of"],
  "c2-precision-02": ["Accept an unsupported accusation to avoid disagreement", "in by"],
  "c2-precision-03": ["Protect the chair's reputation by leaving the error uncorrected", "but despite"],
  "c2-precision-04": ["All optional stops are already authorised in writing", "unresolvedly"],
  "c2-precision-05": ["A final booking is made before staffing is checked", "for without"],
  "c2-precision-06": ["A permanent decision without comparing trial results", "for being to"],
};

export function fourthOptionsFor(lessonId: string) {
  const options = fourthOptions[lessonId];
  if (!options) throw new Error(`Missing fourth options for lesson ${lessonId}`);
  return options;
}
