export type StoreMission = {
  id: string; title: string; scene: string;
  decisions: { question: string; options: [string, string, string]; answer: number; explanation: string }[];
  writing: string; model: string; checklist: string[];
};
export const storeMissions: Record<string, StoreMission[]> = {
  "practice-travel": [
    { id: "cafe", title: "Seu pedido veio diferente", scene: "Server: Here's your coffee with milk.\nYou ordered tea without milk. Your train leaves in ten minutes.\nServer: I'm sorry. Would you like a new drink or a refund?",
      decisions: [
        { question: "Como corrigir o pedido com clareza e educação?", options: ["Could I have extra milk, please?", "Excuse me, I ordered tea without milk.", "I want milk in my coffee."], answer: 1, explanation: "I ordered informa o pedido anterior; without milk preserva o detalhe. Não é necessário acusar o atendente." },
        { question: "Você prefere o dinheiro de volta porque precisa sair. Qual resposta resolve a situação?", options: ["A refund, please. I need to catch my train.", "A new drink, please. I have lots of time.", "A receipt, please. I need to catch my train."], answer: 0, explanation: "Refund pede reembolso; receipt pede um comprovante. A segunda frase explica a urgência. Pedir uma nova bebida contradiz sua decisão." },
      ], writing: "Escreva duas falas: corrija um pedido diferente e peça uma solução. Troque a bebida e explique sua preferência.", model: "Excuse me, I ordered orange juice, not coffee. Could I have the juice, please? I can wait a few minutes.", checklist: ["Ficou claro o que pedi?", "Solicitei uma solução?", "Usei please ou excuse me de modo adequado?"] },
    { id: "hotel", title: "Um quarto para duas pessoas", scene: "Receptionist: Your booking is for one person and two nights.\nYour confirmation says two people and two nights.\nReceptionist: Could you show me the confirmation? We have a room with two beds available.",
      decisions: [
        { question: "O que precisa ser corrigido?", options: ["The number of nights.", "The name of the hotel.", "The number of guests."], answer: 2, explanation: "O número de noites coincide. One person e two people mostram a divergência sobre hóspedes." },
        { question: "Escolha a resposta que apresenta evidência e confirma uma necessidade.", options: ["I have no booking and I want to leave.", "Here is my confirmation. Does the room have two beds?", "Please cancel both nights immediately."], answer: 1, explanation: "A confirmação permite conferir a reserva e a pergunta checa a configuração do quarto sem cancelar a estadia." },
      ], writing: "Responda ao hotel em três frases: apresente a reserva, corrija o número de pessoas e faça uma pergunta sobre o quarto.", model: "I have a booking for two people. The confirmation is on my phone. Is breakfast included?", checklist: ["Usei people para mais de uma pessoa?", "Corrigi apenas o dado divergente?", "Minha pergunta pode receber uma resposta útil?"] },
  ],
  "practice-team": [
    { id: "deadline", title: "Negociar sem prometer demais", scene: "Maya: Can we send the full report on Friday?\nLeo: The analysis will be ready, but the supplier's figures arrive on Monday.\nMaya: The client needs something for a meeting on Friday.\nLeo: We could send an interim summary and mark the missing figures clearly.",
      decisions: [
        { question: "Qual compromisso respeita a necessidade do cliente e o limite dos dados?", options: ["Send a clearly labelled interim summary on Friday and update it after Monday's figures arrive.", "Present estimated figures as confirmed results.", "Promise the complete report on Friday without conditions."], answer: 0, explanation: "A entrega parcial atende à reunião sem ocultar a dependência. A atualização deve ter um prazo combinado após receber e conferir os dados." },
        { question: "Como pedir o próximo acordo de modo específico?", options: ["Everything will definitely be perfect.", "Whatever you think is fine.", "Would Tuesday work for the revised report, provided the figures arrive on Monday?"], answer: 2, explanation: "A pergunta oferece um prazo e explicita a condição. O cliente pode aceitar, negociar ou propor outra prioridade." },
      ], writing: "Escreva um e-mail de 80–120 palavras com a entrega de sexta, a limitação e uma proposta condicional de atualização. Termine pedindo confirmação.", model: "We can send an interim summary on Friday for your meeting. It will clearly identify the supplier figures that are still missing. Provided those arrive on Monday, we propose sending the revised report on Tuesday. Would that timetable meet your needs?", checklist: ["Distingui entrega parcial e final?", "Nomeei a dependência?", "Pedi confirmação sem tratar a proposta como acordo?"] },
    { id: "plan", title: "Uma mudança de última hora", scene: "The outdoor workshop was scheduled for Saturday. Heavy rain is expected. The library can offer a smaller room that seats twenty people, but thirty have registered. An online session would include everyone, although two participants have unreliable internet. The organiser asks you for a recommendation and a backup plan.",
      decisions: [
        { question: "Qual conclusão reconhece a principal perda de cada alternativa?", options: ["Every option includes everyone without adjustment.", "The room limits attendance; online access may exclude two people unless support is arranged.", "Moving indoors solves the capacity problem automatically."], answer: 1, explanation: "A sala resolve o clima, mas não a capacidade. O formato online evita esse limite físico e cria uma necessidade de acesso." },
        { question: "Qual informação ajuda mais a testar uma solução inclusiva?", options: ["Whether the library can provide internet access for the two participants during the online session.", "Whether the workshop could finish ten minutes earlier.", "Whether the invitation should use a more formal greeting."], answer: 0, explanation: "Essa pergunta testa se o espaço disponível pode servir como ponto de acesso. A solução ainda precisa de confirmação, equipamento e horário." },
      ], writing: "Recomende uma solução em 80–120 palavras. Inclua uma condição a confirmar e um plano alternativo se ela não se concretizar.", model: "I suggest an online workshop, provided we can arrange reliable access for the two participants. We should ask whether they could join from the library. If that is not possible, we should consult the group about rescheduling rather than silently excluding them.", checklist: ["Expliquei quem seria afetado?", "Separei possibilidade e confirmação?", "Meu plano alternativo responde ao problema original?"] },
  ],
  "practice-nuance": [
    { id: "evidence", title: "Duas fontes, uma decisão", scene: "A six-week trial at Branch A found higher customer satisfaction after appointments were introduced. Branch B introduced the same system but recorded no reduction in waiting times. Branch A surveyed only customers who attended; Branch B measured all arrivals, including people without appointments. A director concludes that the reports contradict each other and that one must be wrong.",
      decisions: [
        { question: "Qual síntese preserva a comparabilidade limitada?", options: ["Appointments necessarily reduce waiting times everywhere.", "Branch B proves that satisfaction cannot improve.", "Satisfaction and waiting time are different outcomes, measured in different groups; the findings may coexist."], answer: 2, explanation: "Os indicadores e as populações diferem. A coexistência é plausível; isso não prova eficácia universal nem invalida uma fonte." },
        { question: "Qual recomendação é proporcional à evidência?", options: ["Roll out the system everywhere because satisfaction is the only relevant outcome.", "Measure both outcomes in comparable groups before deciding on wider adoption.", "Discard every response from customers without appointments."], answer: 1, explanation: "Uma avaliação comparável ajuda a distinguir efeitos e custos. Excluir atendimentos sem agendamento apagaria parte importante do serviço." },
      ], writing: "Escreva uma nota de 150–200 palavras que corrija a falsa contradição, proponha uma avaliação e reconheça uma limitação que permaneceria.", model: "The reports need not be inconsistent: one concerns satisfaction among attendees, whereas the other covers waiting times for all arrivals. A broader trial should track both measures in comparable groups. Even then, differences between branches may limit how confidently the results can be generalised.", checklist: ["Preservei população e indicador de cada fonte?", "Evitei converter coexistência em prova de eficácia?", "A limitação é específica, e não apenas 'more research is needed'?"] },
    { id: "tone", title: "Precisão sem acusação", scene: "A colleague drafts this update: 'As everyone should already know, the revised instructions were obviously clear. Any further confusion is the responsibility of the local teams.' Yet two offices received different versions, and the central team has not confirmed which one is current. You must edit the message for the affected teams without hiding the operational problem.",
      decisions: [
        { question: "Qual pressuposto o texto impõe sem sustentação?", options: ["That everyone received and understood the same clear instructions.", "That different offices exist.", "That a message can be revised."], answer: 0, explanation: "Should already know e obviously tratam clareza e conhecimento compartilhado como dados. A divergência de versões contradiz essa base." },
        { question: "Qual reformulação mantém responsabilidade e próximo passo?", options: ["There may perhaps possibly be something somewhere to consider.", "Local teams must stop asking questions because the message is clear.", "Two versions appear to be circulating. The central team will confirm the current instructions before asking offices to proceed."], answer: 2, explanation: "A reformulação nomeia o problema e atribui uma ação. Ela evita tanto a acusação sem evidência quanto uma cautela tão vaga que impede agir." },
      ], writing: "Reescreva o aviso em 100–150 palavras para as equipes. Depois explique, em inglês, duas escolhas que alteraram pressupostos ou responsabilidade.", model: "We have identified different versions of the instructions in circulation. Please pause implementation while the central team confirms the current version. We will send a single reference document and explain what has changed. If you have already acted on an earlier version, let us know so we can agree on the next steps.", checklist: ["Removi a acusação sem apagar o problema?", "Deixei claro quem fará o quê?", "Justifiquei o efeito de duas escolhas linguísticas?"] },
  ],
};
