// Imported only by the server route and administrative audio generator.
import type { LearnerLevel } from "./onboarding-shared.ts";
export type PlacementSkill =
  "vocabulary" | "grammar" | "reading" | "context" | "listening";
export type PlacementItem = {
  id: string;
  level: LearnerLevel;
  skill: PlacementSkill;
  prompt: string;
  options: string[];
  answer: number;
  transcript?: string;
};
const skills: PlacementSkill[] = [
  "vocabulary",
  "vocabulary",
  "grammar",
  "grammar",
  "grammar",
  "reading",
  "reading",
  "reading",
  "context",
  "context",
  "listening",
  "listening",
];
// Each row contains a prompt, the correct response and three plausible distractors.
const rows: Record<LearnerLevel, string[][]> = {
  A1: [
    [
      "You want to drink something. Which is a drink?",
      "Water",
      "Bread",
      "Chair",
      "Rice",
    ],
    ["Your mother’s sister is your…", "aunt", "daughter", "uncle", "son"],
    ["She ___ a student.", "is", "are", "am", "be"],
    ["I have two ___.", "children", "child", "childs", "childes"],
    ["___ you like coffee?", "Do", "Does", "Are", "Is"],
    [
      "The shop opens at nine and closes at five. When can you shop?",
      "At ten in the morning",
      "At six in the morning",
      "At eight in the evening",
      "At six in the evening",
    ],
    [
      "Sam lives near school. He walks there every morning. How does he travel?",
      "On foot",
      "By bus",
      "By train",
      "By bike",
    ],
    [
      "Please bring a pencil. Books are on your desk. What do you need to bring?",
      "A pencil",
      "A desk",
      "A book",
      "A bag",
    ],
    [
      "Someone says “Thank you.” What is a suitable reply?",
      "You’re welcome.",
      "Good night.",
      "I’m fifteen.",
      "It’s Tuesday.",
    ],
    [
      "You meet a new classmate. Ask their name.",
      "What’s your name?",
      "Where is the pen?",
      "How much is it?",
      "What time is it?",
    ],
    [
      "What does the speaker want?",
      "Tea",
      "Coffee",
      "Juice",
      "Milk",
      "Sparky: Would you like coffee? Pinky: No, thank you. Tea, please.",
    ],
    [
      "Where is the bag?",
      "Under the chair",
      "On the table",
      "By the door",
      "On the chair",
      "Pinky: Where is my bag? Sparky: It is under the chair, next to your shoes.",
    ],
  ],
  A2: [
    [
      "A person who repairs cars is a…",
      "mechanic",
      "receptionist",
      "passenger",
      "chemist",
    ],
    [
      "The opposite of “borrow” in “Can I borrow your pen?” is…",
      "lend",
      "spend",
      "keep",
      "bring",
    ],
    ["We ___ to the beach last Sunday.", "went", "go", "gone", "going"],
    [
      "This bag is ___ than that one.",
      "heavier",
      "heavy",
      "heaviest",
      "more heavy",
    ],
    ["There isn’t ___ milk left.", "much", "many", "a few", "several"],
    [
      "The train is delayed by twenty minutes. It normally leaves at 10:10. When is it now expected?",
      "10:30",
      "10:20",
      "09:50",
      "10:10",
    ],
    [
      "Mina used to cycle to work, but now takes the bus because her office moved. Why did she change transport?",
      "Her workplace changed location",
      "Her bicycle broke",
      "She lost her job",
      "The bus became free",
    ],
    [
      "Returns are accepted within 14 days with a receipt. You bought a shirt yesterday. What must you bring to return it?",
      "Proof of purchase",
      "A membership card",
      "A written complaint",
      "Another shirt",
    ],
    [
      "You cannot hear someone on the phone. What should you say?",
      "Could you speak a little louder?",
      "You should call yesterday.",
      "I have already listened.",
      "You must stop speaking.",
    ],
    [
      "You are late for an appointment. Choose the most useful message.",
      "I’m sorry; I’ll be there in ten minutes.",
      "I was here next week.",
      "You are welcome to leave.",
      "I don’t know your name.",
    ],
    [
      "Why is Pinky changing her order?",
      "She cannot eat cheese",
      "The soup is too hot",
      "She wants something cheaper",
      "There is no salad",
      "Sparky: The sandwich comes with cheese. Pinky: Oh, I cannot eat cheese. Could I have the vegetable soup instead?",
    ],
    [
      "When will they meet?",
      "Friday afternoon",
      "Thursday morning",
      "Friday morning",
      "Saturday afternoon",
      "Pinky: Can we meet on Thursday? Sparky: I am busy all day. Friday afternoon works. Pinky: Great, see you then.",
    ],
  ],
  B1: [
    [
      "If a meeting is “put off”, it is…",
      "postponed",
      "finished",
      "attended",
      "recorded",
    ],
    [
      "Choose the word: She made a useful ___ to the discussion.",
      "contribution",
      "distribution",
      "construction",
      "instruction",
    ],
    [
      "If it rains tomorrow, we ___ indoors.",
      "will stay",
      "would stay",
      "stayed",
      "had stayed",
    ],
    ["I ___ here since 2020.", "have lived", "live", "am living", "lived"],
    [
      "The book ___ by a local author last year.",
      "was written",
      "has writing",
      "wrote",
      "is writing",
    ],
    [
      "A library extended its hours after residents complained they could not visit after work. What problem did the change address?",
      "Access for working residents",
      "A shortage of books",
      "Excessive membership fees",
      "Noise during the day",
    ],
    [
      "Lee enjoyed working from home but missed informal chats. He now goes to the office twice a week. What does his choice suggest?",
      "He wants a balance of flexibility and social contact",
      "He dislikes all remote work",
      "He cannot work without supervision",
      "He works only two days a week",
    ],
    [
      "The museum ticket includes the permanent collection. Special exhibitions cost extra. What can you see without another payment?",
      "The permanent collection",
      "Every temporary exhibition",
      "Only the entrance hall",
      "All evening events",
    ],
    [
      "A friend seems disappointed after an interview. Choose a supportive response without making a promise.",
      "That sounds tough. Do you want to talk about it?",
      "You will definitely get the job.",
      "You should never apply again.",
      "Interviews are always easy.",
    ],
    [
      "You disagree with a colleague’s suggestion. Choose a constructive reply.",
      "I see the benefit, but could we consider the cost?",
      "That makes no sense at all.",
      "Whatever you say is correct.",
      "Let us never discuss it again.",
    ],
    [
      "What will they do first?",
      "Ask whether another room is available",
      "Cancel the workshop",
      "Buy new equipment",
      "Invite more people",
      "Sparky: The room is too small for everyone who registered. Pinky: Before cancelling, let’s ask if the larger room is free. Sparky: Good idea. I will call reception now.",
    ],
    [
      "Why does Pinky prefer the train?",
      "She can use the journey to work",
      "It always arrives earlier",
      "It costs less than the bus",
      "She dislikes reading",
      "Sparky: The bus is cheaper. Pinky: True, but the train has tables and a quiet carriage. I can finish my report on the way. Sparky: That makes sense.",
    ],
  ],
  B2: [
    [
      "“The findings are tentative” means they are…",
      "not yet certain",
      "deliberately false",
      "widely accepted",
      "highly detailed",
    ],
    [
      "Which best completes “We need to ___ a balance between speed and accuracy”?",
      "strike",
      "hit",
      "reach out",
      "take up",
    ],
    [
      "If I had checked the timetable, I ___ the train.",
      "would not have missed",
      "will not miss",
      "did not miss",
      "would not miss",
    ],
    [
      "By next June, she ___ here for five years.",
      "will have worked",
      "will work",
      "has worked",
      "had worked",
    ],
    [
      "Despite ___ little time, they completed the project.",
      "having",
      "to have",
      "they had",
      "have",
    ],
    [
      "A city introduced bike lanes. Cycling increased, but the report notes that fuel prices rose at the same time. Why mention fuel prices?",
      "They offer another possible explanation for the increase",
      "They prove bike lanes were ineffective",
      "They show cycling became more dangerous",
      "They establish that all drivers switched to bikes",
    ],
    [
      "A reviewer calls a film “visually stunning, although its characters rarely move beyond familiar stereotypes.” What is the assessment?",
      "Strong presentation but limited character depth",
      "Excellent acting and original characters",
      "Poor visuals but a convincing story",
      "Entirely negative without qualification",
    ],
    [
      "Staff welcomed flexible hours, provided that meetings remained within a shared four-hour window. What qualified their support?",
      "Maintaining time for collaboration",
      "Reducing the working week to four hours",
      "Removing all meetings",
      "Making attendance optional",
    ],
    [
      "A client requests work outside the agreed scope. Which response sets a professional boundary?",
      "We can add that, but we’ll need to revise the timeline and fee.",
      "It is impossible to change anything.",
      "Sure, no matter how long it takes.",
      "You should have thought of that earlier.",
    ],
    [
      "“I take your point, but the evidence is mixed.” What is the speaker doing?",
      "Acknowledging an argument while qualifying agreement",
      "Withdrawing every objection",
      "Accusing someone of dishonesty",
      "Changing the subject completely",
    ],
    [
      "What concern does Pinky raise?",
      "The survey may exclude some residents",
      "The survey is too expensive to print",
      "Residents are uninterested in transport",
      "The deadline is legally binding",
      "Sparky: The online survey should tell us what residents need. Pinky: It will tell us what connected residents need. What about people who rarely use the internet? Sparky: We should add paper forms at the library.",
    ],
    [
      "What do they agree to do?",
      "Try a limited pilot before expanding",
      "Launch everywhere immediately",
      "Abandon the service permanently",
      "Wait until all uncertainty disappears",
      "Pinky: The proposal looks promising, but we have no evidence it will work here. Sparky: A small pilot would limit the risk. Pinky: Yes, as long as we define success before we start.",
    ],
  ],
  C1: [
    [
      "“The policy may exacerbate inequality” means it may…",
      "make inequality worse",
      "measure inequality accurately",
      "remove inequality gradually",
      "conceal inequality completely",
    ],
    [
      "Which phrase best replaces “a qualification that limits the claim”?",
      "a caveat",
      "a consensus",
      "a precedent",
      "a mandate",
    ],
    [
      "Not until the audit was complete ___ the scale of the problem.",
      "did we realise",
      "we realised",
      "had we realise",
      "we did realised",
    ],
    [
      "The committee recommended that the proposal ___ revised.",
      "be",
      "is",
      "was",
      "being",
    ],
    [
      "Had the evidence been stronger, the outcome ___ different.",
      "might have been",
      "may be",
      "was being",
      "has been",
    ],
    [
      "The author supports open data but argues that publishing raw datasets without context can produce confident misinterpretations. What is the central qualification?",
      "Transparency needs interpretive support",
      "Data should remain inaccessible",
      "Only experts should conduct research",
      "Misinterpretations prove the data are false",
    ],
    [
      "A company describes redundancies as “aligning resources with strategic priorities.” What does this wording primarily achieve?",
      "It frames job cuts in impersonal managerial terms",
      "It commits to rehiring every employee",
      "It explains the exact financial calculation",
      "It denies that staffing will change",
    ],
    [
      "An essay praises citizen consultation yet notes that those with time and confidence often dominate it. What tension is identified?",
      "Formal openness may coexist with unequal participation",
      "Consultation always produces unanimous decisions",
      "Expertise makes consultation unnecessary",
      "Participation inevitably reduces confidence",
    ],
    [
      "“Perhaps we could revisit the assumptions before signing this off.” In a formal meeting, this most likely functions as…",
      "a tactful request to delay approval",
      "an unconditional endorsement",
      "a request to repeat the signature",
      "an admission that no assumptions exist",
    ],
    [
      "Which response best mediates between speed and inclusion?",
      "Could we publish an interim decision and reserve a consultation window before final approval?",
      "We should ignore whichever group is slower.",
      "Let us promise everyone their preferred outcome.",
      "There is no point discussing trade-offs.",
    ],
    [
      "What is Sparky’s underlying objection?",
      "The metric may reward activity rather than meaningful outcomes",
      "The team has collected no data",
      "The target is too difficult to calculate",
      "The report should contain more graphs",
      "Pinky: We doubled the number of workshops, so the programme is clearly successful. Sparky: That tells us we delivered more. It does not yet tell us whether anyone’s skills improved. Pinky: Then we need follow-up evidence.",
    ],
    [
      "How should the final remark be interpreted?",
      "Conditional support with a concern about implementation",
      "Unqualified enthusiasm",
      "A request to cancel consultation",
      "A denial that resources matter",
      "Sparky: Everyone supports the new mentoring scheme in principle. Pinky: In principle is doing quite a lot of work there. Unless mentors get protected time, it is another good idea added to an already full calendar.",
    ],
  ],
  C2: [
    [
      "“The concession was largely cosmetic” implies it…",
      "changed appearances more than substance",
      "was costly but effective",
      "resolved the underlying dispute",
      "was unintentionally generous",
    ],
    [
      "Which best describes an argument that seems plausible but is misleading?",
      "specious",
      "scrupulous",
      "unequivocal",
      "incisive",
    ],
    [
      "So compelling ___ that even the sceptics reconsidered.",
      "was the evidence",
      "the evidence was",
      "had the evidence",
      "did the evidence",
    ],
    [
      "He is not so much opposed to reform ___ doubtful of its timing.",
      "as",
      "than",
      "but",
      "like",
    ],
    [
      "Were it not for the archival records, the claim ___ impossible to verify.",
      "would be",
      "will have been",
      "had been",
      "is being",
    ],
    [
      "“The review was exhaustive in its enumeration of failures, less so in its curiosity about their causes.” What criticism is implied?",
      "Breadth of description substituted for explanatory depth",
      "The review invented failures",
      "The causes were too numerous to list",
      "The reviewer approved the organisation’s response",
    ],
    [
      "A historian rejects both the claim that events were inevitable and the idea that they were merely accidental. What approach is implied?",
      "An account of constraints interacting with contingent choices",
      "A search for one decisive cause",
      "A refusal to use documentary evidence",
      "An assumption that outcomes cannot be explained",
    ],
    [
      "“The policy’s elegance survives only so long as one declines to ask who bears its costs.” What is the author challenging?",
      "An attractive abstraction that obscures distributional consequences",
      "The grammatical clarity of the policy",
      "The impossibility of measuring any cost",
      "The claim that the policy has no supporters",
    ],
    [
      "After a sweeping promise, someone says “That would be a first.” What is the most likely pragmatic meaning?",
      "Scepticism expressed through understated irony",
      "Literal confirmation of a scheduled first event",
      "Enthusiastic approval without reservation",
      "A request for chronological clarification",
    ],
    [
      "Which reformulation preserves a nuanced claim? “The evidence is consistent with the hypothesis, but does not uniquely support it.”",
      "The hypothesis fits the evidence, although alternatives may fit it too.",
      "The evidence proves the hypothesis beyond doubt.",
      "The hypothesis has been conclusively disproved.",
      "No relationship exists between evidence and hypothesis.",
    ],
    [
      "What distinction does Pinky insist on?",
      "Not disproving a claim is different from substantiating it",
      "All untested claims should be treated as false",
      "Consensus is sufficient proof",
      "The original study must be repeated without changes",
      "Sparky: Nobody has demonstrated that the intervention failed. Pinky: Granted. But the absence of a refutation is not evidence that it worked. We need a positive case, ideally against a credible comparison.",
    ],
    [
      "What does Sparky’s final response accomplish?",
      "It accepts the principle while challenging the distribution of risk",
      "It rejects experimentation categorically",
      "It agrees that all parties face equal consequences",
      "It changes the discussion to personal ambition",
      "Pinky: We must be willing to fail if we want to innovate. Sparky: Certainly. Though I would be more persuaded by that invitation if those making it were also the ones expected to absorb the failure.",
    ],
  ],
};
export const placementBank: PlacementItem[] = Object.entries(rows).flatMap(
  ([level, entries]) =>
    entries.map((row, index) => ({
      id: `placement-v1-${level.toLowerCase()}-${index + 1}`,
      level: level as LearnerLevel,
      skill: skills[index],
      prompt: row[0],
      options: row.slice(1, 5),
      answer: 0,
      ...(row[5] ? { transcript: row[5] } : {}),
    })),
);
