// Generated by scripts/build-wardrobe-manifest.mjs. Regenerate after changing a sprite.
export const wardrobeAssetRevisions: Readonly<Record<string, string>> = {
  "/visuals/wardrobe/bases/sparky.png": "029ecaa1c81ee805",
  "/visuals/wardrobe/bases/pinky.png": "5abfc61a7ae46290",
  "/visuals/wardrobe/outfits/pinky-focus-look.png": "b1b3d817a2784d04",
  "/visuals/wardrobe/outfits/sparky-explorer-look.png": "62bebe7876f4d878",
  "/visuals/wardrobe/outfits/sparky-academy-look.png": "a39045aff68cdccf",
  "/visuals/wardrobe/outfits/pinky-atelier-look.png": "088a7391c7c05b53",
  "/visuals/wardrobe/outfits/sparky-cozy-reader.png": "9eac14e36766c8cf",
  "/visuals/wardrobe/outfits/sparky-science-club.png": "5ceaa73eed6c6ed7",
  "/visuals/wardrobe/outfits/sparky-debate-captain.png": "1b8872ebcd748915",
  "/visuals/wardrobe/outfits/sparky-urban-sport.png": "4e3edae104b7c68a",
  "/visuals/wardrobe/outfits/pinky-campus.png": "7656d30f10a04322",
  "/visuals/wardrobe/outfits/pinky-festival.png": "c2d7a9936cf80b0b",
  "/visuals/wardrobe/outfits/pinky-creative-lab.png": "424a3a94c414e55d",
  "/visuals/wardrobe/outfits/pinky-presenter.png": "20ab07908e532f02",
  "/visuals/wardrobe/accessories/urban-cap-sparky.png": "bc6dc2f4a39971c5",
  "/visuals/wardrobe/accessories/urban-cap-pinky.png": "075ff49347568a30",
  "/visuals/wardrobe/accessories/lavender-beret-sparky.png": "3e33dc1d61ff06e0",
  "/visuals/wardrobe/accessories/lavender-beret-pinky.png": "5334989fa00be576",
  "/visuals/wardrobe/accessories/focus-headphones-sparky.png": "fdad07f112142e82",
  "/visuals/wardrobe/accessories/focus-headphones-pinky.png": "905ac4aa664aa20a",
  "/visuals/wardrobe/accessories/knit-beanie-sparky.png": "b65cf60e83a968f6",
  "/visuals/wardrobe/accessories/knit-beanie-pinky.png": "c69448e938586225",
  "/visuals/wardrobe/accessories/amber-readers-sparky.png": "525e3638a4cfde74",
  "/visuals/wardrobe/accessories/amber-readers-pinky.png": "04c30ce38968f484",
  "/visuals/wardrobe/accessories/round-readers-sparky.png": "bc9915f36dd2cf79",
  "/visuals/wardrobe/accessories/round-readers-pinky.png": "1e87f2cc317c02af",
  "/visuals/wardrobe/accessories/sunglasses-sparky.png": "5872403fb369b19e",
  "/visuals/wardrobe/accessories/sunglasses-pinky.png": "7894d5b21826046c",
  "/visuals/wardrobe/accessories/science-visor-sparky.png": "d41f1d5337171d3d",
  "/visuals/wardrobe/accessories/science-visor-pinky.png": "28aaec93d4aeaf67",
  "/visuals/wardrobe/accessories/study-scarf-sparky.png": "be50ad44aecc57eb",
  "/visuals/wardrobe/accessories/study-scarf-pinky.png": "f42f4d6e31c7c526",
  "/visuals/wardrobe/accessories/debate-bow-sparky.png": "58e1c86dd8e5249e",
  "/visuals/wardrobe/accessories/debate-bow-pinky.png": "c206d1462a4ecaa3",
  "/visuals/wardrobe/accessories/constellation-pendant-sparky.png": "fd19283c3943feb7",
  "/visuals/wardrobe/accessories/constellation-pendant-pinky.png": "288792601429cbef",
  "/visuals/wardrobe/accessories/club-lanyard-sparky.png": "97dab9f084bb8cde",
  "/visuals/wardrobe/accessories/club-lanyard-pinky.png": "461ff93e1ed7d68e",
  "/visuals/wardrobe/accessories/explorer-satchel-sparky.png": "aa02d5c80926d02e",
  "/visuals/wardrobe/accessories/explorer-satchel-pinky.png": "3307f3f38ca375b2",
  "/visuals/wardrobe/accessories/compact-backpack-sparky-back.png": "503d52b1769cef8e",
  "/visuals/wardrobe/accessories/compact-backpack-sparky.png": "808b5dd5fc48eebe",
  "/visuals/wardrobe/accessories/compact-backpack-pinky.png": "c401db8ba280551a",
  "/visuals/wardrobe/accessories/book-tote-sparky.png": "6b421dd23c12566b",
  "/visuals/wardrobe/accessories/book-tote-pinky.png": "493bbb399c386338",
  "/visuals/wardrobe/accessories/rocket-pack-sparky-back.png": "89ca0593c871d151",
  "/visuals/wardrobe/accessories/rocket-pack-sparky.png": "bb3840e0378901cd",
  "/visuals/wardrobe/accessories/rocket-pack-pinky.png": "9f84edc13e84e77c"
};

// Content revisions refresh browser and service-worker caches without changing item IDs.
export function wardrobeAssetUrl(path: string): string {
  const pathname = path.split("?")[0];
  const revision = wardrobeAssetRevisions[pathname];
  return revision ? `${pathname}?v=${revision}` : path;
}
