"""Build a tiny decorative energy envelope without modifying the private audio.

Requires PyAV and NumPy. Values describe average intensity, not detected beats.
"""
import json
from pathlib import Path

import av
import numpy as np

root = Path(__file__).resolve().parent.parent
tracks = {}
for track, name in [('perfect-local', 'audio.mp3'), ('heartless-local', 'heartless/audio.mp3'), ('stay-at-your-house-local', 'stay-at-your-house/audio.mp3'), ('buttercup-local', 'buttercup-local/audio.mp3')]:
    with av.open(str(root / '.music-assets' / name)) as source:
        resampler = av.AudioResampler(format='fltp', layout='mono', rate=8000)
        frames = [f.to_ndarray().ravel() for frame in source.decode(audio=0) for f in resampler.resample(frame)]
        frames.extend(f.to_ndarray().ravel() for f in resampler.resample(None))
        audio = np.concatenate(frames)
    # One-second trailing RMS, sampled every quarter second, smoothed again in
    # the client by interpolation. Short transients do not produce flashes.
    power = np.concatenate(([0.0], np.cumsum(audio.astype(np.float64) ** 2)))
    ends = np.arange(0, len(audio), 2000)
    starts = np.maximum(0, ends - 8000)
    rms = np.sqrt((power[ends] - power[starts]) / np.maximum(1, ends - starts))
    scale = max(float(np.percentile(rms, 95)), 1e-9)
    values = np.round(np.clip(rms / scale, 0, 1) * 100).astype(int).tolist()
    tracks[track] = {'step': .25, 'values': values}

output = '// Generated by scripts/build-music-energy.py; no audio or lyrics.\n'
output += 'export const musicEnergy: Record<string, { step: number; values: number[] }> = '
output += json.dumps(tracks, separators=(',', ':')) + ';\n'
(root / 'src/lib/music-energy.ts').write_text(output, encoding='utf8')
print('Prepared energy envelopes:', {track: len(data['values']) for track, data in tracks.items()})
